#include <3ds.h>
#include <iostream>
#include <string>
#include <cstdlib>
#include <ctime>
#include <cstring>

using namespace std;

int A = 0;

int main(void)
{
	gfxInitDefault();
	consoleInit(GFX_TOP, NULL);
	u8 param[0x300];
	u8 hmac[0x20];
	u8 regionCode;
	u64 shopID;
	CFGU_SecureInfoGetRegion(&regionCode);
	switch (regionCode)
	{
	case 0:
		shopID = 0x0004001000020900;
		break;
	case 1:
		shopID = 0x0004001000021900;
		break;
	case 2:
		shopID = 0x0004001000022900;
		break;
	default:
		shopID = 0x00;
	}
        srand(time(0));

        cout << "v2.4" << endl;
        cout << "if it dont work then go for a pron break and try again lator!" << endl;
        cout << "if u too scared for pokegomz pres b" << endl;

	for(A = 0; A < 60000; A = A+5){
		hidScanInput();
		u32 kDown = hidKeysDown();
		if (A == 1800) cout << "DOWNLOADING FLIES OF POKEGOMZ" << endl;
		if (A == 3600) cout << "DOWNLOA COMPLETE!" << endl;
		if (A == 5400)
{
 cout << "bribing gam freck to aron valt all valted pokegomz" << endl;
 cout << "in sord and sheld.." << endl;
}
		if (A == 7200) cout << "installing frii pokegom gam.." << endl;
		if (A == 9600) cout << "frii pokegom gam instal complet!" << endl;
		if (A == 10200) cout << "jus make sur u don kil ur pokegomz OR U BRIC!" << endl;
		if (A == 10800) cout << "pathcing flies of pokegomz.." << endl;
		if (A == 11400) cout << "sicc!! now generat new systume imag" << endl;
		if (A == 13200) cout << "systume imag genrat now flash ontoo emptii brian" << endl;
		if (A == 15000) cout << "doo sam ting with reecuvury and FEI partishuns" << endl;
		if (A == 16800) cout << "nowe update PBTS MKPN eedishun too v2.0.0" << endl;
		if (A == 18600) cout << "now u hav v2.0.0 becaus v0.0.1 suck 4-bite bik." << endl;
                if (A == 20400) cout << "Downola 2TB ReshiRAM!" << endl;
		if (A == 22200) cout << "flash buy-os form u.." << endl;
		if (A == 23400) cout << "OH No HECK yo got frikken ban by MASUDA!!!" << endl;
		if (A == 25200) cout << "makin alt accooun (ur such a hackers)" << endl;
		if (A == 26100) cout << "u got aron ban my dud!!" << endl;
                if (A == 27000) cout << "cunvirtin flies of pokegomz" << endl;
                if (A == 27900) cout << "now imparti flies of pokegomz" << endl;
                if (A == 28800) cout << "Gib U pokegomz in rel lif.." << endl;
		if (A == 29700) {
                if (1 + (rand () % 809) == 1) cout << "Nowe u hav a rel liv Bulbasaur!!!!!" << endl;
                if (1 + (rand () % 809) == 2) cout << "Nowe u hav a rel liv Ivysaur!!!!!" << endl;
                if (1 + (rand () % 809) == 3) cout << "Nowe u hav a rel liv Venusaur!!!!!" << endl;
                if (1 + (rand () % 809) == 4) cout << "Nowe u hav a rel liv Charmander!!!!!" << endl;
                if (1 + (rand () % 809) == 5) cout << "Nowe u hav a rel liv Charmeleon!!!!!" << endl;
                if (1 + (rand () % 809) == 6) cout << "Nowe u hav a rel liv Charizard!!!!!" << endl;
                if (1 + (rand () % 809) == 7) cout << "Nowe u hav a rel liv Squirtle!!!!!" << endl;
                if (1 + (rand () % 809) == 8) cout << "Nowe u hav a rel liv Wartortle!!!!!" << endl;
                if (1 + (rand () % 809) == 9) cout << "Nowe u hav a rel liv Blastoise!!!!!" << endl;
                if (1 + (rand () % 809) == 10) cout << "Nowe u hav a rel liv Caterpie!!!!!" << endl;
                if (1 + (rand () % 809) == 11) cout << "Nowe u hav a rel liv Metapod!!!!!" << endl;
                if (1 + (rand () % 809) == 12) cout << "Nowe u hav a rel liv Butterfree!!!!!" << endl;
                if (1 + (rand () % 809) == 13) cout << "Nowe u hav a rel liv Weedle!!!!!" << endl;
                if (1 + (rand () % 809) == 14) cout << "Nowe u hav a rel liv Kakuna!!!!!" << endl;
                if (1 + (rand () % 809) == 15) cout << "Nowe u hav a rel liv Beedrill!!!!!" << endl;
                if (1 + (rand () % 809) == 16) cout << "Nowe u hav a rel liv Pidgey!!!!!" << endl;
                if (1 + (rand () % 809) == 17) cout << "Nowe u hav a rel liv Pidgeotto!!!!!" << endl;
                if (1 + (rand () % 809) == 18) cout << "Nowe u hav a rel liv Pidgeot!!!!!" << endl;
                if (1 + (rand () % 809) == 19) cout << "Nowe u hav a rel liv Rattata!!!!!" << endl;
                if (1 + (rand () % 809) == 20) cout << "Nowe u hav a rel liv Raticate!!!!!" << endl;
                if (1 + (rand () % 809) == 21) cout << "Nowe u hav a rel liv Spearow!!!!!" << endl;
                if (1 + (rand () % 809) == 22) cout << "Nowe u hav a rel liv Fearow!!!!!" << endl;
                if (1 + (rand () % 809) == 23) cout << "Nowe u hav a rel liv Ekans!!!!!" << endl;
                if (1 + (rand () % 809) == 24) cout << "Nowe u hav a rel liv Arbok!!!!!" << endl;
                if (1 + (rand () % 809) == 25) cout << "Nowe u hav a rel liv Pikachu!!!!!" << endl;
                if (1 + (rand () % 809) == 26) cout << "Nowe u hav a rel liv Raichu!!!!!" << endl;
                if (1 + (rand () % 809) == 27) cout << "Nowe u hav a rel liv Sandshrew!!!!!" << endl;
                if (1 + (rand () % 809) == 28) cout << "Nowe u hav a rel liv Sandslash!!!!!" << endl;
                if (1 + (rand () % 809) == 29) cout << "Nowe u hav a rel liv Nidoran F!!!!!" << endl;
                if (1 + (rand () % 809) == 30) cout << "Nowe u hav a rel liv Nidorina!!!!!" << endl;
                if (1 + (rand () % 809) == 31) cout << "Nowe u hav a rel liv Nidoqueen!!!!!" << endl;
                if (1 + (rand () % 809) == 32) cout << "Nowe u hav a rel liv Nidoran M!!!!!" << endl;
                if (1 + (rand () % 809) == 33) cout << "Nowe u hav a rel liv Nidorino!!!!!" << endl;
                if (1 + (rand () % 809) == 34) cout << "Nowe u hav a rel liv Nidoking!!!!!" << endl;
                if (1 + (rand () % 809) == 35) cout << "Nowe u hav a rel liv Clefairy!!!!!" << endl;
                if (1 + (rand () % 809) == 36) cout << "Nowe u hav a rel liv Clefable!!!!!" << endl;
                if (1 + (rand () % 809) == 37) cout << "Nowe u hav a rel liv Vulpix!!!!!" << endl;
                if (1 + (rand () % 809) == 38) cout << "Nowe u hav a rel liv Ninetales!!!!!" << endl;
                if (1 + (rand () % 809) == 39) cout << "Nowe u hav a rel liv Jigglypuff!!!!!" << endl;
                if (1 + (rand () % 809) == 40) cout << "Nowe u hav a rel liv Wigglytuff!!!!!" << endl;
                if (1 + (rand () % 809) == 41) cout << "Nowe u hav a rel liv Zubat!!!!!" << endl;
                if (1 + (rand () % 809) == 42) cout << "Nowe u hav a rel liv Golbat!!!!!" << endl;
                if (1 + (rand () % 809) == 43) cout << "Nowe u hav a rel liv Oddish!!!!!" << endl;
                if (1 + (rand () % 809) == 44) cout << "Nowe u hav a rel liv Gloom!!!!!" << endl;
                if (1 + (rand () % 809) == 45) cout << "Nowe u hav a rel liv Vileplume!!!!!" << endl;
                if (1 + (rand () % 809) == 46) cout << "Nowe u hav a rel liv Paras!!!!!" << endl;
                if (1 + (rand () % 809) == 47) cout << "Nowe u hav a rel liv Parasect!!!!!" << endl;
                if (1 + (rand () % 809) == 48) cout << "Nowe u hav a rel liv Venonat!!!!!" << endl;
                if (1 + (rand () % 809) == 49) cout << "Nowe u hav a rel liv Venomoth!!!!!" << endl;
                if (1 + (rand () % 809) == 50) cout << "Nowe u hav a rel liv Diglett!!!!!" << endl;
                if (1 + (rand () % 809) == 51) cout << "Nowe u hav a rel liv Dugtrio!!!!!" << endl;
                if (1 + (rand () % 809) == 52) cout << "Nowe u hav a rel liv Meowth!!!!!" << endl;
                if (1 + (rand () % 809) == 53) cout << "Nowe u hav a rel liv Persian!!!!!" << endl;
                if (1 + (rand () % 809) == 54) cout << "Nowe u hav a rel liv Psyduck!!!!!" << endl;
                if (1 + (rand () % 809) == 55) cout << "Nowe u hav a rel liv Golduck!!!!!" << endl;
                if (1 + (rand () % 809) == 56) cout << "Nowe u hav a rel liv Mankey!!!!!" << endl;
                if (1 + (rand () % 809) == 57) cout << "Nowe u hav a rel liv Primeape!!!!!" << endl;
                if (1 + (rand () % 809) == 58) cout << "Nowe u hav a rel liv Growlithe!!!!!" << endl;
                if (1 + (rand () % 809) == 59) cout << "Nowe u hav a rel liv Arcanine!!!!!" << endl;
                if (1 + (rand () % 809) == 60) cout << "Nowe u hav a rel liv Poliwag!!!!!" << endl;
                if (1 + (rand () % 809) == 61) cout << "Nowe u hav a rel liv Poliwhirl!!!!!" << endl;
                if (1 + (rand () % 809) == 62) cout << "Nowe u hav a rel liv Poliwrath!!!!!" << endl;
                if (1 + (rand () % 809) == 63) cout << "Nowe u hav a rel liv Abra!!!!!" << endl;
                if (1 + (rand () % 809) == 64) cout << "Nowe u hav a rel liv Kadabra!!!!!" << endl;
                if (1 + (rand () % 809) == 65) cout << "Nowe u hav a rel liv Alakazam!!!!!" << endl;
                if (1 + (rand () % 809) == 66) cout << "Nowe u hav a rel liv Machop!!!!!" << endl;
                if (1 + (rand () % 809) == 67) cout << "Nowe u hav a rel liv Machoke!!!!!" << endl;
                if (1 + (rand () % 809) == 68) cout << "Nowe u hav a rel liv Machamp!!!!!" << endl;
                if (1 + (rand () % 809) == 69) cout << "Nowe u hav a rel liv Bellsprout!!!!!" << endl;
                if (1 + (rand () % 809) == 70) cout << "Nowe u hav a rel liv Weepinbell!!!!!" << endl;
                if (1 + (rand () % 809) == 71) cout << "Nowe u hav a rel liv Victreebel!!!!!" << endl;
                if (1 + (rand () % 809) == 72) cout << "Nowe u hav a rel liv Tentacool!!!!!" << endl;
                if (1 + (rand () % 809) == 73) cout << "Nowe u hav a rel liv Tentacruel!!!!!" << endl;
                if (1 + (rand () % 809) == 74) cout << "Nowe u hav a rel liv Geodude!!!!!" << endl;
                if (1 + (rand () % 809) == 75) cout << "Nowe u hav a rel liv Graveler!!!!!" << endl;
                if (1 + (rand () % 809) == 76) cout << "Nowe u hav a rel liv Golem!!!!!" << endl;
                if (1 + (rand () % 809) == 77) cout << "Nowe u hav a rel liv Ponyta!!!!!" << endl;
                if (1 + (rand () % 809) == 78) cout << "Nowe u hav a rel liv Rapidash!!!!!" << endl;
                if (1 + (rand () % 809) == 79) cout << "Nowe u hav a rel liv Slowpoke!!!!!" << endl;
                if (1 + (rand () % 809) == 80) cout << "Nowe u hav a rel liv Slowbro!!!!!" << endl;
                if (1 + (rand () % 809) == 81) cout << "Nowe u hav a rel liv Magnemite!!!!!" << endl;
                if (1 + (rand () % 809) == 82) cout << "Nowe u hav a rel liv Magneton!!!!!" << endl;
                if (1 + (rand () % 809) == 83) cout << "Nowe u hav a rel liv Farfetch'd!!!!!" << endl;
                if (1 + (rand () % 809) == 84) cout << "Nowe u hav a rel liv Doduo!!!!!" << endl;
                if (1 + (rand () % 809) == 85) cout << "Nowe u hav a rel liv Dodrio!!!!!" << endl;
                if (1 + (rand () % 809) == 86) cout << "Nowe u hav a rel liv Seel!!!!!" << endl;
                if (1 + (rand () % 809) == 87) cout << "Nowe u hav a rel liv Dewgong!!!!!" << endl;
                if (1 + (rand () % 809) == 88) cout << "Nowe u hav a rel liv Grimer!!!!!" << endl;
                if (1 + (rand () % 809) == 89) cout << "Nowe u hav a rel liv Muk!!!!!" << endl;
                if (1 + (rand () % 809) == 90) cout << "Nowe u hav a rel liv Shellder!!!!!" << endl;
                if (1 + (rand () % 809) == 91) cout << "Nowe u hav a rel liv Cloyster!!!!!" << endl;
                if (1 + (rand () % 809) == 92) cout << "Nowe u hav a rel liv Gastly!!!!!" << endl;
                if (1 + (rand () % 809) == 93) cout << "Nowe u hav a rel liv Haunter!!!!!" << endl;
                if (1 + (rand () % 809) == 94) cout << "Nowe u hav a rel liv Gengar!!!!!" << endl;
                if (1 + (rand () % 809) == 95) cout << "Nowe u hav a rel liv Onix!!!!!" << endl;
                if (1 + (rand () % 809) == 96) cout << "Nowe u hav a rel liv Drowzee!!!!!" << endl;
                if (1 + (rand () % 809) == 97) cout << "Nowe u hav a rel liv Hypno!!!!!" << endl;
                if (1 + (rand () % 809) == 98) cout << "Nowe u hav a rel liv Krabby!!!!!" << endl;
                if (1 + (rand () % 809) == 99) cout << "Nowe u hav a rel liv Kingler!!!!!" << endl;
                if (1 + (rand () % 809) == 100) cout << "Nowe u hav a rel liv Voltorb!!!!!" << endl;
                if (1 + (rand () % 809) == 101) cout << "Nowe u hav a rel liv Electrode!!!!!" << endl;
                if (1 + (rand () % 809) == 102) cout << "Nowe u hav a rel liv Exeggcute!!!!!" << endl;
                if (1 + (rand () % 809) == 103) cout << "Nowe u hav a rel liv Exeggutor!!!!!" << endl;
                if (1 + (rand () % 809) == 104) cout << "Nowe u hav a rel liv Cubone!!!!!" << endl;
                if (1 + (rand () % 809) == 105) cout << "Nowe u hav a rel liv Marowak!!!!!" << endl;
                if (1 + (rand () % 809) == 106) cout << "Nowe u hav a rel liv Hitmonlee!!!!!" << endl;
                if (1 + (rand () % 809) == 107) cout << "Nowe u hav a rel liv Hitmonchan!!!!!" << endl;
                if (1 + (rand () % 809) == 108) cout << "Nowe u hav a rel liv Lickitung!!!!!" << endl;
                if (1 + (rand () % 809) == 109) cout << "Nowe u hav a rel liv Koffing!!!!!" << endl;
                if (1 + (rand () % 809) == 110) cout << "Nowe u hav a rel liv Weezing!!!!!" << endl;
                if (1 + (rand () % 809) == 111) cout << "Nowe u hav a rel liv Rhyhorn!!!!!" << endl;
                if (1 + (rand () % 809) == 112) cout << "Nowe u hav a rel liv Rhydon!!!!!" << endl;
                if (1 + (rand () % 809) == 113) cout << "Nowe u hav a rel liv Chansey!!!!!" << endl;
                if (1 + (rand () % 809) == 114) cout << "Nowe u hav a rel liv Tangela!!!!!" << endl;
                if (1 + (rand () % 809) == 115) cout << "Nowe u hav a rel liv Kangaskhan!!!!!" << endl;
                if (1 + (rand () % 809) == 116) cout << "Nowe u hav a rel liv Horsea!!!!!" << endl;
                if (1 + (rand () % 809) == 117) cout << "Nowe u hav a rel liv Seadra!!!!!" << endl;
                if (1 + (rand () % 809) == 118) cout << "Nowe u hav a rel liv Goldeen!!!!!" << endl;
                if (1 + (rand () % 809) == 119) cout << "Nowe u hav a rel liv Seaking!!!!!" << endl;
                if (1 + (rand () % 809) == 120) cout << "Nowe u hav a rel liv Staryu!!!!!" << endl;
                if (1 + (rand () % 809) == 121) cout << "Nowe u hav a rel liv Starmie!!!!!" << endl;
                if (1 + (rand () % 809) == 122) cout << "Nowe u hav a rel liv Mr. Mime!!!!!" << endl;
                if (1 + (rand () % 809) == 123) cout << "Nowe u hav a rel liv Scyther!!!!!" << endl;
                if (1 + (rand () % 809) == 124) cout << "Nowe u hav a rel liv Jynx!!!!!" << endl;
                if (1 + (rand () % 809) == 125) cout << "Nowe u hav a rel liv Electabuzz!!!!!" << endl;
                if (1 + (rand () % 809) == 126) cout << "Nowe u hav a rel liv Magmar!!!!!" << endl;
                if (1 + (rand () % 809) == 127) cout << "Nowe u hav a rel liv Pinsir!!!!!" << endl;
                if (1 + (rand () % 809) == 128) cout << "Nowe u hav a rel liv Tauros!!!!!" << endl;
                if (1 + (rand () % 809) == 129) cout << "Nowe u hav a rel liv Magikarp!!!!!" << endl;
                if (1 + (rand () % 809) == 130) cout << "Nowe u hav a rel liv Gyarados!!!!!" << endl;
                if (1 + (rand () % 809) == 131) cout << "Nowe u hav a rel liv Lapras!!!!!" << endl;
                if (1 + (rand () % 809) == 132) cout << "Nowe u hav a rel liv Ditto!!!!!" << endl;
                if (1 + (rand () % 809) == 133) cout << "Nowe u hav a rel liv Eevee!!!!!" << endl;
                if (1 + (rand () % 809) == 134) cout << "Nowe u hav a rel liv Vaporeon!!!!!" << endl;
                if (1 + (rand () % 809) == 135) cout << "Nowe u hav a rel liv Jolteon!!!!!" << endl;
                if (1 + (rand () % 809) == 136) cout << "Nowe u hav a rel liv Flareon!!!!!" << endl;
                if (1 + (rand () % 809) == 137) cout << "Nowe u hav a rel liv Porygon!!!!!" << endl;
                if (1 + (rand () % 809) == 138) cout << "Nowe u hav a rel liv Omanyte!!!!!" << endl;
                if (1 + (rand () % 809) == 139) cout << "Nowe u hav a rel liv Omastar!!!!!" << endl;
                if (1 + (rand () % 809) == 140) cout << "Nowe u hav a rel liv Kabuto!!!!!" << endl;
                if (1 + (rand () % 809) == 141) cout << "Nowe u hav a rel liv Kabutops!!!!!" << endl;
                if (1 + (rand () % 809) == 142) cout << "Nowe u hav a rel liv Aerodactyl!!!!!" << endl;
                if (1 + (rand () % 809) == 143) cout << "Nowe u hav a rel liv Snorlax!!!!!" << endl;
                if (1 + (rand () % 809) == 144) cout << "Nowe u hav a rel liv Articuno!!!!!" << endl;
                if (1 + (rand () % 809) == 145) cout << "Nowe u hav a rel liv Zapdos!!!!!" << endl;
                if (1 + (rand () % 809) == 146) cout << "Nowe u hav a rel liv Moltres!!!!!" << endl;
                if (1 + (rand () % 809) == 147) cout << "Nowe u hav a rel liv Dratini!!!!!" << endl;
                if (1 + (rand () % 809) == 148) cout << "Nowe u hav a rel liv Dragonair!!!!!" << endl;
                if (1 + (rand () % 809) == 149) cout << "Nowe u hav a rel liv Dragonite!!!!!" << endl;
                if (1 + (rand () % 809) == 150) cout << "Nowe u hav a rel liv Mewtwo!!!!!" << endl;
                if (1 + (rand () % 809) == 151) cout << "Nowe u hav a rel liv Mew!!!!!" << endl;
                if (1 + (rand () % 809) == 152) cout << "Nowe u hav a rel liv Chikorita!!!!!" << endl;
                if (1 + (rand () % 809) == 153) cout << "Nowe u hav a rel liv Bayleef!!!!!" << endl;
                if (1 + (rand () % 809) == 154) cout << "Nowe u hav a rel liv Meganium!!!!!" << endl;
                if (1 + (rand () % 809) == 155) cout << "Nowe u hav a rel liv Cyndaquil!!!!!" << endl;
                if (1 + (rand () % 809) == 156) cout << "Nowe u hav a rel liv Quilava!!!!!" << endl;
                if (1 + (rand () % 809) == 157) cout << "Nowe u hav a rel liv Typhlosion!!!!!" << endl;
                if (1 + (rand () % 809) == 158) cout << "Nowe u hav a rel liv Totodile!!!!!" << endl;
                if (1 + (rand () % 809) == 159) cout << "Nowe u hav a rel liv Croconaw!!!!!" << endl;
                if (1 + (rand () % 809) == 160) cout << "Nowe u hav a rel liv Feraligatr!!!!!" << endl;
                if (1 + (rand () % 809) == 161) cout << "Nowe u hav a rel liv Sentret!!!!!" << endl;
                if (1 + (rand () % 809) == 162) cout << "Nowe u hav a rel liv Furret!!!!!" << endl;
                if (1 + (rand () % 809) == 163) cout << "Nowe u hav a rel liv Hoothoot!!!!!" << endl;
                if (1 + (rand () % 809) == 164) cout << "Nowe u hav a rel liv Noctowl!!!!!" << endl;
                if (1 + (rand () % 809) == 165) cout << "Nowe u hav a rel liv Ledyba!!!!!" << endl;
                if (1 + (rand () % 809) == 166) cout << "Nowe u hav a rel liv Ledian!!!!!" << endl;
                if (1 + (rand () % 809) == 167) cout << "Nowe u hav a rel liv Spinarak!!!!!" << endl;
                if (1 + (rand () % 809) == 168) cout << "Nowe u hav a rel liv Ariados!!!!!" << endl;
                if (1 + (rand () % 809) == 169) cout << "Nowe u hav a rel liv Crobat!!!!!" << endl;
                if (1 + (rand () % 809) == 170) cout << "Nowe u hav a rel liv Chinchou!!!!!" << endl;
                if (1 + (rand () % 809) == 171) cout << "Nowe u hav a rel liv Lanturn!!!!!" << endl;
                if (1 + (rand () % 809) == 172) cout << "Nowe u hav a rel liv Pichu!!!!!" << endl;
                if (1 + (rand () % 809) == 173) cout << "Nowe u hav a rel liv Cleffa!!!!!" << endl;
                if (1 + (rand () % 809) == 174) cout << "Nowe u hav a rel liv Igglybuff!!!!!" << endl;
                if (1 + (rand () % 809) == 175) cout << "Nowe u hav a rel liv Togepi!!!!!" << endl;
                if (1 + (rand () % 809) == 176) cout << "Nowe u hav a rel liv Togetic!!!!!" << endl;
                if (1 + (rand () % 809) == 177) cout << "Nowe u hav a rel liv Natu!!!!!" << endl;
                if (1 + (rand () % 809) == 178) cout << "Nowe u hav a rel liv Xatu!!!!!" << endl;
                if (1 + (rand () % 809) == 179) cout << "Nowe u hav a rel liv Mareep!!!!!" << endl;
                if (1 + (rand () % 809) == 180) cout << "Nowe u hav a rel liv Flaaffy!!!!!" << endl;
                if (1 + (rand () % 809) == 181) cout << "Nowe u hav a rel liv Ampharos!!!!!" << endl;
                if (1 + (rand () % 809) == 182) cout << "Nowe u hav a rel liv Bellossom!!!!!" << endl;
                if (1 + (rand () % 809) == 183) cout << "Nowe u hav a rel liv Marill!!!!!" << endl;
                if (1 + (rand () % 809) == 184) cout << "Nowe u hav a rel liv Azumarill!!!!!" << endl;
                if (1 + (rand () % 809) == 185) cout << "Nowe u hav a rel liv Sudowoodo!!!!!" << endl;
                if (1 + (rand () % 809) == 186) cout << "Nowe u hav a rel liv Politoed!!!!!" << endl;
                if (1 + (rand () % 809) == 187) cout << "Nowe u hav a rel liv Hoppip!!!!!" << endl;
                if (1 + (rand () % 809) == 188) cout << "Nowe u hav a rel liv Skiploom!!!!!" << endl;
                if (1 + (rand () % 809) == 189) cout << "Nowe u hav a rel liv Jumpluff!!!!!" << endl;
                if (1 + (rand () % 809) == 190) cout << "Nowe u hav a rel liv Aipom!!!!!" << endl;
                if (1 + (rand () % 809) == 191) cout << "Nowe u hav a rel liv Sunkern!!!!!" << endl;
                if (1 + (rand () % 809) == 192) cout << "Nowe u hav a rel liv Sunflora!!!!!" << endl;
                if (1 + (rand () % 809) == 193) cout << "Nowe u hav a rel liv Yanma!!!!!" << endl;
                if (1 + (rand () % 809) == 194) cout << "Nowe u hav a rel liv Wooper!!!!!" << endl;
                if (1 + (rand () % 809) == 195) cout << "Nowe u hav a rel liv Quagsire!!!!!" << endl;
                if (1 + (rand () % 809) == 196) cout << "Nowe u hav a rel liv Espeon!!!!!" << endl;
                if (1 + (rand () % 809) == 197) cout << "Nowe u hav a rel liv Umbreon!!!!!" << endl;
                if (1 + (rand () % 809) == 198) cout << "Nowe u hav a rel liv Murkrow!!!!!" << endl;
                if (1 + (rand () % 809) == 199) cout << "Nowe u hav a rel liv Slowking!!!!!" << endl;
                if (1 + (rand () % 809) == 200) cout << "Nowe u hav a rel liv Misdreavus!!!!!" << endl;
                if (1 + (rand () % 809) == 201) cout << "Nowe u hav a rel liv Unown!!!!!" << endl;
                if (1 + (rand () % 809) == 202) cout << "Nowe u hav a rel liv Wobbuffet!!!!!" << endl;
                if (1 + (rand () % 809) == 203) cout << "Nowe u hav a rel liv Girafarig!!!!!" << endl;
                if (1 + (rand () % 809) == 204) cout << "Nowe u hav a rel liv Pineco!!!!!" << endl;
                if (1 + (rand () % 809) == 205) cout << "Nowe u hav a rel liv Forretress!!!!!" << endl;
                if (1 + (rand () % 809) == 206) cout << "Nowe u hav a rel liv Dunsparce!!!!!" << endl;
                if (1 + (rand () % 809) == 207) cout << "Nowe u hav a rel liv Gligar!!!!!" << endl;
                if (1 + (rand () % 809) == 208) cout << "Nowe u hav a rel liv Steelix!!!!!" << endl;
                if (1 + (rand () % 809) == 209) cout << "Nowe u hav a rel liv Snubbull!!!!!" << endl;
                if (1 + (rand () % 809) == 210) cout << "Nowe u hav a rel liv Granbull!!!!!" << endl;
                if (1 + (rand () % 809) == 211) cout << "Nowe u hav a rel liv Qwilfish!!!!!" << endl;
                if (1 + (rand () % 809) == 212) cout << "Nowe u hav a rel liv Scizor!!!!!" << endl;
                if (1 + (rand () % 809) == 213) cout << "Nowe u hav a rel liv Shuckle!!!!!" << endl;
                if (1 + (rand () % 809) == 214) cout << "Nowe u hav a rel liv Heracross!!!!!" << endl;
                if (1 + (rand () % 809) == 215) cout << "Nowe u hav a rel liv Sneasel!!!!!" << endl;
                if (1 + (rand () % 809) == 216) cout << "Nowe u hav a rel liv Teddiursa!!!!!" << endl;
                if (1 + (rand () % 809) == 217) cout << "Nowe u hav a rel liv Ursaring!!!!!" << endl;
                if (1 + (rand () % 809) == 218) cout << "Nowe u hav a rel liv Slugma!!!!!" << endl;
                if (1 + (rand () % 809) == 219) cout << "Nowe u hav a rel liv Magcargo!!!!!" << endl;
                if (1 + (rand () % 809) == 220) cout << "Nowe u hav a rel liv Swinub!!!!!" << endl;
                if (1 + (rand () % 809) == 221) cout << "Nowe u hav a rel liv Piloswine!!!!!" << endl;
                if (1 + (rand () % 809) == 222) cout << "Nowe u hav a rel liv Corsola!!!!!" << endl;
                if (1 + (rand () % 809) == 223) cout << "Nowe u hav a rel liv Remoraid!!!!!" << endl;
                if (1 + (rand () % 809) == 224) cout << "Nowe u hav a rel liv Octillery!!!!!" << endl;
                if (1 + (rand () % 809) == 225) cout << "Nowe u hav a rel liv Delibird!!!!!" << endl;
                if (1 + (rand () % 809) == 226) cout << "Nowe u hav a rel liv Mantine!!!!!" << endl;
                if (1 + (rand () % 809) == 227) cout << "Nowe u hav a rel liv Skarmory!!!!!" << endl;
                if (1 + (rand () % 809) == 228) cout << "Nowe u hav a rel liv Houndour!!!!!" << endl;
                if (1 + (rand () % 809) == 229) cout << "Nowe u hav a rel liv Houndoom!!!!!" << endl;
                if (1 + (rand () % 809) == 230) cout << "Nowe u hav a rel liv Kingdra!!!!!" << endl;
                if (1 + (rand () % 809) == 231) cout << "Nowe u hav a rel liv Phanpy!!!!!" << endl;
                if (1 + (rand () % 809) == 232) cout << "Nowe u hav a rel liv Donphan!!!!!" << endl;
                if (1 + (rand () % 809) == 233) cout << "Nowe u hav a rel liv Porygon2!!!!!" << endl;
                if (1 + (rand () % 809) == 234) cout << "Nowe u hav a rel liv Stantler!!!!!" << endl;
                if (1 + (rand () % 809) == 235) cout << "Nowe u hav a rel liv Smeargle!!!!!" << endl;
                if (1 + (rand () % 809) == 236) cout << "Nowe u hav a rel liv Tyrogue!!!!!" << endl;
                if (1 + (rand () % 809) == 237) cout << "Nowe u hav a rel liv Hitmontop!!!!!" << endl;
                if (1 + (rand () % 809) == 238) cout << "Nowe u hav a rel liv Smoochum!!!!!" << endl;
                if (1 + (rand () % 809) == 239) cout << "Nowe u hav a rel liv Elekid!!!!!" << endl;
                if (1 + (rand () % 809) == 240) cout << "Nowe u hav a rel liv Magby!!!!!" << endl;
                if (1 + (rand () % 809) == 241) cout << "Nowe u hav a rel liv Miltank!!!!!" << endl;
                if (1 + (rand () % 809) == 242) cout << "Nowe u hav a rel liv Blissey!!!!!" << endl;
                if (1 + (rand () % 809) == 243) cout << "Nowe u hav a rel liv Raikou!!!!!" << endl;
                if (1 + (rand () % 809) == 244) cout << "Nowe u hav a rel liv Entei!!!!!" << endl;
                if (1 + (rand () % 809) == 245) cout << "Nowe u hav a rel liv Suicune!!!!!" << endl;
                if (1 + (rand () % 809) == 246) cout << "Nowe u hav a rel liv Larvitar!!!!!" << endl;
                if (1 + (rand () % 809) == 247) cout << "Nowe u hav a rel liv Pupitar!!!!!" << endl;
                if (1 + (rand () % 809) == 248) cout << "Nowe u hav a rel liv Tyranitar!!!!!" << endl;
                if (1 + (rand () % 809) == 249) cout << "Nowe u hav a rel liv Lugia!!!!!" << endl;
                if (1 + (rand () % 809) == 250) cout << "Nowe u hav a rel liv Ho-Oh!!!!!" << endl;
                if (1 + (rand () % 809) == 251) cout << "Nowe u hav a rel liv Celebi!!!!!" << endl;
                if (1 + (rand () % 809) == 252) cout << "Nowe u hav a rel liv Treecko!!!!!" << endl;
                if (1 + (rand () % 809) == 253) cout << "Nowe u hav a rel liv Grovyle!!!!!" << endl;
                if (1 + (rand () % 809) == 254) cout << "Nowe u hav a rel liv Sceptile!!!!!" << endl;
                if (1 + (rand () % 809) == 255) cout << "Nowe u hav a rel liv Torchic!!!!!" << endl;
                if (1 + (rand () % 809) == 256) cout << "Nowe u hav a rel liv Combusken!!!!!" << endl;
                if (1 + (rand () % 809) == 257) cout << "Nowe u hav a rel liv Blaziken!!!!!" << endl;
                if (1 + (rand () % 809) == 258) cout << "Nowe u hav a rel liv Mudkip!!!!!" << endl;
                if (1 + (rand () % 809) == 259) cout << "Nowe u hav a rel liv Marshtomp!!!!!" << endl;
                if (1 + (rand () % 809) == 260) cout << "Nowe u hav a rel liv Swampert!!!!!" << endl;
                if (1 + (rand () % 809) == 261) cout << "Nowe u hav a rel liv Poochyena!!!!!" << endl;
                if (1 + (rand () % 809) == 262) cout << "Nowe u hav a rel liv Mightyena!!!!!" << endl;
                if (1 + (rand () % 809) == 263) cout << "Nowe u hav a rel liv Zigzagoon!!!!!" << endl;
                if (1 + (rand () % 809) == 264) cout << "Nowe u hav a rel liv Linoone!!!!!" << endl;
                if (1 + (rand () % 809) == 265) cout << "Nowe u hav a rel liv Wurmple!!!!!" << endl;
                if (1 + (rand () % 809) == 266) cout << "Nowe u hav a rel liv Silcoon!!!!!" << endl;
                if (1 + (rand () % 809) == 267) cout << "Nowe u hav a rel liv Beautifly!!!!!" << endl;
                if (1 + (rand () % 809) == 268) cout << "Nowe u hav a rel liv Cascoon!!!!!" << endl;
                if (1 + (rand () % 809) == 269) cout << "Nowe u hav a rel liv Dustox!!!!!" << endl;
                if (1 + (rand () % 809) == 270) cout << "Nowe u hav a rel liv Lotad!!!!!" << endl;
                if (1 + (rand () % 809) == 271) cout << "Nowe u hav a rel liv Lombre!!!!!" << endl;
                if (1 + (rand () % 809) == 272) cout << "Nowe u hav a rel liv Ludicolo!!!!!" << endl;
                if (1 + (rand () % 809) == 273) cout << "Nowe u hav a rel liv Seedot!!!!!" << endl;
                if (1 + (rand () % 809) == 274) cout << "Nowe u hav a rel liv Nuzleaf!!!!!" << endl;
                if (1 + (rand () % 809) == 275) cout << "Nowe u hav a rel liv Shiftry!!!!!" << endl;
                if (1 + (rand () % 809) == 276) cout << "Nowe u hav a rel liv Taillow!!!!!" << endl;
                if (1 + (rand () % 809) == 277) cout << "Nowe u hav a rel liv Swellow!!!!!" << endl;
                if (1 + (rand () % 809) == 278) cout << "Nowe u hav a rel liv Wingull!!!!!" << endl;
                if (1 + (rand () % 809) == 279) cout << "Nowe u hav a rel liv Pelipper!!!!!" << endl;
                if (1 + (rand () % 809) == 280) cout << "Nowe u hav a rel liv Ralts!!!!!" << endl;
                if (1 + (rand () % 809) == 281) cout << "Nowe u hav a rel liv Kirlia!!!!!" << endl;
                if (1 + (rand () % 809) == 282) cout << "Nowe u hav a rel liv Gardevoir!!!!!" << endl;
                if (1 + (rand () % 809) == 283) cout << "Nowe u hav a rel liv Surskit!!!!!" << endl;
                if (1 + (rand () % 809) == 284) cout << "Nowe u hav a rel liv Masquerain!!!!!" << endl;
                if (1 + (rand () % 809) == 285) cout << "Nowe u hav a rel liv Shroomish!!!!!" << endl;
                if (1 + (rand () % 809) == 286) cout << "Nowe u hav a rel liv Breloom!!!!!" << endl;
                if (1 + (rand () % 809) == 287) cout << "Nowe u hav a rel liv Slakoth!!!!!" << endl;
                if (1 + (rand () % 809) == 288) cout << "Nowe u hav a rel liv Vigoroth!!!!!" << endl;
                if (1 + (rand () % 809) == 289) cout << "Nowe u hav a rel liv Slaking!!!!!" << endl;
                if (1 + (rand () % 809) == 290) cout << "Nowe u hav a rel liv Nincada!!!!!" << endl;
                if (1 + (rand () % 809) == 291) cout << "Nowe u hav a rel liv Ninjask!!!!!" << endl;
                if (1 + (rand () % 809) == 292) cout << "Nowe u hav a rel liv Shedinja!!!!!" << endl;
                if (1 + (rand () % 809) == 293) cout << "Nowe u hav a rel liv Whismur!!!!!" << endl;
                if (1 + (rand () % 809) == 294) cout << "Nowe u hav a rel liv Loudred!!!!!" << endl;
                if (1 + (rand () % 809) == 295) cout << "Nowe u hav a rel liv Exploud!!!!!" << endl;
                if (1 + (rand () % 809) == 296) cout << "Nowe u hav a rel liv Makuhita!!!!!" << endl;
                if (1 + (rand () % 809) == 297) cout << "Nowe u hav a rel liv Hariyama!!!!!" << endl;
                if (1 + (rand () % 809) == 298) cout << "Nowe u hav a rel liv Azurill!!!!!" << endl;
                if (1 + (rand () % 809) == 299) cout << "Nowe u hav a rel liv Nosepass!!!!!" << endl;
                if (1 + (rand () % 809) == 300) cout << "Nowe u hav a rel liv Skitty!!!!!" << endl;
                if (1 + (rand () % 809) == 301) cout << "Nowe u hav a rel liv Delcatty!!!!!" << endl;
                if (1 + (rand () % 809) == 302) cout << "Nowe u hav a rel liv Sableye!!!!!" << endl;
                if (1 + (rand () % 809) == 303) cout << "Nowe u hav a rel liv Mawile!!!!!" << endl;
                if (1 + (rand () % 809) == 304) cout << "Nowe u hav a rel liv Aron!!!!!" << endl;
                if (1 + (rand () % 809) == 305) cout << "Nowe u hav a rel liv Lairon!!!!!" << endl;
                if (1 + (rand () % 809) == 306) cout << "Nowe u hav a rel liv Aggron!!!!!" << endl;
                if (1 + (rand () % 809) == 307) cout << "Nowe u hav a rel liv Meditite!!!!!" << endl;
                if (1 + (rand () % 809) == 308) cout << "Nowe u hav a rel liv Medicham!!!!!" << endl;
                if (1 + (rand () % 809) == 309) cout << "Nowe u hav a rel liv Electrike!!!!!" << endl;
                if (1 + (rand () % 809) == 310) cout << "Nowe u hav a rel liv Manectric!!!!!" << endl;
                if (1 + (rand () % 809) == 311) cout << "Nowe u hav a rel liv Plusle!!!!!" << endl;
                if (1 + (rand () % 809) == 312) cout << "Nowe u hav a rel liv Minun!!!!!" << endl;
                if (1 + (rand () % 809) == 313) cout << "Nowe u hav a rel liv Volbeat!!!!!" << endl;
                if (1 + (rand () % 809) == 314) cout << "Nowe u hav a rel liv Illumise!!!!!" << endl;
                if (1 + (rand () % 809) == 315) cout << "Nowe u hav a rel liv Roselia!!!!!" << endl;
                if (1 + (rand () % 809) == 316) cout << "Nowe u hav a rel liv Gulpin!!!!!" << endl;
                if (1 + (rand () % 809) == 317) cout << "Nowe u hav a rel liv Swalot!!!!!" << endl;
                if (1 + (rand () % 809) == 318) cout << "Nowe u hav a rel liv Carvanha!!!!!" << endl;
                if (1 + (rand () % 809) == 319) cout << "Nowe u hav a rel liv Sharpedo!!!!!" << endl;
                if (1 + (rand () % 809) == 320) cout << "Nowe u hav a rel liv Wailmer!!!!!" << endl;
                if (1 + (rand () % 809) == 321) cout << "Nowe u hav a rel liv Wailord!!!!!" << endl;
                if (1 + (rand () % 809) == 322) cout << "Nowe u hav a rel liv Numel!!!!!" << endl;
                if (1 + (rand () % 809) == 323) cout << "Nowe u hav a rel liv Camerupt!!!!!" << endl;
                if (1 + (rand () % 809) == 324) cout << "Nowe u hav a rel liv Torkoal!!!!!" << endl;
                if (1 + (rand () % 809) == 325) cout << "Nowe u hav a rel liv Spoink!!!!!" << endl;
                if (1 + (rand () % 809) == 326) cout << "Nowe u hav a rel liv Grumpig!!!!!" << endl;
                if (1 + (rand () % 809) == 327) cout << "Nowe u hav a rel liv Spinda!!!!!" << endl;
                if (1 + (rand () % 809) == 328) cout << "Nowe u hav a rel liv Trapinch!!!!!" << endl;
                if (1 + (rand () % 809) == 329) cout << "Nowe u hav a rel liv Vibrava!!!!!" << endl;
                if (1 + (rand () % 809) == 330) cout << "Nowe u hav a rel liv Flygon!!!!!" << endl;
                if (1 + (rand () % 809) == 331) cout << "Nowe u hav a rel liv Cacnea!!!!!" << endl;
                if (1 + (rand () % 809) == 332) cout << "Nowe u hav a rel liv Cacturne!!!!!" << endl;
                if (1 + (rand () % 809) == 333) cout << "Nowe u hav a rel liv Swablu!!!!!" << endl;
                if (1 + (rand () % 809) == 334) cout << "Nowe u hav a rel liv Altaria!!!!!" << endl;
                if (1 + (rand () % 809) == 335) cout << "Nowe u hav a rel liv Zangoose!!!!!" << endl;
                if (1 + (rand () % 809) == 336) cout << "Nowe u hav a rel liv Seviper!!!!!" << endl;
                if (1 + (rand () % 809) == 337) cout << "Nowe u hav a rel liv Lunatone!!!!!" << endl;
                if (1 + (rand () % 809) == 338) cout << "Nowe u hav a rel liv Solrock!!!!!" << endl;
                if (1 + (rand () % 809) == 339) cout << "Nowe u hav a rel liv Barboach!!!!!" << endl;
                if (1 + (rand () % 809) == 340) cout << "Nowe u hav a rel liv Whiscash!!!!!" << endl;
                if (1 + (rand () % 809) == 341) cout << "Nowe u hav a rel liv Corphish!!!!!" << endl;
                if (1 + (rand () % 809) == 342) cout << "Nowe u hav a rel liv Crawdaunt!!!!!" << endl;
                if (1 + (rand () % 809) == 343) cout << "Nowe u hav a rel liv Baltoy!!!!!" << endl;
                if (1 + (rand () % 809) == 344) cout << "Nowe u hav a rel liv Claydol!!!!!" << endl;
                if (1 + (rand () % 809) == 345) cout << "Nowe u hav a rel liv Lileep!!!!!" << endl;
                if (1 + (rand () % 809) == 346) cout << "Nowe u hav a rel liv Cradily!!!!!" << endl;
                if (1 + (rand () % 809) == 347) cout << "Nowe u hav a rel liv Anorith!!!!!" << endl;
                if (1 + (rand () % 809) == 348) cout << "Nowe u hav a rel liv Armaldo!!!!!" << endl;
                if (1 + (rand () % 809) == 349) cout << "Nowe u hav a rel liv Feebas!!!!!" << endl;
                if (1 + (rand () % 809) == 350) cout << "Nowe u hav a rel liv Milotic!!!!!" << endl;
                if (1 + (rand () % 809) == 351) cout << "Nowe u hav a rel liv Castform!!!!!" << endl;
                if (1 + (rand () % 809) == 352) cout << "Nowe u hav a rel liv Kecleon!!!!!" << endl;
                if (1 + (rand () % 809) == 353) cout << "Nowe u hav a rel liv Shuppet!!!!!" << endl;
                if (1 + (rand () % 809) == 354) cout << "Nowe u hav a rel liv Banette!!!!!" << endl;
                if (1 + (rand () % 809) == 355) cout << "Nowe u hav a rel liv Duskull!!!!!" << endl;
                if (1 + (rand () % 809) == 356) cout << "Nowe u hav a rel liv Dusclops!!!!!" << endl;
                if (1 + (rand () % 809) == 357) cout << "Nowe u hav a rel liv Tropius!!!!!" << endl;
                if (1 + (rand () % 809) == 358) cout << "Nowe u hav a rel liv Chimecho!!!!!" << endl;
                if (1 + (rand () % 809) == 359) cout << "Nowe u hav a rel liv Absol!!!!!" << endl;
                if (1 + (rand () % 809) == 360) cout << "Nowe u hav a rel liv Wynaut!!!!!" << endl;
                if (1 + (rand () % 809) == 361) cout << "Nowe u hav a rel liv Snorunt!!!!!" << endl;
                if (1 + (rand () % 809) == 362) cout << "Nowe u hav a rel liv Glalie!!!!!" << endl;
                if (1 + (rand () % 809) == 363) cout << "Nowe u hav a rel liv Spheal!!!!!" << endl;
                if (1 + (rand () % 809) == 364) cout << "Nowe u hav a rel liv Sealeo!!!!!" << endl;
                if (1 + (rand () % 809) == 365) cout << "Nowe u hav a rel liv Walrein!!!!!" << endl;
                if (1 + (rand () % 809) == 366) cout << "Nowe u hav a rel liv Clamperl!!!!!" << endl;
                if (1 + (rand () % 809) == 367) cout << "Nowe u hav a rel liv Huntail!!!!!" << endl;
                if (1 + (rand () % 809) == 368) cout << "Nowe u hav a rel liv Gorebyss!!!!!" << endl;
                if (1 + (rand () % 809) == 369) cout << "Nowe u hav a rel liv Relicanth!!!!!" << endl;
                if (1 + (rand () % 809) == 370) cout << "Nowe u hav a rel liv Luvdisc!!!!!" << endl;
                if (1 + (rand () % 809) == 371) cout << "Nowe u hav a rel liv Bagon!!!!!" << endl;
                if (1 + (rand () % 809) == 372) cout << "Nowe u hav a rel liv Shelgon!!!!!" << endl;
                if (1 + (rand () % 809) == 373) cout << "Nowe u hav a rel liv Salamence!!!!!" << endl;
                if (1 + (rand () % 809) == 374) cout << "Nowe u hav a rel liv Beldum!!!!!" << endl;
                if (1 + (rand () % 809) == 375) cout << "Nowe u hav a rel liv Metang!!!!!" << endl;
                if (1 + (rand () % 809) == 376) cout << "Nowe u hav a rel liv Metagross!!!!!" << endl;
                if (1 + (rand () % 809) == 377) cout << "Nowe u hav a rel liv Regirock!!!!!" << endl;
                if (1 + (rand () % 809) == 378) cout << "Nowe u hav a rel liv Regice!!!!!" << endl;
                if (1 + (rand () % 809) == 379) cout << "Nowe u hav a rel liv Registeel!!!!!" << endl;
                if (1 + (rand () % 809) == 380) cout << "Nowe u hav a rel liv Latias!!!!!" << endl;
                if (1 + (rand () % 809) == 381) cout << "Nowe u hav a rel liv Latios!!!!!" << endl;
                if (1 + (rand () % 809) == 382) cout << "Nowe u hav a rel liv Kyogre!!!!!" << endl;
                if (1 + (rand () % 809) == 383) cout << "Nowe u hav a rel liv Groudon!!!!!" << endl;
                if (1 + (rand () % 809) == 384) cout << "Nowe u hav a rel liv Rayquaza!!!!!" << endl;
                if (1 + (rand () % 809) == 385) cout << "Nowe u hav a rel liv Jirachi!!!!!" << endl;
                if (1 + (rand () % 809) == 386) cout << "Nowe u hav a rel liv Deoxys!!!!!" << endl;
                if (1 + (rand () % 809) == 387) cout << "Nowe u hav a rel liv Turtwig!!!!!" << endl;
                if (1 + (rand () % 809) == 388) cout << "Nowe u hav a rel liv Grotle!!!!!" << endl;
                if (1 + (rand () % 809) == 389) cout << "Nowe u hav a rel liv Torterra!!!!!" << endl;
                if (1 + (rand () % 809) == 390) cout << "Nowe u hav a rel liv Chimchar!!!!!" << endl;
                if (1 + (rand () % 809) == 391) cout << "Nowe u hav a rel liv Monferno!!!!!" << endl;
                if (1 + (rand () % 809) == 392) cout << "Nowe u hav a rel liv Infernape!!!!!" << endl;
                if (1 + (rand () % 809) == 393) cout << "Nowe u hav a rel liv Piplup!!!!!" << endl;
                if (1 + (rand () % 809) == 394) cout << "Nowe u hav a rel liv Prinplup!!!!!" << endl;
                if (1 + (rand () % 809) == 395) cout << "Nowe u hav a rel liv Empoleon!!!!!" << endl;
                if (1 + (rand () % 809) == 396) cout << "Nowe u hav a rel liv Starly!!!!!" << endl;
                if (1 + (rand () % 809) == 397) cout << "Nowe u hav a rel liv Staravia!!!!!" << endl;
                if (1 + (rand () % 809) == 398) cout << "Nowe u hav a rel liv Staraptor!!!!!" << endl;
                if (1 + (rand () % 809) == 399) cout << "Nowe u hav a rel liv Bidoof!!!!!" << endl;
                if (1 + (rand () % 809) == 400) cout << "Nowe u hav a rel liv Bibarel!!!!!" << endl;
                if (1 + (rand () % 809) == 401) cout << "Nowe u hav a rel liv Kricketot!!!!!" << endl;
                if (1 + (rand () % 809) == 402) cout << "Nowe u hav a rel liv Kricketune!!!!!" << endl;
                if (1 + (rand () % 809) == 403) cout << "Nowe u hav a rel liv Shinx!!!!!" << endl;
                if (1 + (rand () % 809) == 404) cout << "Nowe u hav a rel liv Luxio!!!!!" << endl;
                if (1 + (rand () % 809) == 405) cout << "Nowe u hav a rel liv Luxray!!!!!" << endl;
                if (1 + (rand () % 809) == 406) cout << "Nowe u hav a rel liv Budew!!!!!" << endl;
                if (1 + (rand () % 809) == 407) cout << "Nowe u hav a rel liv Roserade!!!!!" << endl;
                if (1 + (rand () % 809) == 408) cout << "Nowe u hav a rel liv Cranidos!!!!!" << endl;
                if (1 + (rand () % 809) == 409) cout << "Nowe u hav a rel liv Rampardos!!!!!" << endl;
                if (1 + (rand () % 809) == 410) cout << "Nowe u hav a rel liv Shieldon!!!!!" << endl;
                if (1 + (rand () % 809) == 411) cout << "Nowe u hav a rel liv Bastiodon!!!!!" << endl;
                if (1 + (rand () % 809) == 412) cout << "Nowe u hav a rel liv Burmy!!!!!" << endl;
                if (1 + (rand () % 809) == 413) cout << "Nowe u hav a rel liv Wormadam!!!!!" << endl;
                if (1 + (rand () % 809) == 414) cout << "Nowe u hav a rel liv Mothim!!!!!" << endl;
                if (1 + (rand () % 809) == 415) cout << "Nowe u hav a rel liv Combee!!!!!" << endl;
                if (1 + (rand () % 809) == 416) cout << "Nowe u hav a rel liv Vespiquen!!!!!" << endl;
                if (1 + (rand () % 809) == 417) cout << "Nowe u hav a rel liv Pachirisu!!!!!" << endl;
                if (1 + (rand () % 809) == 418) cout << "Nowe u hav a rel liv Buizel!!!!!" << endl;
                if (1 + (rand () % 809) == 419) cout << "Nowe u hav a rel liv Floatzel!!!!!" << endl;
                if (1 + (rand () % 809) == 420) cout << "Nowe u hav a rel liv Cherubi!!!!!" << endl;
                if (1 + (rand () % 809) == 421) cout << "Nowe u hav a rel liv Cherrim!!!!!" << endl;
                if (1 + (rand () % 809) == 422) cout << "Nowe u hav a rel liv Shellos!!!!!" << endl;
                if (1 + (rand () % 809) == 423) cout << "Nowe u hav a rel liv Gastrodon!!!!!" << endl;
                if (1 + (rand () % 809) == 424) cout << "Nowe u hav a rel liv Ambipom!!!!!" << endl;
                if (1 + (rand () % 809) == 425) cout << "Nowe u hav a rel liv Drifloon!!!!!" << endl;
                if (1 + (rand () % 809) == 426) cout << "Nowe u hav a rel liv Drifblim!!!!!" << endl;
                if (1 + (rand () % 809) == 427) cout << "Nowe u hav a rel liv Buneary!!!!!" << endl;
                if (1 + (rand () % 809) == 428) cout << "Nowe u hav a rel liv Lopunny!!!!!" << endl;
                if (1 + (rand () % 809) == 429) cout << "Nowe u hav a rel liv Mismagius!!!!!" << endl;
                if (1 + (rand () % 809) == 430) cout << "Nowe u hav a rel liv Honchkrow!!!!!" << endl;
                if (1 + (rand () % 809) == 431) cout << "Nowe u hav a rel liv Glameow!!!!!" << endl;
                if (1 + (rand () % 809) == 432) cout << "Nowe u hav a rel liv Purugly!!!!!" << endl;
                if (1 + (rand () % 809) == 433) cout << "Nowe u hav a rel liv Chingling!!!!!" << endl;
                if (1 + (rand () % 809) == 434) cout << "Nowe u hav a rel liv Stunky!!!!!" << endl;
                if (1 + (rand () % 809) == 435) cout << "Nowe u hav a rel liv Skuntank!!!!!" << endl;
                if (1 + (rand () % 809) == 436) cout << "Nowe u hav a rel liv Bronzor!!!!!" << endl;
                if (1 + (rand () % 809) == 437) cout << "Nowe u hav a rel liv Bronzong!!!!!" << endl;
                if (1 + (rand () % 809) == 438) cout << "Nowe u hav a rel liv Bonsly!!!!!" << endl;
                if (1 + (rand () % 809) == 439) cout << "Nowe u hav a rel liv Mime Jr.!!!!!" << endl;
                if (1 + (rand () % 809) == 440) cout << "Nowe u hav a rel liv Happiny!!!!!" << endl;
                if (1 + (rand () % 809) == 441) cout << "Nowe u hav a rel liv Chatot!!!!!" << endl;
                if (1 + (rand () % 809) == 442) cout << "Nowe u hav a rel liv Spiritomb!!!!!" << endl;
                if (1 + (rand () % 809) == 443) cout << "Nowe u hav a rel liv Gible!!!!!" << endl;
                if (1 + (rand () % 809) == 444) cout << "Nowe u hav a rel liv Gabite!!!!!" << endl;
                if (1 + (rand () % 809) == 445) cout << "Nowe u hav a rel liv Garchomp!!!!!" << endl;
                if (1 + (rand () % 809) == 446) cout << "Nowe u hav a rel liv Munchlax!!!!!" << endl;
                if (1 + (rand () % 809) == 447) cout << "Nowe u hav a rel liv Riolu!!!!!" << endl;
                if (1 + (rand () % 809) == 448) cout << "Nowe u hav a rel liv Lucario!!!!!" << endl;
                if (1 + (rand () % 809) == 449) cout << "Nowe u hav a rel liv Hippopotas!!!!!" << endl;
                if (1 + (rand () % 809) == 450) cout << "Nowe u hav a rel liv Hippowdon!!!!!" << endl;
                if (1 + (rand () % 809) == 451) cout << "Nowe u hav a rel liv Skorupi!!!!!" << endl;
                if (1 + (rand () % 809) == 452) cout << "Nowe u hav a rel liv Drapion!!!!!" << endl;
                if (1 + (rand () % 809) == 453) cout << "Nowe u hav a rel liv Croagunk!!!!!" << endl;
                if (1 + (rand () % 809) == 454) cout << "Nowe u hav a rel liv Toxicroak!!!!!" << endl;
                if (1 + (rand () % 809) == 455) cout << "Nowe u hav a rel liv Carnivine!!!!!" << endl;
                if (1 + (rand () % 809) == 456) cout << "Nowe u hav a rel liv Finneon!!!!!" << endl;
                if (1 + (rand () % 809) == 457) cout << "Nowe u hav a rel liv Lumineon!!!!!" << endl;
                if (1 + (rand () % 809) == 458) cout << "Nowe u hav a rel liv Mantyke!!!!!" << endl;
                if (1 + (rand () % 809) == 459) cout << "Nowe u hav a rel liv Snover!!!!!" << endl;
                if (1 + (rand () % 809) == 460) cout << "Nowe u hav a rel liv Abomasnow!!!!!" << endl;
                if (1 + (rand () % 809) == 461) cout << "Nowe u hav a rel liv Weavile!!!!!" << endl;
                if (1 + (rand () % 809) == 462) cout << "Nowe u hav a rel liv Magnezone!!!!!" << endl;
                if (1 + (rand () % 809) == 463) cout << "Nowe u hav a rel liv Lickilicky!!!!!" << endl;
                if (1 + (rand () % 809) == 464) cout << "Nowe u hav a rel liv Rhyperior!!!!!" << endl;
                if (1 + (rand () % 809) == 465) cout << "Nowe u hav a rel liv Tangrowth!!!!!" << endl;
                if (1 + (rand () % 809) == 466) cout << "Nowe u hav a rel liv Electivire!!!!!" << endl;
                if (1 + (rand () % 809) == 467) cout << "Nowe u hav a rel liv Magmortar!!!!!" << endl;
                if (1 + (rand () % 809) == 468) cout << "Nowe u hav a rel liv Togekiss!!!!!" << endl;
                if (1 + (rand () % 809) == 469) cout << "Nowe u hav a rel liv Yanmega!!!!!" << endl;
                if (1 + (rand () % 809) == 470) cout << "Nowe u hav a rel liv Leafeon!!!!!" << endl;
                if (1 + (rand () % 809) == 471) cout << "Nowe u hav a rel liv Glaceon!!!!!" << endl;
                if (1 + (rand () % 809) == 472) cout << "Nowe u hav a rel liv Gliscor!!!!!" << endl;
                if (1 + (rand () % 809) == 473) cout << "Nowe u hav a rel liv Mamoswine!!!!!" << endl;
                if (1 + (rand () % 809) == 474) cout << "Nowe u hav a rel liv Porygon-Z!!!!!" << endl;
                if (1 + (rand () % 809) == 475) cout << "Nowe u hav a rel liv Gallade!!!!!" << endl;
                if (1 + (rand () % 809) == 476) cout << "Nowe u hav a rel liv Probopass!!!!!" << endl;
                if (1 + (rand () % 809) == 477) cout << "Nowe u hav a rel liv Dusknoir!!!!!" << endl;
                if (1 + (rand () % 809) == 478) cout << "Nowe u hav a rel liv Froslass!!!!!" << endl;
                if (1 + (rand () % 809) == 479) cout << "Nowe u hav a rel liv Rotom!!!!!" << endl;
                if (1 + (rand () % 809) == 480) cout << "Nowe u hav a rel liv Uxie!!!!!" << endl;
                if (1 + (rand () % 809) == 481) cout << "Nowe u hav a rel liv Mesprit!!!!!" << endl;
                if (1 + (rand () % 809) == 482) cout << "Nowe u hav a rel liv Azelf!!!!!" << endl;
                if (1 + (rand () % 809) == 483) cout << "Nowe u hav a rel liv Dialga!!!!!" << endl;
                if (1 + (rand () % 809) == 484) cout << "Nowe u hav a rel liv Palkia!!!!!" << endl;
                if (1 + (rand () % 809) == 485) cout << "Nowe u hav a rel liv Heatran!!!!!" << endl;
                if (1 + (rand () % 809) == 486) cout << "Nowe u hav a rel liv Regigigas!!!!!" << endl;
                if (1 + (rand () % 809) == 487) cout << "Nowe u hav a rel liv Giratina!!!!!" << endl;
                if (1 + (rand () % 809) == 488) cout << "Nowe u hav a rel liv Cresselia!!!!!" << endl;
                if (1 + (rand () % 809) == 489) cout << "Nowe u hav a rel liv Phione!!!!!" << endl;
                if (1 + (rand () % 809) == 490) cout << "Nowe u hav a rel liv Manaphy!!!!!" << endl;
                if (1 + (rand () % 809) == 491) cout << "Nowe u hav a rel liv Darkrai!!!!!" << endl;
                if (1 + (rand () % 809) == 492) cout << "Nowe u hav a rel liv Shaymin!!!!!" << endl;
                if (1 + (rand () % 809) == 493) cout << "Nowe u hav a rel liv Arceus!!!!!" << endl;
                if (1 + (rand () % 809) == 494) cout << "Nowe u hav a rel liv Victini!!!!!" << endl;
                if (1 + (rand () % 809) == 495) cout << "Nowe u hav a rel liv Snivy!!!!!" << endl;
                if (1 + (rand () % 809) == 496) cout << "Nowe u hav a rel liv Servine!!!!!" << endl;
                if (1 + (rand () % 809) == 497) cout << "Nowe u hav a rel liv Serperior!!!!!" << endl;
                if (1 + (rand () % 809) == 498) cout << "Nowe u hav a rel liv Tepig!!!!!" << endl;
                if (1 + (rand () % 809) == 499) cout << "Nowe u hav a rel liv Pignite!!!!!" << endl;
                if (1 + (rand () % 809) == 500) cout << "Nowe u hav a rel liv Emboar!!!!!" << endl;
                if (1 + (rand () % 809) == 501) cout << "Nowe u hav a rel liv Oshawott!!!!!" << endl;
                if (1 + (rand () % 809) == 502) cout << "Nowe u hav a rel liv Dewott!!!!!" << endl;
                if (1 + (rand () % 809) == 503) cout << "Nowe u hav a rel liv Samurott!!!!!" << endl;
                if (1 + (rand () % 809) == 504) cout << "Nowe u hav a rel liv Patrat!!!!!" << endl;
                if (1 + (rand () % 809) == 505) cout << "Nowe u hav a rel liv Watchog!!!!!" << endl;
                if (1 + (rand () % 809) == 506) cout << "Nowe u hav a rel liv Lillipup!!!!!" << endl;
                if (1 + (rand () % 809) == 507) cout << "Nowe u hav a rel liv Herdier!!!!!" << endl;
                if (1 + (rand () % 809) == 508) cout << "Nowe u hav a rel liv Stoutland!!!!!" << endl;
                if (1 + (rand () % 809) == 509) cout << "Nowe u hav a rel liv Purrloin!!!!!" << endl;
                if (1 + (rand () % 809) == 510) cout << "Nowe u hav a rel liv Liepard!!!!!" << endl;
                if (1 + (rand () % 809) == 511) cout << "Nowe u hav a rel liv Pansage!!!!!" << endl;
                if (1 + (rand () % 809) == 512) cout << "Nowe u hav a rel liv Simisage!!!!!" << endl;
                if (1 + (rand () % 809) == 513) cout << "Nowe u hav a rel liv Pansear!!!!!" << endl;
                if (1 + (rand () % 809) == 514) cout << "Nowe u hav a rel liv Simisear!!!!!" << endl;
                if (1 + (rand () % 809) == 515) cout << "Nowe u hav a rel liv Panpour!!!!!" << endl;
                if (1 + (rand () % 809) == 516) cout << "Nowe u hav a rel liv Simipour!!!!!" << endl;
                if (1 + (rand () % 809) == 517) cout << "Nowe u hav a rel liv Munna!!!!!" << endl;
                if (1 + (rand () % 809) == 518) cout << "Nowe u hav a rel liv Musharna!!!!!" << endl;
                if (1 + (rand () % 809) == 519) cout << "Nowe u hav a rel liv Pidove!!!!!" << endl;
                if (1 + (rand () % 809) == 520) cout << "Nowe u hav a rel liv Tranquill!!!!!" << endl;
                if (1 + (rand () % 809) == 521) cout << "Nowe u hav a rel liv Unfezant!!!!!" << endl;
                if (1 + (rand () % 809) == 522) cout << "Nowe u hav a rel liv Blitzle!!!!!" << endl;
                if (1 + (rand () % 809) == 523) cout << "Nowe u hav a rel liv Zebstrika!!!!!" << endl;
                if (1 + (rand () % 809) == 524) cout << "Nowe u hav a rel liv Roggenrola!!!!!" << endl;
                if (1 + (rand () % 809) == 525) cout << "Nowe u hav a rel liv Boldore!!!!!" << endl;
                if (1 + (rand () % 809) == 526) cout << "Nowe u hav a rel liv Gigalith!!!!!" << endl;
                if (1 + (rand () % 809) == 527) cout << "Nowe u hav a rel liv Woobat!!!!!" << endl;
                if (1 + (rand () % 809) == 528) cout << "Nowe u hav a rel liv Swoobat!!!!!" << endl;
                if (1 + (rand () % 809) == 529) cout << "Nowe u hav a rel liv Drilbur!!!!!" << endl;
                if (1 + (rand () % 809) == 530) cout << "Nowe u hav a rel liv Excadrill!!!!!" << endl;
                if (1 + (rand () % 809) == 531) cout << "Nowe u hav a rel liv Audino!!!!!" << endl;
                if (1 + (rand () % 809) == 532) cout << "Nowe u hav a rel liv Timburr!!!!!" << endl;
                if (1 + (rand () % 809) == 533) cout << "Nowe u hav a rel liv Gurdurr!!!!!" << endl;
                if (1 + (rand () % 809) == 534) cout << "Nowe u hav a rel liv Conkeldurr!!!!!" << endl;
                if (1 + (rand () % 809) == 535) cout << "Nowe u hav a rel liv Tympole!!!!!" << endl;
                if (1 + (rand () % 809) == 536) cout << "Nowe u hav a rel liv Palpitoad!!!!!" << endl;
                if (1 + (rand () % 809) == 537) cout << "Nowe u hav a rel liv Seismitoad!!!!!" << endl;
                if (1 + (rand () % 809) == 538) cout << "Nowe u hav a rel liv Throh!!!!!" << endl;
                if (1 + (rand () % 809) == 539) cout << "Nowe u hav a rel liv Sawk!!!!!" << endl;
                if (1 + (rand () % 809) == 540) cout << "Nowe u hav a rel liv Sewaddle!!!!!" << endl;
                if (1 + (rand () % 809) == 541) cout << "Nowe u hav a rel liv Swadloon!!!!!" << endl;
                if (1 + (rand () % 809) == 542) cout << "Nowe u hav a rel liv Leavanny!!!!!" << endl;
                if (1 + (rand () % 809) == 543) cout << "Nowe u hav a rel liv Venipede!!!!!" << endl;
                if (1 + (rand () % 809) == 544) cout << "Nowe u hav a rel liv Whirlipede!!!!!" << endl;
                if (1 + (rand () % 809) == 545) cout << "Nowe u hav a rel liv Scolipede!!!!!" << endl;
                if (1 + (rand () % 809) == 546) cout << "Nowe u hav a rel liv Cottonee!!!!!" << endl;
                if (1 + (rand () % 809) == 547) cout << "Nowe u hav a rel liv Whimsicott!!!!!" << endl;
                if (1 + (rand () % 809) == 548) cout << "Nowe u hav a rel liv Petilil!!!!!" << endl;
                if (1 + (rand () % 809) == 549) cout << "Nowe u hav a rel liv Lilligant!!!!!" << endl;
                if (1 + (rand () % 809) == 550) cout << "Nowe u hav a rel liv Basculin!!!!!" << endl;
                if (1 + (rand () % 809) == 551) cout << "Nowe u hav a rel liv Sandile!!!!!" << endl;
                if (1 + (rand () % 809) == 552) cout << "Nowe u hav a rel liv Krokorok!!!!!" << endl;
                if (1 + (rand () % 809) == 553) cout << "Nowe u hav a rel liv Krookodile!!!!!" << endl;
                if (1 + (rand () % 809) == 554) cout << "Nowe u hav a rel liv Darumaka!!!!!" << endl;
                if (1 + (rand () % 809) == 555) cout << "Nowe u hav a rel liv Darmanitan!!!!!" << endl;
                if (1 + (rand () % 809) == 556) cout << "Nowe u hav a rel liv Maractus!!!!!" << endl;
                if (1 + (rand () % 809) == 557) cout << "Nowe u hav a rel liv Dwebble!!!!!" << endl;
                if (1 + (rand () % 809) == 558) cout << "Nowe u hav a rel liv Crustle!!!!!" << endl;
                if (1 + (rand () % 809) == 559) cout << "Nowe u hav a rel liv Scraggy!!!!!" << endl;
                if (1 + (rand () % 809) == 560) cout << "Nowe u hav a rel liv Scrafty!!!!!" << endl;
                if (1 + (rand () % 809) == 561) cout << "Nowe u hav a rel liv Sigilyph!!!!!" << endl;
                if (1 + (rand () % 809) == 562) cout << "Nowe u hav a rel liv Yamask!!!!!" << endl;
                if (1 + (rand () % 809) == 563) cout << "Nowe u hav a rel liv Cofagrigus!!!!!" << endl;
                if (1 + (rand () % 809) == 564) cout << "Nowe u hav a rel liv Tirtouga!!!!!" << endl;
                if (1 + (rand () % 809) == 565) cout << "Nowe u hav a rel liv Carracosta!!!!!" << endl;
                if (1 + (rand () % 809) == 566) cout << "Nowe u hav a rel liv Archen!!!!!" << endl;
                if (1 + (rand () % 809) == 567) cout << "Nowe u hav a rel liv Archeops!!!!!" << endl;
                if (1 + (rand () % 809) == 568) cout << "Nowe u hav a rel liv Trubbish!!!!!" << endl;
                if (1 + (rand () % 809) == 569) cout << "Nowe u hav a rel liv Garbodor!!!!!" << endl;
                if (1 + (rand () % 809) == 570) cout << "Nowe u hav a rel liv Zorua!!!!!" << endl;
                if (1 + (rand () % 809) == 571) cout << "Nowe u hav a rel liv Zoroark!!!!!" << endl;
                if (1 + (rand () % 809) == 572) cout << "Nowe u hav a rel liv Minccino!!!!!" << endl;
                if (1 + (rand () % 809) == 573) cout << "Nowe u hav a rel liv Cinccino!!!!!" << endl;
                if (1 + (rand () % 809) == 574) cout << "Nowe u hav a rel liv Gothita!!!!!" << endl;
                if (1 + (rand () % 809) == 575) cout << "Nowe u hav a rel liv Gothorita!!!!!" << endl;
                if (1 + (rand () % 809) == 576) cout << "Nowe u hav a rel liv Gothitelle!!!!!" << endl;
                if (1 + (rand () % 809) == 577) cout << "Nowe u hav a rel liv Solosis!!!!!" << endl;
                if (1 + (rand () % 809) == 578) cout << "Nowe u hav a rel liv Duosion!!!!!" << endl;
                if (1 + (rand () % 809) == 579) cout << "Nowe u hav a rel liv Reuniclus!!!!!" << endl;
                if (1 + (rand () % 809) == 580) cout << "Nowe u hav a rel liv Ducklett!!!!!" << endl;
                if (1 + (rand () % 809) == 581) cout << "Nowe u hav a rel liv Swanna!!!!!" << endl;
                if (1 + (rand () % 809) == 582) cout << "Nowe u hav a rel liv Vanillite!!!!!" << endl;
                if (1 + (rand () % 809) == 583) cout << "Nowe u hav a rel liv Vanillish!!!!!" << endl;
                if (1 + (rand () % 809) == 584) cout << "Nowe u hav a rel liv Vanilluxe!!!!!" << endl;
                if (1 + (rand () % 809) == 585) cout << "Nowe u hav a rel liv Deerling!!!!!" << endl;
                if (1 + (rand () % 809) == 586) cout << "Nowe u hav a rel liv Sawsbuck!!!!!" << endl;
                if (1 + (rand () % 809) == 587) cout << "Nowe u hav a rel liv Emolga!!!!!" << endl;
                if (1 + (rand () % 809) == 588) cout << "Nowe u hav a rel liv Karrablast!!!!!" << endl;
                if (1 + (rand () % 809) == 589) cout << "Nowe u hav a rel liv Escavalier!!!!!" << endl;
                if (1 + (rand () % 809) == 590) cout << "Nowe u hav a rel liv Foongus!!!!!" << endl;
                if (1 + (rand () % 809) == 591) cout << "Nowe u hav a rel liv Amoonguss!!!!!" << endl;
                if (1 + (rand () % 809) == 592) cout << "Nowe u hav a rel liv Frillish!!!!!" << endl;
                if (1 + (rand () % 809) == 593) cout << "Nowe u hav a rel liv Jellicent!!!!!" << endl;
                if (1 + (rand () % 809) == 594) cout << "Nowe u hav a rel liv Alomomola!!!!!" << endl;
                if (1 + (rand () % 809) == 595) cout << "Nowe u hav a rel liv Joltik!!!!!" << endl;
                if (1 + (rand () % 809) == 596) cout << "Nowe u hav a rel liv Galvantula!!!!!" << endl;
                if (1 + (rand () % 809) == 597) cout << "Nowe u hav a rel liv Ferroseed!!!!!" << endl;
                if (1 + (rand () % 809) == 598) cout << "Nowe u hav a rel liv Ferrothorn!!!!!" << endl;
                if (1 + (rand () % 809) == 599) cout << "Nowe u hav a rel liv Klink!!!!!" << endl;
                if (1 + (rand () % 809) == 600) cout << "Nowe u hav a rel liv Klang!!!!!" << endl;
                if (1 + (rand () % 809) == 601) cout << "Nowe u hav a rel liv Klinklang!!!!!" << endl;
                if (1 + (rand () % 809) == 602) cout << "Nowe u hav a rel liv Tynamo!!!!!" << endl;
                if (1 + (rand () % 809) == 603) cout << "Nowe u hav a rel liv Eelektrik!!!!!" << endl;
                if (1 + (rand () % 809) == 604) cout << "Nowe u hav a rel liv Eelektross!!!!!" << endl;
                if (1 + (rand () % 809) == 605) cout << "Nowe u hav a rel liv Elgyem!!!!!" << endl;
                if (1 + (rand () % 809) == 606) cout << "Nowe u hav a rel liv Beheeyem!!!!!" << endl;
                if (1 + (rand () % 809) == 607) cout << "Nowe u hav a rel liv Litwick!!!!!" << endl;
                if (1 + (rand () % 809) == 608) cout << "Nowe u hav a rel liv Lampent!!!!!" << endl;
                if (1 + (rand () % 809) == 609) cout << "Nowe u hav a rel liv Chandelure!!!!!" << endl;
                if (1 + (rand () % 809) == 610) cout << "Nowe u hav a rel liv Axew!!!!!" << endl;
                if (1 + (rand () % 809) == 611) cout << "Nowe u hav a rel liv Fraxure!!!!!" << endl;
                if (1 + (rand () % 809) == 612) cout << "Nowe u hav a rel liv Haxorus!!!!!" << endl;
                if (1 + (rand () % 809) == 613) cout << "Nowe u hav a rel liv Cubchoo!!!!!" << endl;
                if (1 + (rand () % 809) == 614) cout << "Nowe u hav a rel liv Beartic!!!!!" << endl;
                if (1 + (rand () % 809) == 615) cout << "Nowe u hav a rel liv Cryogonal!!!!!" << endl;
                if (1 + (rand () % 809) == 616) cout << "Nowe u hav a rel liv Shelmet!!!!!" << endl;
                if (1 + (rand () % 809) == 617) cout << "Nowe u hav a rel liv Accelgor!!!!!" << endl;
                if (1 + (rand () % 809) == 618) cout << "Nowe u hav a rel liv Stunfisk!!!!!" << endl;
                if (1 + (rand () % 809) == 619) cout << "Nowe u hav a rel liv Mienfoo!!!!!" << endl;
                if (1 + (rand () % 809) == 620) cout << "Nowe u hav a rel liv Mienshao!!!!!" << endl;
                if (1 + (rand () % 809) == 621) cout << "Nowe u hav a rel liv Druddigon!!!!!" << endl;
                if (1 + (rand () % 809) == 622) cout << "Nowe u hav a rel liv Golett!!!!!" << endl;
                if (1 + (rand () % 809) == 623) cout << "Nowe u hav a rel liv Golurk!!!!!" << endl;
                if (1 + (rand () % 809) == 624) cout << "Nowe u hav a rel liv Pawniard!!!!!" << endl;
                if (1 + (rand () % 809) == 625) cout << "Nowe u hav a rel liv Bisharp!!!!!" << endl;
                if (1 + (rand () % 809) == 626) cout << "Nowe u hav a rel liv Bouffalant!!!!!" << endl;
                if (1 + (rand () % 809) == 627) cout << "Nowe u hav a rel liv Rufflet!!!!!" << endl;
                if (1 + (rand () % 809) == 628) cout << "Nowe u hav a rel liv Braviary!!!!!" << endl;
                if (1 + (rand () % 809) == 629) cout << "Nowe u hav a rel liv Vullaby!!!!!" << endl;
                if (1 + (rand () % 809) == 630) cout << "Nowe u hav a rel liv Mandibuzz!!!!!" << endl;
                if (1 + (rand () % 809) == 631) cout << "Nowe u hav a rel liv Heatmor!!!!!" << endl;
                if (1 + (rand () % 809) == 632) cout << "Nowe u hav a rel liv Durant!!!!!" << endl;
                if (1 + (rand () % 809) == 633) cout << "Nowe u hav a rel liv Deino!!!!!" << endl;
                if (1 + (rand () % 809) == 634) cout << "Nowe u hav a rel liv Zweilous!!!!!" << endl;
                if (1 + (rand () % 809) == 635) cout << "Nowe u hav a rel liv Hydreigon!!!!!" << endl;
                if (1 + (rand () % 809) == 636) cout << "Nowe u hav a rel liv Larvesta!!!!!" << endl;
                if (1 + (rand () % 809) == 637) cout << "Nowe u hav a rel liv Volcarona!!!!!" << endl;
                if (1 + (rand () % 809) == 638) cout << "Nowe u hav a rel liv Cobalion!!!!!" << endl;
                if (1 + (rand () % 809) == 639) cout << "Nowe u hav a rel liv Terrakion!!!!!" << endl;
                if (1 + (rand () % 809) == 640) cout << "Nowe u hav a rel liv Virizion!!!!!" << endl;
                if (1 + (rand () % 809) == 641) cout << "Nowe u hav a rel liv Tornadus!!!!!" << endl;
                if (1 + (rand () % 809) == 642) cout << "Nowe u hav a rel liv Thundurus!!!!!" << endl;
                if (1 + (rand () % 809) == 643) cout << "Nowe u hav a rel liv Reshiram!!!!!" << endl;
                if (1 + (rand () % 809) == 644) cout << "Nowe u hav a rel liv Zekrom!!!!!" << endl;
                if (1 + (rand () % 809) == 645) cout << "Nowe u hav a rel liv Landorus!!!!!" << endl;
                if (1 + (rand () % 809) == 646) cout << "Nowe u hav a rel liv Kyurem!!!!!" << endl;
                if (1 + (rand () % 809) == 647) cout << "Nowe u hav a rel liv Keldeo!!!!!" << endl;
                if (1 + (rand () % 809) == 648) cout << "Nowe u hav a rel liv Meloetta!!!!!" << endl;
                if (1 + (rand () % 809) == 649) cout << "Nowe u hav a rel liv Genesect!!!!!" << endl;
                if (1 + (rand () % 809) == 650) cout << "Nowe u hav a rel liv Chespin!!!!!" << endl;
                if (1 + (rand () % 809) == 651) cout << "Nowe u hav a rel liv Quilladin!!!!!" << endl;
                if (1 + (rand () % 809) == 652) cout << "Nowe u hav a rel liv Chesnaught!!!!!" << endl;
                if (1 + (rand () % 809) == 653) cout << "Nowe u hav a rel liv Fennekin!!!!!" << endl;
                if (1 + (rand () % 809) == 654) cout << "Nowe u hav a rel liv Braixen!!!!!" << endl;
                if (1 + (rand () % 809) == 655) cout << "Nowe u hav a rel liv Delphox!!!!!" << endl;
                if (1 + (rand () % 809) == 656) cout << "Nowe u hav a rel liv Froakie!!!!!" << endl;
                if (1 + (rand () % 809) == 657) cout << "Nowe u hav a rel liv Frogadier!!!!!" << endl;
                if (1 + (rand () % 809) == 658) cout << "Nowe u hav a rel liv Greninja!!!!!" << endl;
                if (1 + (rand () % 809) == 659) cout << "Nowe u hav a rel liv Bunnelby!!!!!" << endl;
                if (1 + (rand () % 809) == 660) cout << "Nowe u hav a rel liv Diggersby!!!!!" << endl;
                if (1 + (rand () % 809) == 661) cout << "Nowe u hav a rel liv Fletchling!!!!!" << endl;
                if (1 + (rand () % 809) == 662) cout << "Nowe u hav a rel liv Fletchinder!!!!!" << endl;
                if (1 + (rand () % 809) == 663) cout << "Nowe u hav a rel liv Talonflame!!!!!" << endl;
                if (1 + (rand () % 809) == 664) cout << "Nowe u hav a rel liv Scatterbug!!!!!" << endl;
                if (1 + (rand () % 809) == 665) cout << "Nowe u hav a rel liv Spewpa!!!!!" << endl;
                if (1 + (rand () % 809) == 666) cout << "Nowe u hav a rel liv Vivillon!!!!!" << endl;
                if (1 + (rand () % 809) == 667) cout << "Nowe u hav a rel liv Litleo!!!!!" << endl;
                if (1 + (rand () % 809) == 668) cout << "Nowe u hav a rel liv Pyroar!!!!!" << endl;
                if (1 + (rand () % 809) == 669) cout << "Nowe u hav a rel liv Flabébé!!!!!" << endl;
                if (1 + (rand () % 809) == 670) cout << "Nowe u hav a rel liv Floette!!!!!" << endl;
                if (1 + (rand () % 809) == 671) cout << "Nowe u hav a rel liv Florges!!!!!" << endl;
                if (1 + (rand () % 809) == 672) cout << "Nowe u hav a rel liv Skiddo!!!!!" << endl;
                if (1 + (rand () % 809) == 673) cout << "Nowe u hav a rel liv Gogoat!!!!!" << endl;
                if (1 + (rand () % 809) == 674) cout << "Nowe u hav a rel liv Pancham!!!!!" << endl;
                if (1 + (rand () % 809) == 675) cout << "Nowe u hav a rel liv Pangoro!!!!!" << endl;
                if (1 + (rand () % 809) == 676) cout << "Nowe u hav a rel liv Furfrou!!!!!" << endl;
                if (1 + (rand () % 809) == 677) cout << "Nowe u hav a rel liv Espurr!!!!!" << endl;
                if (1 + (rand () % 809) == 678) cout << "Nowe u hav a rel liv Meowstic!!!!!" << endl;
                if (1 + (rand () % 809) == 679) cout << "Nowe u hav a rel liv Honedge!!!!!" << endl;
                if (1 + (rand () % 809) == 680) cout << "Nowe u hav a rel liv Doublade!!!!!" << endl;
                if (1 + (rand () % 809) == 681) cout << "Nowe u hav a rel liv Aegislash!!!!!" << endl;
                if (1 + (rand () % 809) == 682) cout << "Nowe u hav a rel liv Spritzee!!!!!" << endl;
                if (1 + (rand () % 809) == 683) cout << "Nowe u hav a rel liv Aromatisse!!!!!" << endl;
                if (1 + (rand () % 809) == 684) cout << "Nowe u hav a rel liv Swirlix!!!!!" << endl;
                if (1 + (rand () % 809) == 685) cout << "Nowe u hav a rel liv Slurpuff!!!!!" << endl;
                if (1 + (rand () % 809) == 686) cout << "Nowe u hav a rel liv Inkay!!!!!" << endl;
                if (1 + (rand () % 809) == 687) cout << "Nowe u hav a rel liv Malamar!!!!!" << endl;
                if (1 + (rand () % 809) == 688) cout << "Nowe u hav a rel liv Binacle!!!!!" << endl;
                if (1 + (rand () % 809) == 689) cout << "Nowe u hav a rel liv Barbaracle!!!!!" << endl;
                if (1 + (rand () % 809) == 690) cout << "Nowe u hav a rel liv Skrelp!!!!!" << endl;
                if (1 + (rand () % 809) == 691) cout << "Nowe u hav a rel liv Dragalge!!!!!" << endl;
                if (1 + (rand () % 809) == 692) cout << "Nowe u hav a rel liv Clauncher!!!!!" << endl;
                if (1 + (rand () % 809) == 693) cout << "Nowe u hav a rel liv Clawitzer!!!!!" << endl;
                if (1 + (rand () % 809) == 694) cout << "Nowe u hav a rel liv Helioptile!!!!!" << endl;
                if (1 + (rand () % 809) == 695) cout << "Nowe u hav a rel liv Heliolisk!!!!!" << endl;
                if (1 + (rand () % 809) == 696) cout << "Nowe u hav a rel liv Tyrunt!!!!!" << endl;
                if (1 + (rand () % 809) == 697) cout << "Nowe u hav a rel liv Tyrantrum!!!!!" << endl;
                if (1 + (rand () % 809) == 698) cout << "Nowe u hav a rel liv Amaura!!!!!" << endl;
                if (1 + (rand () % 809) == 699) cout << "Nowe u hav a rel liv Aurorus!!!!!" << endl;
                if (1 + (rand () % 809) == 700) cout << "Nowe u hav a rel liv Sylveon!!!!!" << endl;
                if (1 + (rand () % 809) == 701) cout << "Nowe u hav a rel liv Hawlucha!!!!!" << endl;
                if (1 + (rand () % 809) == 702) cout << "Nowe u hav a rel liv Dedenne!!!!!" << endl;
                if (1 + (rand () % 809) == 703) cout << "Nowe u hav a rel liv Carbink!!!!!" << endl;
                if (1 + (rand () % 809) == 704) cout << "Nowe u hav a rel liv Goomy!!!!!" << endl;
                if (1 + (rand () % 809) == 705) cout << "Nowe u hav a rel liv Sliggoo!!!!!" << endl;
                if (1 + (rand () % 809) == 706) cout << "Nowe u hav a rel liv Goodra!!!!!" << endl;
                if (1 + (rand () % 809) == 707) cout << "Nowe u hav a rel liv Klefki!!!!!" << endl;
                if (1 + (rand () % 809) == 708) cout << "Nowe u hav a rel liv Phantump!!!!!" << endl;
                if (1 + (rand () % 809) == 709) cout << "Nowe u hav a rel liv Trevenant!!!!!" << endl;
                if (1 + (rand () % 809) == 710) cout << "Nowe u hav a rel liv Pumpkaboo!!!!!" << endl;
                if (1 + (rand () % 809) == 711) cout << "Nowe u hav a rel liv Gourgeist!!!!!" << endl;
                if (1 + (rand () % 809) == 712) cout << "Nowe u hav a rel liv Bergmite!!!!!" << endl;
                if (1 + (rand () % 809) == 713) cout << "Nowe u hav a rel liv Avalugg!!!!!" << endl;
                if (1 + (rand () % 809) == 714) cout << "Nowe u hav a rel liv Noibat!!!!!" << endl;
                if (1 + (rand () % 809) == 715) cout << "Nowe u hav a rel liv Noivern!!!!!" << endl;
                if (1 + (rand () % 809) == 716) cout << "Nowe u hav a rel liv Xerneas!!!!!" << endl;
                if (1 + (rand () % 809) == 717) cout << "Nowe u hav a rel liv Yveltal!!!!!" << endl;
                if (1 + (rand () % 809) == 718) cout << "Nowe u hav a rel liv Zygarde!!!!!" << endl;
                if (1 + (rand () % 809) == 719) cout << "Nowe u hav a rel liv Diancie!!!!!" << endl;
                if (1 + (rand () % 809) == 720) cout << "Nowe u hav a rel liv Hoopa!!!!!" << endl;
                if (1 + (rand () % 809) == 721) cout << "Nowe u hav a rel liv Volcanion!!!!!" << endl;
                if (1 + (rand () % 809) == 722) cout << "Nowe u hav a rel liv Rowlet!!!!!" << endl;
                if (1 + (rand () % 809) == 723) cout << "Nowe u hav a rel liv Dartrix!!!!!" << endl;
                if (1 + (rand () % 809) == 724) cout << "Nowe u hav a rel liv Decidueye!!!!!" << endl;
                if (1 + (rand () % 809) == 725) cout << "Nowe u hav a rel liv Litten!!!!!" << endl;
                if (1 + (rand () % 809) == 726) cout << "Nowe u hav a rel liv Torracat!!!!!" << endl;
                if (1 + (rand () % 809) == 727) cout << "Nowe u hav a rel liv Incineroar!!!!!" << endl;
                if (1 + (rand () % 809) == 728) cout << "Nowe u hav a rel liv Popplio!!!!!" << endl;
                if (1 + (rand () % 809) == 729) cout << "Nowe u hav a rel liv Brionne!!!!!" << endl;
                if (1 + (rand () % 809) == 730) cout << "Nowe u hav a rel liv Primarina!!!!!" << endl;
                if (1 + (rand () % 809) == 731) cout << "Nowe u hav a rel liv Pikipek!!!!!" << endl;
                if (1 + (rand () % 809) == 732) cout << "Nowe u hav a rel liv Trumbeak!!!!!" << endl;
                if (1 + (rand () % 809) == 733) cout << "Nowe u hav a rel liv Toucannon!!!!!" << endl;
                if (1 + (rand () % 809) == 734) cout << "Nowe u hav a rel liv Yungoos!!!!!" << endl;
                if (1 + (rand () % 809) == 735) cout << "Nowe u hav a rel liv Gumshoos!!!!!" << endl;
                if (1 + (rand () % 809) == 736) cout << "Nowe u hav a rel liv Grubbin!!!!!" << endl;
                if (1 + (rand () % 809) == 737) cout << "Nowe u hav a rel liv Charjabug!!!!!" << endl;
                if (1 + (rand () % 809) == 738) cout << "Nowe u hav a rel liv Vikavolt!!!!!" << endl;
                if (1 + (rand () % 809) == 739) cout << "Nowe u hav a rel liv Crabrawler!!!!!" << endl;
                if (1 + (rand () % 809) == 740) cout << "Nowe u hav a rel liv Crabominable!!!!!" << endl;
                if (1 + (rand () % 809) == 741) cout << "Nowe u hav a rel liv Oricorio!!!!!" << endl;
                if (1 + (rand () % 809) == 742) cout << "Nowe u hav a rel liv Cutiefly!!!!!" << endl;
                if (1 + (rand () % 809) == 743) cout << "Nowe u hav a rel liv Ribombee!!!!!" << endl;
                if (1 + (rand () % 809) == 744) cout << "Nowe u hav a rel liv Rockruff!!!!!" << endl;
                if (1 + (rand () % 809) == 745) cout << "Nowe u hav a rel liv Lycanroc!!!!!" << endl;
                if (1 + (rand () % 809) == 746) cout << "Nowe u hav a rel liv Wishiwashi!!!!!" << endl;
                if (1 + (rand () % 809) == 747) cout << "Nowe u hav a rel liv Mareanie!!!!!" << endl;
                if (1 + (rand () % 809) == 748) cout << "Nowe u hav a rel liv Toxapex!!!!!" << endl;
                if (1 + (rand () % 809) == 749) cout << "Nowe u hav a rel liv Mudbray!!!!!" << endl;
                if (1 + (rand () % 809) == 750) cout << "Nowe u hav a rel liv Mudsdale!!!!!" << endl;
                if (1 + (rand () % 809) == 751) cout << "Nowe u hav a rel liv Dewpider!!!!!" << endl;
                if (1 + (rand () % 809) == 752) cout << "Nowe u hav a rel liv Araquanid!!!!!" << endl;
                if (1 + (rand () % 809) == 753) cout << "Nowe u hav a rel liv Fomantis!!!!!" << endl;
                if (1 + (rand () % 809) == 754) cout << "Nowe u hav a rel liv Lurantis!!!!!" << endl;
                if (1 + (rand () % 809) == 755) cout << "Nowe u hav a rel liv Morelull!!!!!" << endl;
                if (1 + (rand () % 809) == 756) cout << "Nowe u hav a rel liv Shiinotic!!!!!" << endl;
                if (1 + (rand () % 809) == 757) cout << "Nowe u hav a rel liv Salandit!!!!!" << endl;
                if (1 + (rand () % 809) == 758) cout << "Nowe u hav a rel liv Salazzle!!!!!" << endl;
                if (1 + (rand () % 809) == 759) cout << "Nowe u hav a rel liv Stufful!!!!!" << endl;
                if (1 + (rand () % 809) == 760) cout << "Nowe u hav a rel liv Bewear!!!!!" << endl;
                if (1 + (rand () % 809) == 761) cout << "Nowe u hav a rel liv Bounsweet!!!!!" << endl;
                if (1 + (rand () % 809) == 762) cout << "Nowe u hav a rel liv Steenee!!!!!" << endl;
                if (1 + (rand () % 809) == 763) cout << "Nowe u hav a rel liv Tsareena!!!!!" << endl;
                if (1 + (rand () % 809) == 764) cout << "Nowe u hav a rel liv Comfey!!!!!" << endl;
                if (1 + (rand () % 809) == 765) cout << "Nowe u hav a rel liv Oranguru!!!!!" << endl;
                if (1 + (rand () % 809) == 766) cout << "Nowe u hav a rel liv Passimian!!!!!" << endl;
                if (1 + (rand () % 809) == 767) cout << "Nowe u hav a rel liv Wimpod!!!!!" << endl;
                if (1 + (rand () % 809) == 768) cout << "Nowe u hav a rel liv Golisopod!!!!!" << endl;
                if (1 + (rand () % 809) == 769) cout << "Nowe u hav a rel liv Sandygast!!!!!" << endl;
                if (1 + (rand () % 809) == 770) cout << "Nowe u hav a rel liv Palossand!!!!!" << endl;
                if (1 + (rand () % 809) == 771) cout << "Nowe u hav a rel liv Pyukumuku!!!!!" << endl;
                if (1 + (rand () % 809) == 772) cout << "Nowe u hav a rel liv Type: Null!!!!!" << endl;
                if (1 + (rand () % 809) == 773) cout << "Nowe u hav a rel liv Silvally!!!!!" << endl;
                if (1 + (rand () % 809) == 774) cout << "Nowe u hav a rel liv Minior!!!!!" << endl;
                if (1 + (rand () % 809) == 775) cout << "Nowe u hav a rel liv Komala!!!!!" << endl;
                if (1 + (rand () % 809) == 776) cout << "Nowe u hav a rel liv Turtonator!!!!!" << endl;
                if (1 + (rand () % 809) == 777) cout << "Nowe u hav a rel liv Togedemaru!!!!!" << endl;
                if (1 + (rand () % 809) == 778) cout << "Nowe u hav a rel liv Mimikyu!!!!!" << endl;
                if (1 + (rand () % 809) == 779) cout << "Nowe u hav a rel liv Bruxish!!!!!" << endl;
                if (1 + (rand () % 809) == 780) cout << "Nowe u hav a rel liv Drampa!!!!!" << endl;
                if (1 + (rand () % 809) == 781) cout << "Nowe u hav a rel liv Dhelmise!!!!!" << endl;
                if (1 + (rand () % 809) == 782) cout << "Nowe u hav a rel liv Jangmo-o!!!!!" << endl;
                if (1 + (rand () % 809) == 783) cout << "Nowe u hav a rel liv Hakamo-o!!!!!" << endl;
                if (1 + (rand () % 809) == 784) cout << "Nowe u hav a rel liv Kommo-o!!!!!" << endl;
                if (1 + (rand () % 809) == 785) cout << "Nowe u hav a rel liv Tapu Koko!!!!!" << endl;
                if (1 + (rand () % 809) == 786) cout << "Nowe u hav a rel liv Tapu Lele!!!!!" << endl;
                if (1 + (rand () % 809) == 787) cout << "Nowe u hav a rel liv Tapu Bulu!!!!!" << endl;
                if (1 + (rand () % 809) == 788) cout << "Nowe u hav a rel liv Tapu Fini!!!!!" << endl;
                if (1 + (rand () % 809) == 789) cout << "Nowe u hav a rel liv Cosmog!!!!!" << endl;
                if (1 + (rand () % 809) == 790) cout << "Nowe u hav a rel liv Cosmoem!!!!!" << endl;
                if (1 + (rand () % 809) == 791) cout << "Nowe u hav a rel liv Solgaleo!!!!!" << endl;
                if (1 + (rand () % 809) == 792) cout << "Nowe u hav a rel liv Lunala!!!!!" << endl;
                if (1 + (rand () % 809) == 793) cout << "Nowe u hav a rel liv Nihilego!!!!!" << endl;
                if (1 + (rand () % 809) == 794) cout << "Nowe u hav a rel liv Buzzwole!!!!!" << endl;
                if (1 + (rand () % 809) == 795) cout << "Nowe u hav a rel liv Pheromosa!!!!!" << endl;
                if (1 + (rand () % 809) == 796) cout << "Nowe u hav a rel liv Xurkitree!!!!!" << endl;
                if (1 + (rand () % 809) == 797) cout << "Nowe u hav a rel liv Celesteela!!!!!" << endl;
                if (1 + (rand () % 809) == 798) cout << "Nowe u hav a rel liv Kartana!!!!!" << endl;
                if (1 + (rand () % 809) == 799) cout << "Nowe u hav a rel liv Guzzlord!!!!!" << endl;
                if (1 + (rand () % 809) == 800) cout << "Nowe u hav a rel liv Necrozma!!!!!" << endl;
                if (1 + (rand () % 809) == 801) cout << "Nowe u hav a rel liv Magearna!!!!!" << endl;
                if (1 + (rand () % 809) == 802) cout << "Nowe u hav a rel liv Marshadow!!!!!" << endl;
                if (1 + (rand () % 809) == 803) cout << "Nowe u hav a rel liv Poipole!!!!!" << endl;
                if (1 + (rand () % 809) == 804) cout << "Nowe u hav a rel liv Naganadel!!!!!" << endl;
                if (1 + (rand () % 809) == 805) cout << "Nowe u hav a rel liv Stakataka!!!!!" << endl;
                if (1 + (rand () % 809) == 806) cout << "Nowe u hav a rel liv Blacephalon!!!!!" << endl;
                if (1 + (rand () % 809) == 807) cout << "Nowe u hav a rel liv Zeraora!!!!!" << endl;
                if (1 + (rand () % 809) == 808) cout << "Nowe u hav a rel liv Meltan!!!!!" << endl;
                if (1 + (rand () % 809) == 809) cout << "Nowe u hav a rel liv Melmetal!!!!!" << endl;
}


		gfxFlushBuffers();
		gfxSwapBuffers();
		gspWaitForVBlank();
		if (kDown & KEY_B) break;
		if (A == 31500){
		memset(param, 0, sizeof(param));
		memset(hmac, 0, sizeof(hmac));
		APT_PrepareToDoApplicationJump(0, shopID, 0);
		APT_DoApplicationJump(param, sizeof(param), hmac); } }

	gfxExit();
	return 0;
}
