#include <3ds.h>
#include <iostream>
#include <string>
#include <cstdlib>
#include <ctime>
#include <cstring>

using namespace std;

int A = 0;

int main(void)
{
	gfxInitDefault();
	consoleInit(GFX_TOP, NULL);
	u8 param[0x300];
	u8 hmac[0x20];
	u8 regionCode;
	u64 shopID;
	CFGU_SecureInfoGetRegion(&regionCode);
	switch (regionCode)
	{
	case 0:
		shopID = 0x0004001000020900;
		break;
	case 1:
		shopID = 0x0004001000021900;
		break;
	case 2:
		shopID = 0x0004001000022900;
		break;
	default:
		shopID = 0x00;
	}
        srand(time(0));

        cout << "v2.4" << endl;
        cout << "if it dont work then go for a pron break and try again lator!" << endl;
        cout << "if u too scared for pokegomz pres b" << endl;

	for(A = 0; A < 60000; A = A+5){
		hidScanInput();
		u32 kDown = hidKeysDown();
		if (A == 1800) cout << "DOWNLOADING FLIES OF POKEGOMZ" << endl;
		if (A == 3600) cout << "DOWNLOA COMPLETE!" << endl;
		if (A == 5400)
{
 cout << "bribing gam freck to aron valt all valted pokegomz" << endl;
 cout << "in sord and sheld.." << endl;
}
		if (A == 7200) cout << "installing frii pokegom gam.." << endl;
		if (A == 9600) cout << "frii pokegom gam instal complet!" << endl;
		if (A == 10200) cout << "jus make sur u don kil ur pokegomz OR U BRIC!" << endl;
		if (A == 10800) cout << "pathcing flies of pokegomz.." << endl;
		if (A == 11400) cout << "sicc!! now generat new systume imag" << endl;
		if (A == 13200) cout << "systume imag genrat now flash ontoo emptii brian" << endl;
		if (A == 15000) cout << "doo sam ting with reecuvury and FEI partishuns" << endl;
		if (A == 16800) cout << "nowe update PBTS MKPN eedishun too v2.0.0" << endl;
		if (A == 18600) cout << "now u hav v2.0.0 becaus v0.0.1 suck 4-bite bik." << endl;
                if (A == 20400) cout << "Downola 2TB ReshiRAM!" << endl;
		if (A == 22200) cout << "flash buy-os form u.." << endl;
		if (A == 23400) cout << "OH No HECK yo got frikken ban by MASUDA!!!" << endl;
		if (A == 25200) cout << "makin alt accooun (ur such a hackers)" << endl;
		if (A == 26100) cout << "u got aron ban my dud!!" << endl;
                if (A == 27000) cout << "cunvirtin flies of pokegomz" << endl;
                if (A == 27900) cout << "now imparti flies of pokegomz" << endl;
                if (A == 28800) cout << "Gib U pokegomz in rel lif.." << endl;
		if (A == 29700) {
                if (1 + (rand () % 493) == 1) cout << "Nowe u hav a rel liv Bulbasaur!!!!!" << endl;
                if (1 + (rand () % 493) == 2) cout << "Nowe u hav a rel liv Ivysaur!!!!!" << endl;
                if (1 + (rand () % 493) == 3) cout << "Nowe u hav a rel liv Venusaur!!!!!" << endl;
                if (1 + (rand () % 493) == 4) cout << "Nowe u hav a rel liv Charmander!!!!!" << endl;
                if (1 + (rand () % 493) == 5) cout << "Nowe u hav a rel liv Charmeleon!!!!!" << endl;
                if (1 + (rand () % 493) == 6) cout << "Nowe u hav a rel liv Charizard!!!!!" << endl;
                if (1 + (rand () % 493) == 7) cout << "Nowe u hav a rel liv Squirtle!!!!!" << endl;
                if (1 + (rand () % 493) == 8) cout << "Nowe u hav a rel liv Wartortle!!!!!" << endl;
                if (1 + (rand () % 493) == 9) cout << "Nowe u hav a rel liv Blastoise!!!!!" << endl;
                if (1 + (rand () % 493) == 10) cout << "Nowe u hav a rel liv Caterpie!!!!!" << endl;
                if (1 + (rand () % 493) == 11) cout << "Nowe u hav a rel liv Metapod!!!!!" << endl;
                if (1 + (rand () % 493) == 12) cout << "Nowe u hav a rel liv Butterfree!!!!!" << endl;
                if (1 + (rand () % 493) == 13) cout << "Nowe u hav a rel liv Weedle!!!!!" << endl;
                if (1 + (rand () % 493) == 14) cout << "Nowe u hav a rel liv Kakuna!!!!!" << endl;
                if (1 + (rand () % 493) == 15) cout << "Nowe u hav a rel liv Beedrill!!!!!" << endl;
                if (1 + (rand () % 493) == 16) cout << "Nowe u hav a rel liv Pidgey!!!!!" << endl;
                if (1 + (rand () % 493) == 17) cout << "Nowe u hav a rel liv Pidgeotto!!!!!" << endl;
                if (1 + (rand () % 493) == 18) cout << "Nowe u hav a rel liv Pidgeot!!!!!" << endl;
                if (1 + (rand () % 493) == 19) cout << "Nowe u hav a rel liv Rattata!!!!!" << endl;
                if (1 + (rand () % 493) == 20) cout << "Nowe u hav a rel liv Raticate!!!!!" << endl;
                if (1 + (rand () % 493) == 21) cout << "Nowe u hav a rel liv Spearow!!!!!" << endl;
                if (1 + (rand () % 493) == 22) cout << "Nowe u hav a rel liv Fearow!!!!!" << endl;
                if (1 + (rand () % 493) == 23) cout << "Nowe u hav a rel liv Ekans!!!!!" << endl;
                if (1 + (rand () % 493) == 24) cout << "Nowe u hav a rel liv Arbok!!!!!" << endl;
                if (1 + (rand () % 493) == 25) cout << "Nowe u hav a rel liv Pikachu!!!!!" << endl;
                if (1 + (rand () % 493) == 26) cout << "Nowe u hav a rel liv Raichu!!!!!" << endl;
                if (1 + (rand () % 493) == 27) cout << "Nowe u hav a rel liv Sandshrew!!!!!" << endl;
                if (1 + (rand () % 493) == 28) cout << "Nowe u hav a rel liv Sandslash!!!!!" << endl;
                if (1 + (rand () % 493) == 29) cout << "Nowe u hav a rel liv Nidoran F!!!!!" << endl;
                if (1 + (rand () % 493) == 30) cout << "Nowe u hav a rel liv Nidorina!!!!!" << endl;
                if (1 + (rand () % 493) == 31) cout << "Nowe u hav a rel liv Nidoqueen!!!!!" << endl;
                if (1 + (rand () % 493) == 32) cout << "Nowe u hav a rel liv Nidoran M!!!!!" << endl;
                if (1 + (rand () % 493) == 33) cout << "Nowe u hav a rel liv Nidorino!!!!!" << endl;
                if (1 + (rand () % 493) == 34) cout << "Nowe u hav a rel liv Nidoking!!!!!" << endl;
                if (1 + (rand () % 493) == 35) cout << "Nowe u hav a rel liv Clefairy!!!!!" << endl;
                if (1 + (rand () % 493) == 36) cout << "Nowe u hav a rel liv Clefable!!!!!" << endl;
                if (1 + (rand () % 493) == 37) cout << "Nowe u hav a rel liv Vulpix!!!!!" << endl;
                if (1 + (rand () % 493) == 38) cout << "Nowe u hav a rel liv Ninetales!!!!!" << endl;
                if (1 + (rand () % 493) == 39) cout << "Nowe u hav a rel liv Jigglypuff!!!!!" << endl;
                if (1 + (rand () % 493) == 40) cout << "Nowe u hav a rel liv Wigglytuff!!!!!" << endl;
                if (1 + (rand () % 493) == 41) cout << "Nowe u hav a rel liv Zubat!!!!!" << endl;
                if (1 + (rand () % 493) == 42) cout << "Nowe u hav a rel liv Golbat!!!!!" << endl;
                if (1 + (rand () % 493) == 43) cout << "Nowe u hav a rel liv Oddish!!!!!" << endl;
                if (1 + (rand () % 493) == 44) cout << "Nowe u hav a rel liv Gloom!!!!!" << endl;
                if (1 + (rand () % 493) == 45) cout << "Nowe u hav a rel liv Vileplume!!!!!" << endl;
                if (1 + (rand () % 493) == 46) cout << "Nowe u hav a rel liv Paras!!!!!" << endl;
                if (1 + (rand () % 493) == 47) cout << "Nowe u hav a rel liv Parasect!!!!!" << endl;
                if (1 + (rand () % 493) == 48) cout << "Nowe u hav a rel liv Venonat!!!!!" << endl;
                if (1 + (rand () % 493) == 49) cout << "Nowe u hav a rel liv Venomoth!!!!!" << endl;
                if (1 + (rand () % 493) == 50) cout << "Nowe u hav a rel liv Diglett!!!!!" << endl;
                if (1 + (rand () % 493) == 51) cout << "Nowe u hav a rel liv Dugtrio!!!!!" << endl;
                if (1 + (rand () % 493) == 52) cout << "Nowe u hav a rel liv Meowth!!!!!" << endl;
                if (1 + (rand () % 493) == 53) cout << "Nowe u hav a rel liv Persian!!!!!" << endl;
                if (1 + (rand () % 493) == 54) cout << "Nowe u hav a rel liv Psyduck!!!!!" << endl;
                if (1 + (rand () % 493) == 55) cout << "Nowe u hav a rel liv Golduck!!!!!" << endl;
                if (1 + (rand () % 493) == 56) cout << "Nowe u hav a rel liv Mankey!!!!!" << endl;
                if (1 + (rand () % 493) == 57) cout << "Nowe u hav a rel liv Primeape!!!!!" << endl;
                if (1 + (rand () % 493) == 58) cout << "Nowe u hav a rel liv Growlithe!!!!!" << endl;
                if (1 + (rand () % 493) == 59) cout << "Nowe u hav a rel liv Arcanine!!!!!" << endl;
                if (1 + (rand () % 493) == 60) cout << "Nowe u hav a rel liv Poliwag!!!!!" << endl;
                if (1 + (rand () % 493) == 61) cout << "Nowe u hav a rel liv Poliwhirl!!!!!" << endl;
                if (1 + (rand () % 493) == 62) cout << "Nowe u hav a rel liv Poliwrath!!!!!" << endl;
                if (1 + (rand () % 493) == 63) cout << "Nowe u hav a rel liv Abra!!!!!" << endl;
                if (1 + (rand () % 493) == 64) cout << "Nowe u hav a rel liv Kadabra!!!!!" << endl;
                if (1 + (rand () % 493) == 65) cout << "Nowe u hav a rel liv Alakazam!!!!!" << endl;
                if (1 + (rand () % 493) == 66) cout << "Nowe u hav a rel liv Machop!!!!!" << endl;
                if (1 + (rand () % 493) == 67) cout << "Nowe u hav a rel liv Machoke!!!!!" << endl;
                if (1 + (rand () % 493) == 68) cout << "Nowe u hav a rel liv Machamp!!!!!" << endl;
                if (1 + (rand () % 493) == 69) cout << "Nowe u hav a rel liv Bellsprout!!!!!" << endl;
                if (1 + (rand () % 493) == 70) cout << "Nowe u hav a rel liv Weepinbell!!!!!" << endl;
                if (1 + (rand () % 493) == 71) cout << "Nowe u hav a rel liv Victreebel!!!!!" << endl;
                if (1 + (rand () % 493) == 72) cout << "Nowe u hav a rel liv Tentacool!!!!!" << endl;
                if (1 + (rand () % 493) == 73) cout << "Nowe u hav a rel liv Tentacruel!!!!!" << endl;
                if (1 + (rand () % 493) == 74) cout << "Nowe u hav a rel liv Geodude!!!!!" << endl;
                if (1 + (rand () % 493) == 75) cout << "Nowe u hav a rel liv Graveler!!!!!" << endl;
                if (1 + (rand () % 493) == 76) cout << "Nowe u hav a rel liv Golem!!!!!" << endl;
                if (1 + (rand () % 493) == 77) cout << "Nowe u hav a rel liv Ponyta!!!!!" << endl;
                if (1 + (rand () % 493) == 78) cout << "Nowe u hav a rel liv Rapidash!!!!!" << endl;
                if (1 + (rand () % 493) == 79) cout << "Nowe u hav a rel liv Slowpoke!!!!!" << endl;
                if (1 + (rand () % 493) == 80) cout << "Nowe u hav a rel liv Slowbro!!!!!" << endl;
                if (1 + (rand () % 493) == 81) cout << "Nowe u hav a rel liv Magnemite!!!!!" << endl;
                if (1 + (rand () % 493) == 82) cout << "Nowe u hav a rel liv Magneton!!!!!" << endl;
                if (1 + (rand () % 493) == 83) cout << "Nowe u hav a rel liv Farfetch'd!!!!!" << endl;
                if (1 + (rand () % 493) == 84) cout << "Nowe u hav a rel liv Doduo!!!!!" << endl;
                if (1 + (rand () % 493) == 85) cout << "Nowe u hav a rel liv Dodrio!!!!!" << endl;
                if (1 + (rand () % 493) == 86) cout << "Nowe u hav a rel liv Seel!!!!!" << endl;
                if (1 + (rand () % 493) == 87) cout << "Nowe u hav a rel liv Dewgong!!!!!" << endl;
                if (1 + (rand () % 493) == 88) cout << "Nowe u hav a rel liv Grimer!!!!!" << endl;
                if (1 + (rand () % 493) == 89) cout << "Nowe u hav a rel liv Muk!!!!!" << endl;
                if (1 + (rand () % 493) == 90) cout << "Nowe u hav a rel liv Shellder!!!!!" << endl;
                if (1 + (rand () % 493) == 91) cout << "Nowe u hav a rel liv Cloyster!!!!!" << endl;
                if (1 + (rand () % 493) == 92) cout << "Nowe u hav a rel liv Gastly!!!!!" << endl;
                if (1 + (rand () % 493) == 93) cout << "Nowe u hav a rel liv Haunter!!!!!" << endl;
                if (1 + (rand () % 493) == 94) cout << "Nowe u hav a rel liv Gengar!!!!!" << endl;
                if (1 + (rand () % 493) == 95) cout << "Nowe u hav a rel liv Onix!!!!!" << endl;
                if (1 + (rand () % 493) == 96) cout << "Nowe u hav a rel liv Drowzee!!!!!" << endl;
                if (1 + (rand () % 493) == 97) cout << "Nowe u hav a rel liv Hypno!!!!!" << endl;
                if (1 + (rand () % 493) == 98) cout << "Nowe u hav a rel liv Krabby!!!!!" << endl;
                if (1 + (rand () % 493) == 99) cout << "Nowe u hav a rel liv Kingler!!!!!" << endl;
                if (1 + (rand () % 493) == 100) cout << "Nowe u hav a rel liv Voltorb!!!!!" << endl;
                if (1 + (rand () % 493) == 101) cout << "Nowe u hav a rel liv Electrode!!!!!" << endl;
                if (1 + (rand () % 493) == 102) cout << "Nowe u hav a rel liv Exeggcute!!!!!" << endl;
                if (1 + (rand () % 493) == 103) cout << "Nowe u hav a rel liv Exeggutor!!!!!" << endl;
                if (1 + (rand () % 493) == 104) cout << "Nowe u hav a rel liv Cubone!!!!!" << endl;
                if (1 + (rand () % 493) == 105) cout << "Nowe u hav a rel liv Marowak!!!!!" << endl;
                if (1 + (rand () % 493) == 106) cout << "Nowe u hav a rel liv Hitmonlee!!!!!" << endl;
                if (1 + (rand () % 493) == 107) cout << "Nowe u hav a rel liv Hitmonchan!!!!!" << endl;
                if (1 + (rand () % 493) == 108) cout << "Nowe u hav a rel liv Lickitung!!!!!" << endl;
                if (1 + (rand () % 493) == 109) cout << "Nowe u hav a rel liv Koffing!!!!!" << endl;
                if (1 + (rand () % 493) == 110) cout << "Nowe u hav a rel liv Weezing!!!!!" << endl;
                if (1 + (rand () % 493) == 111) cout << "Nowe u hav a rel liv Rhyhorn!!!!!" << endl;
                if (1 + (rand () % 493) == 112) cout << "Nowe u hav a rel liv Rhydon!!!!!" << endl;
                if (1 + (rand () % 493) == 113) cout << "Nowe u hav a rel liv Chansey!!!!!" << endl;
                if (1 + (rand () % 493) == 114) cout << "Nowe u hav a rel liv Tangela!!!!!" << endl;
                if (1 + (rand () % 493) == 115) cout << "Nowe u hav a rel liv Kangaskhan!!!!!" << endl;
                if (1 + (rand () % 493) == 116) cout << "Nowe u hav a rel liv Horsea!!!!!" << endl;
                if (1 + (rand () % 493) == 117) cout << "Nowe u hav a rel liv Seadra!!!!!" << endl;
                if (1 + (rand () % 493) == 118) cout << "Nowe u hav a rel liv Goldeen!!!!!" << endl;
                if (1 + (rand () % 493) == 119) cout << "Nowe u hav a rel liv Seaking!!!!!" << endl;
                if (1 + (rand () % 493) == 120) cout << "Nowe u hav a rel liv Staryu!!!!!" << endl;
                if (1 + (rand () % 493) == 121) cout << "Nowe u hav a rel liv Starmie!!!!!" << endl;
                if (1 + (rand () % 493) == 122) cout << "Nowe u hav a rel liv Mr. Mime!!!!!" << endl;
                if (1 + (rand () % 493) == 123) cout << "Nowe u hav a rel liv Scyther!!!!!" << endl;
                if (1 + (rand () % 493) == 124) cout << "Nowe u hav a rel liv Jynx!!!!!" << endl;
                if (1 + (rand () % 493) == 125) cout << "Nowe u hav a rel liv Electabuzz!!!!!" << endl;
                if (1 + (rand () % 493) == 126) cout << "Nowe u hav a rel liv Magmar!!!!!" << endl;
                if (1 + (rand () % 493) == 127) cout << "Nowe u hav a rel liv Pinsir!!!!!" << endl;
                if (1 + (rand () % 493) == 128) cout << "Nowe u hav a rel liv Tauros!!!!!" << endl;
                if (1 + (rand () % 493) == 129) cout << "Nowe u hav a rel liv Magikarp!!!!!" << endl;
                if (1 + (rand () % 493) == 130) cout << "Nowe u hav a rel liv Gyarados!!!!!" << endl;
                if (1 + (rand () % 493) == 131) cout << "Nowe u hav a rel liv Lapras!!!!!" << endl;
                if (1 + (rand () % 493) == 132) cout << "Nowe u hav a rel liv Ditto!!!!!" << endl;
                if (1 + (rand () % 493) == 133) cout << "Nowe u hav a rel liv Eevee!!!!!" << endl;
                if (1 + (rand () % 493) == 134) cout << "Nowe u hav a rel liv Vaporeon!!!!!" << endl;
                if (1 + (rand () % 493) == 135) cout << "Nowe u hav a rel liv Jolteon!!!!!" << endl;
                if (1 + (rand () % 493) == 136) cout << "Nowe u hav a rel liv Flareon!!!!!" << endl;
                if (1 + (rand () % 493) == 137) cout << "Nowe u hav a rel liv Porygon!!!!!" << endl;
                if (1 + (rand () % 493) == 138) cout << "Nowe u hav a rel liv Omanyte!!!!!" << endl;
                if (1 + (rand () % 493) == 139) cout << "Nowe u hav a rel liv Omastar!!!!!" << endl;
                if (1 + (rand () % 493) == 140) cout << "Nowe u hav a rel liv Kabuto!!!!!" << endl;
                if (1 + (rand () % 493) == 141) cout << "Nowe u hav a rel liv Kabutops!!!!!" << endl;
                if (1 + (rand () % 493) == 142) cout << "Nowe u hav a rel liv Aerodactyl!!!!!" << endl;
                if (1 + (rand () % 493) == 143) cout << "Nowe u hav a rel liv Snorlax!!!!!" << endl;
                if (1 + (rand () % 493) == 144) cout << "Nowe u hav a rel liv Articuno!!!!!" << endl;
                if (1 + (rand () % 493) == 145) cout << "Nowe u hav a rel liv Zapdos!!!!!" << endl;
                if (1 + (rand () % 493) == 146) cout << "Nowe u hav a rel liv Moltres!!!!!" << endl;
                if (1 + (rand () % 493) == 147) cout << "Nowe u hav a rel liv Dratini!!!!!" << endl;
                if (1 + (rand () % 493) == 148) cout << "Nowe u hav a rel liv Dragonair!!!!!" << endl;
                if (1 + (rand () % 493) == 149) cout << "Nowe u hav a rel liv Dragonite!!!!!" << endl;
                if (1 + (rand () % 493) == 150) cout << "Nowe u hav a rel liv Mewtwo!!!!!" << endl;
                if (1 + (rand () % 493) == 151) cout << "Nowe u hav a rel liv Mew!!!!!" << endl;
                if (1 + (rand () % 493) == 152) cout << "Nowe u hav a rel liv Chikorita!!!!!" << endl;
                if (1 + (rand () % 493) == 153) cout << "Nowe u hav a rel liv Bayleef!!!!!" << endl;
                if (1 + (rand () % 493) == 154) cout << "Nowe u hav a rel liv Meganium!!!!!" << endl;
                if (1 + (rand () % 493) == 155) cout << "Nowe u hav a rel liv Cyndaquil!!!!!" << endl;
                if (1 + (rand () % 493) == 156) cout << "Nowe u hav a rel liv Quilava!!!!!" << endl;
                if (1 + (rand () % 493) == 157) cout << "Nowe u hav a rel liv Typhlosion!!!!!" << endl;
                if (1 + (rand () % 493) == 158) cout << "Nowe u hav a rel liv Totodile!!!!!" << endl;
                if (1 + (rand () % 493) == 159) cout << "Nowe u hav a rel liv Croconaw!!!!!" << endl;
                if (1 + (rand () % 493) == 160) cout << "Nowe u hav a rel liv Feraligatr!!!!!" << endl;
                if (1 + (rand () % 493) == 161) cout << "Nowe u hav a rel liv Sentret!!!!!" << endl;
                if (1 + (rand () % 493) == 162) cout << "Nowe u hav a rel liv Furret!!!!!" << endl;
                if (1 + (rand () % 493) == 163) cout << "Nowe u hav a rel liv Hoothoot!!!!!" << endl;
                if (1 + (rand () % 493) == 164) cout << "Nowe u hav a rel liv Noctowl!!!!!" << endl;
                if (1 + (rand () % 493) == 165) cout << "Nowe u hav a rel liv Ledyba!!!!!" << endl;
                if (1 + (rand () % 493) == 166) cout << "Nowe u hav a rel liv Ledian!!!!!" << endl;
                if (1 + (rand () % 493) == 167) cout << "Nowe u hav a rel liv Spinarak!!!!!" << endl;
                if (1 + (rand () % 493) == 168) cout << "Nowe u hav a rel liv Ariados!!!!!" << endl;
                if (1 + (rand () % 493) == 169) cout << "Nowe u hav a rel liv Crobat!!!!!" << endl;
                if (1 + (rand () % 493) == 170) cout << "Nowe u hav a rel liv Chinchou!!!!!" << endl;
                if (1 + (rand () % 493) == 171) cout << "Nowe u hav a rel liv Lanturn!!!!!" << endl;
                if (1 + (rand () % 493) == 172) cout << "Nowe u hav a rel liv Pichu!!!!!" << endl;
                if (1 + (rand () % 493) == 173) cout << "Nowe u hav a rel liv Cleffa!!!!!" << endl;
                if (1 + (rand () % 493) == 174) cout << "Nowe u hav a rel liv Igglybuff!!!!!" << endl;
                if (1 + (rand () % 493) == 175) cout << "Nowe u hav a rel liv Togepi!!!!!" << endl;
                if (1 + (rand () % 493) == 176) cout << "Nowe u hav a rel liv Togetic!!!!!" << endl;
                if (1 + (rand () % 493) == 177) cout << "Nowe u hav a rel liv Natu!!!!!" << endl;
                if (1 + (rand () % 493) == 178) cout << "Nowe u hav a rel liv Xatu!!!!!" << endl;
                if (1 + (rand () % 493) == 179) cout << "Nowe u hav a rel liv Mareep!!!!!" << endl;
                if (1 + (rand () % 493) == 180) cout << "Nowe u hav a rel liv Flaaffy!!!!!" << endl;
                if (1 + (rand () % 493) == 181) cout << "Nowe u hav a rel liv Ampharos!!!!!" << endl;
                if (1 + (rand () % 493) == 182) cout << "Nowe u hav a rel liv Bellossom!!!!!" << endl;
                if (1 + (rand () % 493) == 183) cout << "Nowe u hav a rel liv Marill!!!!!" << endl;
                if (1 + (rand () % 493) == 184) cout << "Nowe u hav a rel liv Azumarill!!!!!" << endl;
                if (1 + (rand () % 493) == 185) cout << "Nowe u hav a rel liv Sudowoodo!!!!!" << endl;
                if (1 + (rand () % 493) == 186) cout << "Nowe u hav a rel liv Politoed!!!!!" << endl;
                if (1 + (rand () % 493) == 187) cout << "Nowe u hav a rel liv Hoppip!!!!!" << endl;
                if (1 + (rand () % 493) == 188) cout << "Nowe u hav a rel liv Skiploom!!!!!" << endl;
                if (1 + (rand () % 493) == 189) cout << "Nowe u hav a rel liv Jumpluff!!!!!" << endl;
                if (1 + (rand () % 493) == 190) cout << "Nowe u hav a rel liv Aipom!!!!!" << endl;
                if (1 + (rand () % 493) == 191) cout << "Nowe u hav a rel liv Sunkern!!!!!" << endl;
                if (1 + (rand () % 493) == 192) cout << "Nowe u hav a rel liv Sunflora!!!!!" << endl;
                if (1 + (rand () % 493) == 193) cout << "Nowe u hav a rel liv Yanma!!!!!" << endl;
                if (1 + (rand () % 493) == 194) cout << "Nowe u hav a rel liv Wooper!!!!!" << endl;
                if (1 + (rand () % 493) == 195) cout << "Nowe u hav a rel liv Quagsire!!!!!" << endl;
                if (1 + (rand () % 493) == 196) cout << "Nowe u hav a rel liv Espeon!!!!!" << endl;
                if (1 + (rand () % 493) == 197) cout << "Nowe u hav a rel liv Umbreon!!!!!" << endl;
                if (1 + (rand () % 493) == 198) cout << "Nowe u hav a rel liv Murkrow!!!!!" << endl;
                if (1 + (rand () % 493) == 199) cout << "Nowe u hav a rel liv Slowking!!!!!" << endl;
                if (1 + (rand () % 493) == 200) cout << "Nowe u hav a rel liv Misdreavus!!!!!" << endl;
                if (1 + (rand () % 493) == 201) cout << "Nowe u hav a rel liv Unown!!!!!" << endl;
                if (1 + (rand () % 493) == 202) cout << "Nowe u hav a rel liv Wobbuffet!!!!!" << endl;
                if (1 + (rand () % 493) == 203) cout << "Nowe u hav a rel liv Girafarig!!!!!" << endl;
                if (1 + (rand () % 493) == 204) cout << "Nowe u hav a rel liv Pineco!!!!!" << endl;
                if (1 + (rand () % 493) == 205) cout << "Nowe u hav a rel liv Forretress!!!!!" << endl;
                if (1 + (rand () % 493) == 206) cout << "Nowe u hav a rel liv Dunsparce!!!!!" << endl;
                if (1 + (rand () % 493) == 207) cout << "Nowe u hav a rel liv Gligar!!!!!" << endl;
                if (1 + (rand () % 493) == 208) cout << "Nowe u hav a rel liv Steelix!!!!!" << endl;
                if (1 + (rand () % 493) == 209) cout << "Nowe u hav a rel liv Snubbull!!!!!" << endl;
                if (1 + (rand () % 493) == 210) cout << "Nowe u hav a rel liv Granbull!!!!!" << endl;
                if (1 + (rand () % 493) == 211) cout << "Nowe u hav a rel liv Qwilfish!!!!!" << endl;
                if (1 + (rand () % 493) == 212) cout << "Nowe u hav a rel liv Scizor!!!!!" << endl;
                if (1 + (rand () % 493) == 213) cout << "Nowe u hav a rel liv Shuckle!!!!!" << endl;
                if (1 + (rand () % 493) == 214) cout << "Nowe u hav a rel liv Heracross!!!!!" << endl;
                if (1 + (rand () % 493) == 215) cout << "Nowe u hav a rel liv Sneasel!!!!!" << endl;
                if (1 + (rand () % 493) == 216) cout << "Nowe u hav a rel liv Teddiursa!!!!!" << endl;
                if (1 + (rand () % 493) == 217) cout << "Nowe u hav a rel liv Ursaring!!!!!" << endl;
                if (1 + (rand () % 493) == 218) cout << "Nowe u hav a rel liv Slugma!!!!!" << endl;
                if (1 + (rand () % 493) == 219) cout << "Nowe u hav a rel liv Magcargo!!!!!" << endl;
                if (1 + (rand () % 493) == 220) cout << "Nowe u hav a rel liv Swinub!!!!!" << endl;
                if (1 + (rand () % 493) == 221) cout << "Nowe u hav a rel liv Piloswine!!!!!" << endl;
                if (1 + (rand () % 493) == 222) cout << "Nowe u hav a rel liv Corsola!!!!!" << endl;
                if (1 + (rand () % 493) == 223) cout << "Nowe u hav a rel liv Remoraid!!!!!" << endl;
                if (1 + (rand () % 493) == 224) cout << "Nowe u hav a rel liv Octillery!!!!!" << endl;
                if (1 + (rand () % 493) == 225) cout << "Nowe u hav a rel liv Delibird!!!!!" << endl;
                if (1 + (rand () % 493) == 226) cout << "Nowe u hav a rel liv Mantine!!!!!" << endl;
                if (1 + (rand () % 493) == 227) cout << "Nowe u hav a rel liv Skarmory!!!!!" << endl;
                if (1 + (rand () % 493) == 228) cout << "Nowe u hav a rel liv Houndour!!!!!" << endl;
                if (1 + (rand () % 493) == 229) cout << "Nowe u hav a rel liv Houndoom!!!!!" << endl;
                if (1 + (rand () % 493) == 230) cout << "Nowe u hav a rel liv Kingdra!!!!!" << endl;
                if (1 + (rand () % 493) == 231) cout << "Nowe u hav a rel liv Phanpy!!!!!" << endl;
                if (1 + (rand () % 493) == 232) cout << "Nowe u hav a rel liv Donphan!!!!!" << endl;
                if (1 + (rand () % 493) == 233) cout << "Nowe u hav a rel liv Porygon2!!!!!" << endl;
                if (1 + (rand () % 493) == 234) cout << "Nowe u hav a rel liv Stantler!!!!!" << endl;
                if (1 + (rand () % 493) == 235) cout << "Nowe u hav a rel liv Smeargle!!!!!" << endl;
                if (1 + (rand () % 493) == 236) cout << "Nowe u hav a rel liv Tyrogue!!!!!" << endl;
                if (1 + (rand () % 493) == 237) cout << "Nowe u hav a rel liv Hitmontop!!!!!" << endl;
                if (1 + (rand () % 493) == 238) cout << "Nowe u hav a rel liv Smoochum!!!!!" << endl;
                if (1 + (rand () % 493) == 239) cout << "Nowe u hav a rel liv Elekid!!!!!" << endl;
                if (1 + (rand () % 493) == 240) cout << "Nowe u hav a rel liv Magby!!!!!" << endl;
                if (1 + (rand () % 493) == 241) cout << "Nowe u hav a rel liv Miltank!!!!!" << endl;
                if (1 + (rand () % 493) == 242) cout << "Nowe u hav a rel liv Blissey!!!!!" << endl;
                if (1 + (rand () % 493) == 243) cout << "Nowe u hav a rel liv Raikou!!!!!" << endl;
                if (1 + (rand () % 493) == 244) cout << "Nowe u hav a rel liv Entei!!!!!" << endl;
                if (1 + (rand () % 493) == 245) cout << "Nowe u hav a rel liv Suicune!!!!!" << endl;
                if (1 + (rand () % 493) == 246) cout << "Nowe u hav a rel liv Larvitar!!!!!" << endl;
                if (1 + (rand () % 493) == 247) cout << "Nowe u hav a rel liv Pupitar!!!!!" << endl;
                if (1 + (rand () % 493) == 248) cout << "Nowe u hav a rel liv Tyranitar!!!!!" << endl;
                if (1 + (rand () % 493) == 249) cout << "Nowe u hav a rel liv Lugia!!!!!" << endl;
                if (1 + (rand () % 493) == 250) cout << "Nowe u hav a rel liv Ho-Oh!!!!!" << endl;
                if (1 + (rand () % 493) == 251) cout << "Nowe u hav a rel liv Celebi!!!!!" << endl;
                if (1 + (rand () % 493) == 252) cout << "Nowe u hav a rel liv Treecko!!!!!" << endl;
                if (1 + (rand () % 493) == 253) cout << "Nowe u hav a rel liv Grovyle!!!!!" << endl;
                if (1 + (rand () % 493) == 254) cout << "Nowe u hav a rel liv Sceptile!!!!!" << endl;
                if (1 + (rand () % 493) == 255) cout << "Nowe u hav a rel liv Torchic!!!!!" << endl;
                if (1 + (rand () % 493) == 256) cout << "Nowe u hav a rel liv Combusken!!!!!" << endl;
                if (1 + (rand () % 493) == 257) cout << "Nowe u hav a rel liv Blaziken!!!!!" << endl;
                if (1 + (rand () % 493) == 258) cout << "Nowe u hav a rel liv Mudkip!!!!!" << endl;
                if (1 + (rand () % 493) == 259) cout << "Nowe u hav a rel liv Marshtomp!!!!!" << endl;
                if (1 + (rand () % 493) == 260) cout << "Nowe u hav a rel liv Swampert!!!!!" << endl;
                if (1 + (rand () % 493) == 261) cout << "Nowe u hav a rel liv Poochyena!!!!!" << endl;
                if (1 + (rand () % 493) == 262) cout << "Nowe u hav a rel liv Mightyena!!!!!" << endl;
                if (1 + (rand () % 493) == 263) cout << "Nowe u hav a rel liv Zigzagoon!!!!!" << endl;
                if (1 + (rand () % 493) == 264) cout << "Nowe u hav a rel liv Linoone!!!!!" << endl;
                if (1 + (rand () % 493) == 265) cout << "Nowe u hav a rel liv Wurmple!!!!!" << endl;
                if (1 + (rand () % 493) == 266) cout << "Nowe u hav a rel liv Silcoon!!!!!" << endl;
                if (1 + (rand () % 493) == 267) cout << "Nowe u hav a rel liv Beautifly!!!!!" << endl;
                if (1 + (rand () % 493) == 268) cout << "Nowe u hav a rel liv Cascoon!!!!!" << endl;
                if (1 + (rand () % 493) == 269) cout << "Nowe u hav a rel liv Dustox!!!!!" << endl;
                if (1 + (rand () % 493) == 270) cout << "Nowe u hav a rel liv Lotad!!!!!" << endl;
                if (1 + (rand () % 493) == 271) cout << "Nowe u hav a rel liv Lombre!!!!!" << endl;
                if (1 + (rand () % 493) == 272) cout << "Nowe u hav a rel liv Ludicolo!!!!!" << endl;
                if (1 + (rand () % 493) == 273) cout << "Nowe u hav a rel liv Seedot!!!!!" << endl;
                if (1 + (rand () % 493) == 274) cout << "Nowe u hav a rel liv Nuzleaf!!!!!" << endl;
                if (1 + (rand () % 493) == 275) cout << "Nowe u hav a rel liv Shiftry!!!!!" << endl;
                if (1 + (rand () % 493) == 276) cout << "Nowe u hav a rel liv Taillow!!!!!" << endl;
                if (1 + (rand () % 493) == 277) cout << "Nowe u hav a rel liv Swellow!!!!!" << endl;
                if (1 + (rand () % 493) == 278) cout << "Nowe u hav a rel liv Wingull!!!!!" << endl;
                if (1 + (rand () % 493) == 279) cout << "Nowe u hav a rel liv Pelipper!!!!!" << endl;
                if (1 + (rand () % 493) == 280) cout << "Nowe u hav a rel liv Ralts!!!!!" << endl;
                if (1 + (rand () % 493) == 281) cout << "Nowe u hav a rel liv Kirlia!!!!!" << endl;
                if (1 + (rand () % 493) == 282) cout << "Nowe u hav a rel liv Gardevoir!!!!!" << endl;
                if (1 + (rand () % 493) == 283) cout << "Nowe u hav a rel liv Surskit!!!!!" << endl;
                if (1 + (rand () % 493) == 284) cout << "Nowe u hav a rel liv Masquerain!!!!!" << endl;
                if (1 + (rand () % 493) == 285) cout << "Nowe u hav a rel liv Shroomish!!!!!" << endl;
                if (1 + (rand () % 493) == 286) cout << "Nowe u hav a rel liv Breloom!!!!!" << endl;
                if (1 + (rand () % 493) == 287) cout << "Nowe u hav a rel liv Slakoth!!!!!" << endl;
                if (1 + (rand () % 493) == 288) cout << "Nowe u hav a rel liv Vigoroth!!!!!" << endl;
                if (1 + (rand () % 493) == 289) cout << "Nowe u hav a rel liv Slaking!!!!!" << endl;
                if (1 + (rand () % 493) == 290) cout << "Nowe u hav a rel liv Nincada!!!!!" << endl;
                if (1 + (rand () % 493) == 291) cout << "Nowe u hav a rel liv Ninjask!!!!!" << endl;
                if (1 + (rand () % 493) == 292) cout << "Nowe u hav a rel liv Shedinja!!!!!" << endl;
                if (1 + (rand () % 493) == 293) cout << "Nowe u hav a rel liv Whismur!!!!!" << endl;
                if (1 + (rand () % 493) == 294) cout << "Nowe u hav a rel liv Loudred!!!!!" << endl;
                if (1 + (rand () % 493) == 295) cout << "Nowe u hav a rel liv Exploud!!!!!" << endl;
                if (1 + (rand () % 493) == 296) cout << "Nowe u hav a rel liv Makuhita!!!!!" << endl;
                if (1 + (rand () % 493) == 297) cout << "Nowe u hav a rel liv Hariyama!!!!!" << endl;
                if (1 + (rand () % 493) == 298) cout << "Nowe u hav a rel liv Azurill!!!!!" << endl;
                if (1 + (rand () % 493) == 299) cout << "Nowe u hav a rel liv Nosepass!!!!!" << endl;
                if (1 + (rand () % 493) == 300) cout << "Nowe u hav a rel liv Skitty!!!!!" << endl;
                if (1 + (rand () % 493) == 301) cout << "Nowe u hav a rel liv Delcatty!!!!!" << endl;
                if (1 + (rand () % 493) == 302) cout << "Nowe u hav a rel liv Sableye!!!!!" << endl;
                if (1 + (rand () % 493) == 303) cout << "Nowe u hav a rel liv Mawile!!!!!" << endl;
                if (1 + (rand () % 493) == 304) cout << "Nowe u hav a rel liv Aron!!!!!" << endl;
                if (1 + (rand () % 493) == 305) cout << "Nowe u hav a rel liv Lairon!!!!!" << endl;
                if (1 + (rand () % 493) == 306) cout << "Nowe u hav a rel liv Aggron!!!!!" << endl;
                if (1 + (rand () % 493) == 307) cout << "Nowe u hav a rel liv Meditite!!!!!" << endl;
                if (1 + (rand () % 493) == 308) cout << "Nowe u hav a rel liv Medicham!!!!!" << endl;
                if (1 + (rand () % 493) == 309) cout << "Nowe u hav a rel liv Electrike!!!!!" << endl;
                if (1 + (rand () % 493) == 310) cout << "Nowe u hav a rel liv Manectric!!!!!" << endl;
                if (1 + (rand () % 493) == 311) cout << "Nowe u hav a rel liv Plusle!!!!!" << endl;
                if (1 + (rand () % 493) == 312) cout << "Nowe u hav a rel liv Minun!!!!!" << endl;
                if (1 + (rand () % 493) == 313) cout << "Nowe u hav a rel liv Volbeat!!!!!" << endl;
                if (1 + (rand () % 493) == 314) cout << "Nowe u hav a rel liv Illumise!!!!!" << endl;
                if (1 + (rand () % 493) == 315) cout << "Nowe u hav a rel liv Roselia!!!!!" << endl;
                if (1 + (rand () % 493) == 316) cout << "Nowe u hav a rel liv Gulpin!!!!!" << endl;
                if (1 + (rand () % 493) == 317) cout << "Nowe u hav a rel liv Swalot!!!!!" << endl;
                if (1 + (rand () % 493) == 318) cout << "Nowe u hav a rel liv Carvanha!!!!!" << endl;
                if (1 + (rand () % 493) == 319) cout << "Nowe u hav a rel liv Sharpedo!!!!!" << endl;
                if (1 + (rand () % 493) == 320) cout << "Nowe u hav a rel liv Wailmer!!!!!" << endl;
                if (1 + (rand () % 493) == 321) cout << "Nowe u hav a rel liv Wailord!!!!!" << endl;
                if (1 + (rand () % 493) == 322) cout << "Nowe u hav a rel liv Numel!!!!!" << endl;
                if (1 + (rand () % 493) == 323) cout << "Nowe u hav a rel liv Camerupt!!!!!" << endl;
                if (1 + (rand () % 493) == 324) cout << "Nowe u hav a rel liv Torkoal!!!!!" << endl;
                if (1 + (rand () % 493) == 325) cout << "Nowe u hav a rel liv Spoink!!!!!" << endl;
                if (1 + (rand () % 493) == 326) cout << "Nowe u hav a rel liv Grumpig!!!!!" << endl;
                if (1 + (rand () % 493) == 327) cout << "Nowe u hav a rel liv Spinda!!!!!" << endl;
                if (1 + (rand () % 493) == 328) cout << "Nowe u hav a rel liv Trapinch!!!!!" << endl;
                if (1 + (rand () % 493) == 329) cout << "Nowe u hav a rel liv Vibrava!!!!!" << endl;
                if (1 + (rand () % 493) == 330) cout << "Nowe u hav a rel liv Flygon!!!!!" << endl;
                if (1 + (rand () % 493) == 331) cout << "Nowe u hav a rel liv Cacnea!!!!!" << endl;
                if (1 + (rand () % 493) == 332) cout << "Nowe u hav a rel liv Cacturne!!!!!" << endl;
                if (1 + (rand () % 493) == 333) cout << "Nowe u hav a rel liv Swablu!!!!!" << endl;
                if (1 + (rand () % 493) == 334) cout << "Nowe u hav a rel liv Altaria!!!!!" << endl;
                if (1 + (rand () % 493) == 335) cout << "Nowe u hav a rel liv Zangoose!!!!!" << endl;
                if (1 + (rand () % 493) == 336) cout << "Nowe u hav a rel liv Seviper!!!!!" << endl;
                if (1 + (rand () % 493) == 337) cout << "Nowe u hav a rel liv Lunatone!!!!!" << endl;
                if (1 + (rand () % 493) == 338) cout << "Nowe u hav a rel liv Solrock!!!!!" << endl;
                if (1 + (rand () % 493) == 339) cout << "Nowe u hav a rel liv Barboach!!!!!" << endl;
                if (1 + (rand () % 493) == 340) cout << "Nowe u hav a rel liv Whiscash!!!!!" << endl;
                if (1 + (rand () % 493) == 341) cout << "Nowe u hav a rel liv Corphish!!!!!" << endl;
                if (1 + (rand () % 493) == 342) cout << "Nowe u hav a rel liv Crawdaunt!!!!!" << endl;
                if (1 + (rand () % 493) == 343) cout << "Nowe u hav a rel liv Baltoy!!!!!" << endl;
                if (1 + (rand () % 493) == 344) cout << "Nowe u hav a rel liv Claydol!!!!!" << endl;
                if (1 + (rand () % 493) == 345) cout << "Nowe u hav a rel liv Lileep!!!!!" << endl;
                if (1 + (rand () % 493) == 346) cout << "Nowe u hav a rel liv Cradily!!!!!" << endl;
                if (1 + (rand () % 493) == 347) cout << "Nowe u hav a rel liv Anorith!!!!!" << endl;
                if (1 + (rand () % 493) == 348) cout << "Nowe u hav a rel liv Armaldo!!!!!" << endl;
                if (1 + (rand () % 493) == 349) cout << "Nowe u hav a rel liv Feebas!!!!!" << endl;
                if (1 + (rand () % 493) == 350) cout << "Nowe u hav a rel liv Milotic!!!!!" << endl;
                if (1 + (rand () % 493) == 351) cout << "Nowe u hav a rel liv Castform!!!!!" << endl;
                if (1 + (rand () % 493) == 352) cout << "Nowe u hav a rel liv Kecleon!!!!!" << endl;
                if (1 + (rand () % 493) == 353) cout << "Nowe u hav a rel liv Shuppet!!!!!" << endl;
                if (1 + (rand () % 493) == 354) cout << "Nowe u hav a rel liv Banette!!!!!" << endl;
                if (1 + (rand () % 493) == 355) cout << "Nowe u hav a rel liv Duskull!!!!!" << endl;
                if (1 + (rand () % 493) == 356) cout << "Nowe u hav a rel liv Dusclops!!!!!" << endl;
                if (1 + (rand () % 493) == 357) cout << "Nowe u hav a rel liv Tropius!!!!!" << endl;
                if (1 + (rand () % 493) == 358) cout << "Nowe u hav a rel liv Chimecho!!!!!" << endl;
                if (1 + (rand () % 493) == 359) cout << "Nowe u hav a rel liv Absol!!!!!" << endl;
                if (1 + (rand () % 493) == 360) cout << "Nowe u hav a rel liv Wynaut!!!!!" << endl;
                if (1 + (rand () % 493) == 361) cout << "Nowe u hav a rel liv Snorunt!!!!!" << endl;
                if (1 + (rand () % 493) == 362) cout << "Nowe u hav a rel liv Glalie!!!!!" << endl;
                if (1 + (rand () % 493) == 363) cout << "Nowe u hav a rel liv Spheal!!!!!" << endl;
                if (1 + (rand () % 493) == 364) cout << "Nowe u hav a rel liv Sealeo!!!!!" << endl;
                if (1 + (rand () % 493) == 365) cout << "Nowe u hav a rel liv Walrein!!!!!" << endl;
                if (1 + (rand () % 493) == 366) cout << "Nowe u hav a rel liv Clamperl!!!!!" << endl;
                if (1 + (rand () % 493) == 367) cout << "Nowe u hav a rel liv Huntail!!!!!" << endl;
                if (1 + (rand () % 493) == 368) cout << "Nowe u hav a rel liv Gorebyss!!!!!" << endl;
                if (1 + (rand () % 493) == 369) cout << "Nowe u hav a rel liv Relicanth!!!!!" << endl;
                if (1 + (rand () % 493) == 370) cout << "Nowe u hav a rel liv Luvdisc!!!!!" << endl;
                if (1 + (rand () % 493) == 371) cout << "Nowe u hav a rel liv Bagon!!!!!" << endl;
                if (1 + (rand () % 493) == 372) cout << "Nowe u hav a rel liv Shelgon!!!!!" << endl;
                if (1 + (rand () % 493) == 373) cout << "Nowe u hav a rel liv Salamence!!!!!" << endl;
                if (1 + (rand () % 493) == 374) cout << "Nowe u hav a rel liv Beldum!!!!!" << endl;
                if (1 + (rand () % 493) == 375) cout << "Nowe u hav a rel liv Metang!!!!!" << endl;
                if (1 + (rand () % 493) == 376) cout << "Nowe u hav a rel liv Metagross!!!!!" << endl;
                if (1 + (rand () % 493) == 377) cout << "Nowe u hav a rel liv Regirock!!!!!" << endl;
                if (1 + (rand () % 493) == 378) cout << "Nowe u hav a rel liv Regice!!!!!" << endl;
                if (1 + (rand () % 493) == 379) cout << "Nowe u hav a rel liv Registeel!!!!!" << endl;
                if (1 + (rand () % 493) == 380) cout << "Nowe u hav a rel liv Latias!!!!!" << endl;
                if (1 + (rand () % 493) == 381) cout << "Nowe u hav a rel liv Latios!!!!!" << endl;
                if (1 + (rand () % 493) == 382) cout << "Nowe u hav a rel liv Kyogre!!!!!" << endl;
                if (1 + (rand () % 493) == 383) cout << "Nowe u hav a rel liv Groudon!!!!!" << endl;
                if (1 + (rand () % 493) == 384) cout << "Nowe u hav a rel liv Rayquaza!!!!!" << endl;
                if (1 + (rand () % 493) == 385) cout << "Nowe u hav a rel liv Jirachi!!!!!" << endl;
                if (1 + (rand () % 493) == 386) cout << "Nowe u hav a rel liv Deoxys!!!!!" << endl;
                if (1 + (rand () % 493) == 387) cout << "Nowe u hav a rel liv Turtwig!!!!!" << endl;
                if (1 + (rand () % 493) == 388) cout << "Nowe u hav a rel liv Grotle!!!!!" << endl;
                if (1 + (rand () % 493) == 389) cout << "Nowe u hav a rel liv Torterra!!!!!" << endl;
                if (1 + (rand () % 493) == 390) cout << "Nowe u hav a rel liv Chimchar!!!!!" << endl;
                if (1 + (rand () % 493) == 391) cout << "Nowe u hav a rel liv Monferno!!!!!" << endl;
                if (1 + (rand () % 493) == 392) cout << "Nowe u hav a rel liv Infernape!!!!!" << endl;
                if (1 + (rand () % 493) == 393) cout << "Nowe u hav a rel liv Piplup!!!!!" << endl;
                if (1 + (rand () % 493) == 394) cout << "Nowe u hav a rel liv Prinplup!!!!!" << endl;
                if (1 + (rand () % 493) == 395) cout << "Nowe u hav a rel liv Empoleon!!!!!" << endl;
                if (1 + (rand () % 493) == 396) cout << "Nowe u hav a rel liv Starly!!!!!" << endl;
                if (1 + (rand () % 493) == 397) cout << "Nowe u hav a rel liv Staravia!!!!!" << endl;
                if (1 + (rand () % 493) == 398) cout << "Nowe u hav a rel liv Staraptor!!!!!" << endl;
                if (1 + (rand () % 493) == 399) cout << "Nowe u hav a rel liv Bidoof!!!!!" << endl;
                if (1 + (rand () % 493) == 400) cout << "Nowe u hav a rel liv Bibarel!!!!!" << endl;
                if (1 + (rand () % 493) == 401) cout << "Nowe u hav a rel liv Kricketot!!!!!" << endl;
                if (1 + (rand () % 493) == 402) cout << "Nowe u hav a rel liv Kricketune!!!!!" << endl;
                if (1 + (rand () % 493) == 403) cout << "Nowe u hav a rel liv Shinx!!!!!" << endl;
                if (1 + (rand () % 493) == 404) cout << "Nowe u hav a rel liv Luxio!!!!!" << endl;
                if (1 + (rand () % 493) == 405) cout << "Nowe u hav a rel liv Luxray!!!!!" << endl;
                if (1 + (rand () % 493) == 406) cout << "Nowe u hav a rel liv Budew!!!!!" << endl;
                if (1 + (rand () % 493) == 407) cout << "Nowe u hav a rel liv Roserade!!!!!" << endl;
                if (1 + (rand () % 493) == 408) cout << "Nowe u hav a rel liv Cranidos!!!!!" << endl;
                if (1 + (rand () % 493) == 409) cout << "Nowe u hav a rel liv Rampardos!!!!!" << endl;
                if (1 + (rand () % 493) == 410) cout << "Nowe u hav a rel liv Shieldon!!!!!" << endl;
                if (1 + (rand () % 493) == 411) cout << "Nowe u hav a rel liv Bastiodon!!!!!" << endl;
                if (1 + (rand () % 493) == 412) cout << "Nowe u hav a rel liv Burmy!!!!!" << endl;
                if (1 + (rand () % 493) == 413) cout << "Nowe u hav a rel liv Wormadam!!!!!" << endl;
                if (1 + (rand () % 493) == 414) cout << "Nowe u hav a rel liv Mothim!!!!!" << endl;
                if (1 + (rand () % 493) == 415) cout << "Nowe u hav a rel liv Combee!!!!!" << endl;
                if (1 + (rand () % 493) == 416) cout << "Nowe u hav a rel liv Vespiquen!!!!!" << endl;
                if (1 + (rand () % 493) == 417) cout << "Nowe u hav a rel liv Pachirisu!!!!!" << endl;
                if (1 + (rand () % 493) == 418) cout << "Nowe u hav a rel liv Buizel!!!!!" << endl;
                if (1 + (rand () % 493) == 419) cout << "Nowe u hav a rel liv Floatzel!!!!!" << endl;
                if (1 + (rand () % 493) == 420) cout << "Nowe u hav a rel liv Cherubi!!!!!" << endl;
                if (1 + (rand () % 493) == 421) cout << "Nowe u hav a rel liv Cherrim!!!!!" << endl;
                if (1 + (rand () % 493) == 422) cout << "Nowe u hav a rel liv Shellos!!!!!" << endl;
                if (1 + (rand () % 493) == 423) cout << "Nowe u hav a rel liv Gastrodon!!!!!" << endl;
                if (1 + (rand () % 493) == 424) cout << "Nowe u hav a rel liv Ambipom!!!!!" << endl;
                if (1 + (rand () % 493) == 425) cout << "Nowe u hav a rel liv Drifloon!!!!!" << endl;
                if (1 + (rand () % 493) == 426) cout << "Nowe u hav a rel liv Drifblim!!!!!" << endl;
                if (1 + (rand () % 493) == 427) cout << "Nowe u hav a rel liv Buneary!!!!!" << endl;
                if (1 + (rand () % 493) == 428) cout << "Nowe u hav a rel liv Lopunny!!!!!" << endl;
                if (1 + (rand () % 493) == 429) cout << "Nowe u hav a rel liv Mismagius!!!!!" << endl;
                if (1 + (rand () % 493) == 430) cout << "Nowe u hav a rel liv Honchkrow!!!!!" << endl;
                if (1 + (rand () % 493) == 431) cout << "Nowe u hav a rel liv Glameow!!!!!" << endl;
                if (1 + (rand () % 493) == 432) cout << "Nowe u hav a rel liv Purugly!!!!!" << endl;
                if (1 + (rand () % 493) == 433) cout << "Nowe u hav a rel liv Chingling!!!!!" << endl;
                if (1 + (rand () % 493) == 434) cout << "Nowe u hav a rel liv Stunky!!!!!" << endl;
                if (1 + (rand () % 493) == 435) cout << "Nowe u hav a rel liv Skuntank!!!!!" << endl;
                if (1 + (rand () % 493) == 436) cout << "Nowe u hav a rel liv Bronzor!!!!!" << endl;
                if (1 + (rand () % 493) == 437) cout << "Nowe u hav a rel liv Bronzong!!!!!" << endl;
                if (1 + (rand () % 493) == 438) cout << "Nowe u hav a rel liv Bonsly!!!!!" << endl;
                if (1 + (rand () % 493) == 439) cout << "Nowe u hav a rel liv Mime Jr.!!!!!" << endl;
                if (1 + (rand () % 493) == 440) cout << "Nowe u hav a rel liv Happiny!!!!!" << endl;
                if (1 + (rand () % 493) == 441) cout << "Nowe u hav a rel liv Chatot!!!!!" << endl;
                if (1 + (rand () % 493) == 442) cout << "Nowe u hav a rel liv Spiritomb!!!!!" << endl;
                if (1 + (rand () % 493) == 443) cout << "Nowe u hav a rel liv Gible!!!!!" << endl;
                if (1 + (rand () % 493) == 444) cout << "Nowe u hav a rel liv Gabite!!!!!" << endl;
                if (1 + (rand () % 493) == 445) cout << "Nowe u hav a rel liv Garchomp!!!!!" << endl;
                if (1 + (rand () % 493) == 446) cout << "Nowe u hav a rel liv Munchlax!!!!!" << endl;
                if (1 + (rand () % 493) == 447) cout << "Nowe u hav a rel liv Riolu!!!!!" << endl;
                if (1 + (rand () % 493) == 448) cout << "Nowe u hav a rel liv Lucario!!!!!" << endl;
                if (1 + (rand () % 493) == 449) cout << "Nowe u hav a rel liv Hippopotas!!!!!" << endl;
                if (1 + (rand () % 493) == 450) cout << "Nowe u hav a rel liv Hippowdon!!!!!" << endl;
                if (1 + (rand () % 493) == 451) cout << "Nowe u hav a rel liv Skorupi!!!!!" << endl;
                if (1 + (rand () % 493) == 452) cout << "Nowe u hav a rel liv Drapion!!!!!" << endl;
                if (1 + (rand () % 493) == 453) cout << "Nowe u hav a rel liv Croagunk!!!!!" << endl;
                if (1 + (rand () % 493) == 454) cout << "Nowe u hav a rel liv Toxicroak!!!!!" << endl;
                if (1 + (rand () % 493) == 455) cout << "Nowe u hav a rel liv Carnivine!!!!!" << endl;
                if (1 + (rand () % 493) == 456) cout << "Nowe u hav a rel liv Finneon!!!!!" << endl;
                if (1 + (rand () % 493) == 457) cout << "Nowe u hav a rel liv Lumineon!!!!!" << endl;
                if (1 + (rand () % 493) == 458) cout << "Nowe u hav a rel liv Mantyke!!!!!" << endl;
                if (1 + (rand () % 493) == 459) cout << "Nowe u hav a rel liv Snover!!!!!" << endl;
                if (1 + (rand () % 493) == 460) cout << "Nowe u hav a rel liv Abomasnow!!!!!" << endl;
                if (1 + (rand () % 493) == 461) cout << "Nowe u hav a rel liv Weavile!!!!!" << endl;
                if (1 + (rand () % 493) == 462) cout << "Nowe u hav a rel liv Magnezone!!!!!" << endl;
                if (1 + (rand () % 493) == 463) cout << "Nowe u hav a rel liv Lickilicky!!!!!" << endl;
                if (1 + (rand () % 493) == 464) cout << "Nowe u hav a rel liv Rhyperior!!!!!" << endl;
                if (1 + (rand () % 493) == 465) cout << "Nowe u hav a rel liv Tangrowth!!!!!" << endl;
                if (1 + (rand () % 493) == 466) cout << "Nowe u hav a rel liv Electivire!!!!!" << endl;
                if (1 + (rand () % 493) == 467) cout << "Nowe u hav a rel liv Magmortar!!!!!" << endl;
                if (1 + (rand () % 493) == 468) cout << "Nowe u hav a rel liv Togekiss!!!!!" << endl;
                if (1 + (rand () % 493) == 469) cout << "Nowe u hav a rel liv Yanmega!!!!!" << endl;
                if (1 + (rand () % 493) == 470) cout << "Nowe u hav a rel liv Leafeon!!!!!" << endl;
                if (1 + (rand () % 493) == 471) cout << "Nowe u hav a rel liv Glaceon!!!!!" << endl;
                if (1 + (rand () % 493) == 472) cout << "Nowe u hav a rel liv Gliscor!!!!!" << endl;
                if (1 + (rand () % 493) == 473) cout << "Nowe u hav a rel liv Mamoswine!!!!!" << endl;
                if (1 + (rand () % 493) == 474) cout << "Nowe u hav a rel liv Porygon-Z!!!!!" << endl;
                if (1 + (rand () % 493) == 475) cout << "Nowe u hav a rel liv Gallade!!!!!" << endl;
                if (1 + (rand () % 493) == 476) cout << "Nowe u hav a rel liv Probopass!!!!!" << endl;
                if (1 + (rand () % 493) == 477) cout << "Nowe u hav a rel liv Dusknoir!!!!!" << endl;
                if (1 + (rand () % 493) == 478) cout << "Nowe u hav a rel liv Froslass!!!!!" << endl;
                if (1 + (rand () % 493) == 479) cout << "Nowe u hav a rel liv Rotom!!!!!" << endl;
                if (1 + (rand () % 493) == 480) cout << "Nowe u hav a rel liv Uxie!!!!!" << endl;
                if (1 + (rand () % 493) == 481) cout << "Nowe u hav a rel liv Mesprit!!!!!" << endl;
                if (1 + (rand () % 493) == 482) cout << "Nowe u hav a rel liv Azelf!!!!!" << endl;
                if (1 + (rand () % 493) == 483) cout << "Nowe u hav a rel liv Dialga!!!!!" << endl;
                if (1 + (rand () % 493) == 484) cout << "Nowe u hav a rel liv Palkia!!!!!" << endl;
                if (1 + (rand () % 493) == 485) cout << "Nowe u hav a rel liv Heatran!!!!!" << endl;
                if (1 + (rand () % 493) == 486) cout << "Nowe u hav a rel liv Regigigas!!!!!" << endl;
                if (1 + (rand () % 493) == 487) cout << "Nowe u hav a rel liv Giratina!!!!!" << endl;
                if (1 + (rand () % 493) == 488) cout << "Nowe u hav a rel liv Cresselia!!!!!" << endl;
                if (1 + (rand () % 493) == 489) cout << "Nowe u hav a rel liv Phione!!!!!" << endl;
                if (1 + (rand () % 493) == 490) cout << "Nowe u hav a rel liv Manaphy!!!!!" << endl;
                if (1 + (rand () % 493) == 491) cout << "Nowe u hav a rel liv Darkrai!!!!!" << endl;
                if (1 + (rand () % 493) == 492) cout << "Nowe u hav a rel liv Shaymin!!!!!" << endl;
                if (1 + (rand () % 493) == 493) cout << "Nowe u hav a rel liv Arceus!!!!!" << endl;
}


		gfxFlushBuffers();
		gfxSwapBuffers();
		gspWaitForVBlank();
		if (kDown & KEY_B) break;
		if (A == 31500){
		memset(param, 0, sizeof(param));
		memset(hmac, 0, sizeof(hmac));
		APT_PrepareToDoApplicationJump(0, shopID, 0);
		APT_DoApplicationJump(param, sizeof(param), hmac); } }

	gfxExit();
	return 0;
}
