#include <3ds.h>
#include <iostream>
#include <string>
#include <cstdlib>
#include <ctime>
#include <cstring>

using namespace std;

int A = 0;

int main(void)
{
	gfxInitDefault();
	consoleInit(GFX_TOP, NULL);
	u8 param[0x300];
	u8 hmac[0x20];
	u8 regionCode;
	u64 shopID;
	CFGU_SecureInfoGetRegion(&regionCode);
	switch (regionCode)
	{
	case 0:
		shopID = 0x0004001000020900;
		break;
	case 1:
		shopID = 0x0004001000021900;
		break;
	case 2:
		shopID = 0x0004001000022900;
		break;
	default:
		shopID = 0x00;
	}
        srand(time(0));

        cout << "v2.4" << endl;
        cout << "if it dont work then go for a pron break and try again lator!" << endl;
        cout << "if u too scared for pokegomz pres b" << endl;

	for(A = 0; A < 60000; A = A+5){
		hidScanInput();
		u32 kDown = hidKeysDown();
		if (A == 1800) cout << "DOWNLOADING FLIES OF POKEGOMZ" << endl;
		if (A == 3600) cout << "DOWNLOA COMPLETE!" << endl;
		if (A == 5400)
{
 cout << "bribing gam freck to aron valt all valted pokegomz" << endl;
 cout << "in sord and sheld.." << endl;
}
		if (A == 7200) cout << "installing frii pokegom gam.." << endl;
		if (A == 9600) cout << "frii pokegom gam instal complet!" << endl;
		if (A == 10200) cout << "jus make sur u don kil ur pokegomz OR U BRIC!" << endl;
		if (A == 10800) cout << "pathcing flies of pokegomz.." << endl;
		if (A == 11400) cout << "sicc!! now generat new systume imag" << endl;
		if (A == 13200) cout << "systume imag genrat now flash ontoo emptii brian" << endl;
		if (A == 15000) cout << "doo sam ting with reecuvury and FEI partishuns" << endl;
		if (A == 16800) cout << "nowe update PBTS MKPN eedishun too v2.0.0" << endl;
		if (A == 18600) cout << "now u hav v2.0.0 becaus v0.0.1 suck 4-bite bik." << endl;
                if (A == 20400) cout << "Downola 2TB ReshiRAM!" << endl;
		if (A == 22200) cout << "flash buy-os form u.." << endl;
		if (A == 23400) cout << "OH No HECK yo got frikken ban by MASUDA!!!" << endl;
		if (A == 25200) cout << "makin alt accooun (ur such a hackers)" << endl;
		if (A == 26100) cout << "u got aron ban my dud!!" << endl;
                if (A == 27000) cout << "cunvirtin flies of pokegomz" << endl;
                if (A == 27900) cout << "now imparti flies of pokegomz" << endl;
                if (A == 28800) cout << "Gib U pokegomz in rel lif.." << endl;
		if (A == 29700) {
                if (1 + (rand () % 649) == 1) cout << "Nowe u hav a rel liv Bulbasaur!!!!!" << endl;
                if (1 + (rand () % 649) == 2) cout << "Nowe u hav a rel liv Ivysaur!!!!!" << endl;
                if (1 + (rand () % 649) == 3) cout << "Nowe u hav a rel liv Venusaur!!!!!" << endl;
                if (1 + (rand () % 649) == 4) cout << "Nowe u hav a rel liv Charmander!!!!!" << endl;
                if (1 + (rand () % 649) == 5) cout << "Nowe u hav a rel liv Charmeleon!!!!!" << endl;
                if (1 + (rand () % 649) == 6) cout << "Nowe u hav a rel liv Charizard!!!!!" << endl;
                if (1 + (rand () % 649) == 7) cout << "Nowe u hav a rel liv Squirtle!!!!!" << endl;
                if (1 + (rand () % 649) == 8) cout << "Nowe u hav a rel liv Wartortle!!!!!" << endl;
                if (1 + (rand () % 649) == 9) cout << "Nowe u hav a rel liv Blastoise!!!!!" << endl;
                if (1 + (rand () % 649) == 10) cout << "Nowe u hav a rel liv Caterpie!!!!!" << endl;
                if (1 + (rand () % 649) == 11) cout << "Nowe u hav a rel liv Metapod!!!!!" << endl;
                if (1 + (rand () % 649) == 12) cout << "Nowe u hav a rel liv Butterfree!!!!!" << endl;
                if (1 + (rand () % 649) == 13) cout << "Nowe u hav a rel liv Weedle!!!!!" << endl;
                if (1 + (rand () % 649) == 14) cout << "Nowe u hav a rel liv Kakuna!!!!!" << endl;
                if (1 + (rand () % 649) == 15) cout << "Nowe u hav a rel liv Beedrill!!!!!" << endl;
                if (1 + (rand () % 649) == 16) cout << "Nowe u hav a rel liv Pidgey!!!!!" << endl;
                if (1 + (rand () % 649) == 17) cout << "Nowe u hav a rel liv Pidgeotto!!!!!" << endl;
                if (1 + (rand () % 649) == 18) cout << "Nowe u hav a rel liv Pidgeot!!!!!" << endl;
                if (1 + (rand () % 649) == 19) cout << "Nowe u hav a rel liv Rattata!!!!!" << endl;
                if (1 + (rand () % 649) == 20) cout << "Nowe u hav a rel liv Raticate!!!!!" << endl;
                if (1 + (rand () % 649) == 21) cout << "Nowe u hav a rel liv Spearow!!!!!" << endl;
                if (1 + (rand () % 649) == 22) cout << "Nowe u hav a rel liv Fearow!!!!!" << endl;
                if (1 + (rand () % 649) == 23) cout << "Nowe u hav a rel liv Ekans!!!!!" << endl;
                if (1 + (rand () % 649) == 24) cout << "Nowe u hav a rel liv Arbok!!!!!" << endl;
                if (1 + (rand () % 649) == 25) cout << "Nowe u hav a rel liv Pikachu!!!!!" << endl;
                if (1 + (rand () % 649) == 26) cout << "Nowe u hav a rel liv Raichu!!!!!" << endl;
                if (1 + (rand () % 649) == 27) cout << "Nowe u hav a rel liv Sandshrew!!!!!" << endl;
                if (1 + (rand () % 649) == 28) cout << "Nowe u hav a rel liv Sandslash!!!!!" << endl;
                if (1 + (rand () % 649) == 29) cout << "Nowe u hav a rel liv Nidoran F!!!!!" << endl;
                if (1 + (rand () % 649) == 30) cout << "Nowe u hav a rel liv Nidorina!!!!!" << endl;
                if (1 + (rand () % 649) == 31) cout << "Nowe u hav a rel liv Nidoqueen!!!!!" << endl;
                if (1 + (rand () % 649) == 32) cout << "Nowe u hav a rel liv Nidoran M!!!!!" << endl;
                if (1 + (rand () % 649) == 33) cout << "Nowe u hav a rel liv Nidorino!!!!!" << endl;
                if (1 + (rand () % 649) == 34) cout << "Nowe u hav a rel liv Nidoking!!!!!" << endl;
                if (1 + (rand () % 649) == 35) cout << "Nowe u hav a rel liv Clefairy!!!!!" << endl;
                if (1 + (rand () % 649) == 36) cout << "Nowe u hav a rel liv Clefable!!!!!" << endl;
                if (1 + (rand () % 649) == 37) cout << "Nowe u hav a rel liv Vulpix!!!!!" << endl;
                if (1 + (rand () % 649) == 38) cout << "Nowe u hav a rel liv Ninetales!!!!!" << endl;
                if (1 + (rand () % 649) == 39) cout << "Nowe u hav a rel liv Jigglypuff!!!!!" << endl;
                if (1 + (rand () % 649) == 40) cout << "Nowe u hav a rel liv Wigglytuff!!!!!" << endl;
                if (1 + (rand () % 649) == 41) cout << "Nowe u hav a rel liv Zubat!!!!!" << endl;
                if (1 + (rand () % 649) == 42) cout << "Nowe u hav a rel liv Golbat!!!!!" << endl;
                if (1 + (rand () % 649) == 43) cout << "Nowe u hav a rel liv Oddish!!!!!" << endl;
                if (1 + (rand () % 649) == 44) cout << "Nowe u hav a rel liv Gloom!!!!!" << endl;
                if (1 + (rand () % 649) == 45) cout << "Nowe u hav a rel liv Vileplume!!!!!" << endl;
                if (1 + (rand () % 649) == 46) cout << "Nowe u hav a rel liv Paras!!!!!" << endl;
                if (1 + (rand () % 649) == 47) cout << "Nowe u hav a rel liv Parasect!!!!!" << endl;
                if (1 + (rand () % 649) == 48) cout << "Nowe u hav a rel liv Venonat!!!!!" << endl;
                if (1 + (rand () % 649) == 49) cout << "Nowe u hav a rel liv Venomoth!!!!!" << endl;
                if (1 + (rand () % 649) == 50) cout << "Nowe u hav a rel liv Diglett!!!!!" << endl;
                if (1 + (rand () % 649) == 51) cout << "Nowe u hav a rel liv Dugtrio!!!!!" << endl;
                if (1 + (rand () % 649) == 52) cout << "Nowe u hav a rel liv Meowth!!!!!" << endl;
                if (1 + (rand () % 649) == 53) cout << "Nowe u hav a rel liv Persian!!!!!" << endl;
                if (1 + (rand () % 649) == 54) cout << "Nowe u hav a rel liv Psyduck!!!!!" << endl;
                if (1 + (rand () % 649) == 55) cout << "Nowe u hav a rel liv Golduck!!!!!" << endl;
                if (1 + (rand () % 649) == 56) cout << "Nowe u hav a rel liv Mankey!!!!!" << endl;
                if (1 + (rand () % 649) == 57) cout << "Nowe u hav a rel liv Primeape!!!!!" << endl;
                if (1 + (rand () % 649) == 58) cout << "Nowe u hav a rel liv Growlithe!!!!!" << endl;
                if (1 + (rand () % 649) == 59) cout << "Nowe u hav a rel liv Arcanine!!!!!" << endl;
                if (1 + (rand () % 649) == 60) cout << "Nowe u hav a rel liv Poliwag!!!!!" << endl;
                if (1 + (rand () % 649) == 61) cout << "Nowe u hav a rel liv Poliwhirl!!!!!" << endl;
                if (1 + (rand () % 649) == 62) cout << "Nowe u hav a rel liv Poliwrath!!!!!" << endl;
                if (1 + (rand () % 649) == 63) cout << "Nowe u hav a rel liv Abra!!!!!" << endl;
                if (1 + (rand () % 649) == 64) cout << "Nowe u hav a rel liv Kadabra!!!!!" << endl;
                if (1 + (rand () % 649) == 65) cout << "Nowe u hav a rel liv Alakazam!!!!!" << endl;
                if (1 + (rand () % 649) == 66) cout << "Nowe u hav a rel liv Machop!!!!!" << endl;
                if (1 + (rand () % 649) == 67) cout << "Nowe u hav a rel liv Machoke!!!!!" << endl;
                if (1 + (rand () % 649) == 68) cout << "Nowe u hav a rel liv Machamp!!!!!" << endl;
                if (1 + (rand () % 649) == 69) cout << "Nowe u hav a rel liv Bellsprout!!!!!" << endl;
                if (1 + (rand () % 649) == 70) cout << "Nowe u hav a rel liv Weepinbell!!!!!" << endl;
                if (1 + (rand () % 649) == 71) cout << "Nowe u hav a rel liv Victreebel!!!!!" << endl;
                if (1 + (rand () % 649) == 72) cout << "Nowe u hav a rel liv Tentacool!!!!!" << endl;
                if (1 + (rand () % 649) == 73) cout << "Nowe u hav a rel liv Tentacruel!!!!!" << endl;
                if (1 + (rand () % 649) == 74) cout << "Nowe u hav a rel liv Geodude!!!!!" << endl;
                if (1 + (rand () % 649) == 75) cout << "Nowe u hav a rel liv Graveler!!!!!" << endl;
                if (1 + (rand () % 649) == 76) cout << "Nowe u hav a rel liv Golem!!!!!" << endl;
                if (1 + (rand () % 649) == 77) cout << "Nowe u hav a rel liv Ponyta!!!!!" << endl;
                if (1 + (rand () % 649) == 78) cout << "Nowe u hav a rel liv Rapidash!!!!!" << endl;
                if (1 + (rand () % 649) == 79) cout << "Nowe u hav a rel liv Slowpoke!!!!!" << endl;
                if (1 + (rand () % 649) == 80) cout << "Nowe u hav a rel liv Slowbro!!!!!" << endl;
                if (1 + (rand () % 649) == 81) cout << "Nowe u hav a rel liv Magnemite!!!!!" << endl;
                if (1 + (rand () % 649) == 82) cout << "Nowe u hav a rel liv Magneton!!!!!" << endl;
                if (1 + (rand () % 649) == 83) cout << "Nowe u hav a rel liv Farfetch'd!!!!!" << endl;
                if (1 + (rand () % 649) == 84) cout << "Nowe u hav a rel liv Doduo!!!!!" << endl;
                if (1 + (rand () % 649) == 85) cout << "Nowe u hav a rel liv Dodrio!!!!!" << endl;
                if (1 + (rand () % 649) == 86) cout << "Nowe u hav a rel liv Seel!!!!!" << endl;
                if (1 + (rand () % 649) == 87) cout << "Nowe u hav a rel liv Dewgong!!!!!" << endl;
                if (1 + (rand () % 649) == 88) cout << "Nowe u hav a rel liv Grimer!!!!!" << endl;
                if (1 + (rand () % 649) == 89) cout << "Nowe u hav a rel liv Muk!!!!!" << endl;
                if (1 + (rand () % 649) == 90) cout << "Nowe u hav a rel liv Shellder!!!!!" << endl;
                if (1 + (rand () % 649) == 91) cout << "Nowe u hav a rel liv Cloyster!!!!!" << endl;
                if (1 + (rand () % 649) == 92) cout << "Nowe u hav a rel liv Gastly!!!!!" << endl;
                if (1 + (rand () % 649) == 93) cout << "Nowe u hav a rel liv Haunter!!!!!" << endl;
                if (1 + (rand () % 649) == 94) cout << "Nowe u hav a rel liv Gengar!!!!!" << endl;
                if (1 + (rand () % 649) == 95) cout << "Nowe u hav a rel liv Onix!!!!!" << endl;
                if (1 + (rand () % 649) == 96) cout << "Nowe u hav a rel liv Drowzee!!!!!" << endl;
                if (1 + (rand () % 649) == 97) cout << "Nowe u hav a rel liv Hypno!!!!!" << endl;
                if (1 + (rand () % 649) == 98) cout << "Nowe u hav a rel liv Krabby!!!!!" << endl;
                if (1 + (rand () % 649) == 99) cout << "Nowe u hav a rel liv Kingler!!!!!" << endl;
                if (1 + (rand () % 649) == 100) cout << "Nowe u hav a rel liv Voltorb!!!!!" << endl;
                if (1 + (rand () % 649) == 101) cout << "Nowe u hav a rel liv Electrode!!!!!" << endl;
                if (1 + (rand () % 649) == 102) cout << "Nowe u hav a rel liv Exeggcute!!!!!" << endl;
                if (1 + (rand () % 649) == 103) cout << "Nowe u hav a rel liv Exeggutor!!!!!" << endl;
                if (1 + (rand () % 649) == 104) cout << "Nowe u hav a rel liv Cubone!!!!!" << endl;
                if (1 + (rand () % 649) == 105) cout << "Nowe u hav a rel liv Marowak!!!!!" << endl;
                if (1 + (rand () % 649) == 106) cout << "Nowe u hav a rel liv Hitmonlee!!!!!" << endl;
                if (1 + (rand () % 649) == 107) cout << "Nowe u hav a rel liv Hitmonchan!!!!!" << endl;
                if (1 + (rand () % 649) == 108) cout << "Nowe u hav a rel liv Lickitung!!!!!" << endl;
                if (1 + (rand () % 649) == 109) cout << "Nowe u hav a rel liv Koffing!!!!!" << endl;
                if (1 + (rand () % 649) == 110) cout << "Nowe u hav a rel liv Weezing!!!!!" << endl;
                if (1 + (rand () % 649) == 111) cout << "Nowe u hav a rel liv Rhyhorn!!!!!" << endl;
                if (1 + (rand () % 649) == 112) cout << "Nowe u hav a rel liv Rhydon!!!!!" << endl;
                if (1 + (rand () % 649) == 113) cout << "Nowe u hav a rel liv Chansey!!!!!" << endl;
                if (1 + (rand () % 649) == 114) cout << "Nowe u hav a rel liv Tangela!!!!!" << endl;
                if (1 + (rand () % 649) == 115) cout << "Nowe u hav a rel liv Kangaskhan!!!!!" << endl;
                if (1 + (rand () % 649) == 116) cout << "Nowe u hav a rel liv Horsea!!!!!" << endl;
                if (1 + (rand () % 649) == 117) cout << "Nowe u hav a rel liv Seadra!!!!!" << endl;
                if (1 + (rand () % 649) == 118) cout << "Nowe u hav a rel liv Goldeen!!!!!" << endl;
                if (1 + (rand () % 649) == 119) cout << "Nowe u hav a rel liv Seaking!!!!!" << endl;
                if (1 + (rand () % 649) == 120) cout << "Nowe u hav a rel liv Staryu!!!!!" << endl;
                if (1 + (rand () % 649) == 121) cout << "Nowe u hav a rel liv Starmie!!!!!" << endl;
                if (1 + (rand () % 649) == 122) cout << "Nowe u hav a rel liv Mr. Mime!!!!!" << endl;
                if (1 + (rand () % 649) == 123) cout << "Nowe u hav a rel liv Scyther!!!!!" << endl;
                if (1 + (rand () % 649) == 124) cout << "Nowe u hav a rel liv Jynx!!!!!" << endl;
                if (1 + (rand () % 649) == 125) cout << "Nowe u hav a rel liv Electabuzz!!!!!" << endl;
                if (1 + (rand () % 649) == 126) cout << "Nowe u hav a rel liv Magmar!!!!!" << endl;
                if (1 + (rand () % 649) == 127) cout << "Nowe u hav a rel liv Pinsir!!!!!" << endl;
                if (1 + (rand () % 649) == 128) cout << "Nowe u hav a rel liv Tauros!!!!!" << endl;
                if (1 + (rand () % 649) == 129) cout << "Nowe u hav a rel liv Magikarp!!!!!" << endl;
                if (1 + (rand () % 649) == 130) cout << "Nowe u hav a rel liv Gyarados!!!!!" << endl;
                if (1 + (rand () % 649) == 131) cout << "Nowe u hav a rel liv Lapras!!!!!" << endl;
                if (1 + (rand () % 649) == 132) cout << "Nowe u hav a rel liv Ditto!!!!!" << endl;
                if (1 + (rand () % 649) == 133) cout << "Nowe u hav a rel liv Eevee!!!!!" << endl;
                if (1 + (rand () % 649) == 134) cout << "Nowe u hav a rel liv Vaporeon!!!!!" << endl;
                if (1 + (rand () % 649) == 135) cout << "Nowe u hav a rel liv Jolteon!!!!!" << endl;
                if (1 + (rand () % 649) == 136) cout << "Nowe u hav a rel liv Flareon!!!!!" << endl;
                if (1 + (rand () % 649) == 137) cout << "Nowe u hav a rel liv Porygon!!!!!" << endl;
                if (1 + (rand () % 649) == 138) cout << "Nowe u hav a rel liv Omanyte!!!!!" << endl;
                if (1 + (rand () % 649) == 139) cout << "Nowe u hav a rel liv Omastar!!!!!" << endl;
                if (1 + (rand () % 649) == 140) cout << "Nowe u hav a rel liv Kabuto!!!!!" << endl;
                if (1 + (rand () % 649) == 141) cout << "Nowe u hav a rel liv Kabutops!!!!!" << endl;
                if (1 + (rand () % 649) == 142) cout << "Nowe u hav a rel liv Aerodactyl!!!!!" << endl;
                if (1 + (rand () % 649) == 143) cout << "Nowe u hav a rel liv Snorlax!!!!!" << endl;
                if (1 + (rand () % 649) == 144) cout << "Nowe u hav a rel liv Articuno!!!!!" << endl;
                if (1 + (rand () % 649) == 145) cout << "Nowe u hav a rel liv Zapdos!!!!!" << endl;
                if (1 + (rand () % 649) == 146) cout << "Nowe u hav a rel liv Moltres!!!!!" << endl;
                if (1 + (rand () % 649) == 147) cout << "Nowe u hav a rel liv Dratini!!!!!" << endl;
                if (1 + (rand () % 649) == 148) cout << "Nowe u hav a rel liv Dragonair!!!!!" << endl;
                if (1 + (rand () % 649) == 149) cout << "Nowe u hav a rel liv Dragonite!!!!!" << endl;
                if (1 + (rand () % 649) == 150) cout << "Nowe u hav a rel liv Mewtwo!!!!!" << endl;
                if (1 + (rand () % 649) == 151) cout << "Nowe u hav a rel liv Mew!!!!!" << endl;
                if (1 + (rand () % 649) == 152) cout << "Nowe u hav a rel liv Chikorita!!!!!" << endl;
                if (1 + (rand () % 649) == 153) cout << "Nowe u hav a rel liv Bayleef!!!!!" << endl;
                if (1 + (rand () % 649) == 154) cout << "Nowe u hav a rel liv Meganium!!!!!" << endl;
                if (1 + (rand () % 649) == 155) cout << "Nowe u hav a rel liv Cyndaquil!!!!!" << endl;
                if (1 + (rand () % 649) == 156) cout << "Nowe u hav a rel liv Quilava!!!!!" << endl;
                if (1 + (rand () % 649) == 157) cout << "Nowe u hav a rel liv Typhlosion!!!!!" << endl;
                if (1 + (rand () % 649) == 158) cout << "Nowe u hav a rel liv Totodile!!!!!" << endl;
                if (1 + (rand () % 649) == 159) cout << "Nowe u hav a rel liv Croconaw!!!!!" << endl;
                if (1 + (rand () % 649) == 160) cout << "Nowe u hav a rel liv Feraligatr!!!!!" << endl;
                if (1 + (rand () % 649) == 161) cout << "Nowe u hav a rel liv Sentret!!!!!" << endl;
                if (1 + (rand () % 649) == 162) cout << "Nowe u hav a rel liv Furret!!!!!" << endl;
                if (1 + (rand () % 649) == 163) cout << "Nowe u hav a rel liv Hoothoot!!!!!" << endl;
                if (1 + (rand () % 649) == 164) cout << "Nowe u hav a rel liv Noctowl!!!!!" << endl;
                if (1 + (rand () % 649) == 165) cout << "Nowe u hav a rel liv Ledyba!!!!!" << endl;
                if (1 + (rand () % 649) == 166) cout << "Nowe u hav a rel liv Ledian!!!!!" << endl;
                if (1 + (rand () % 649) == 167) cout << "Nowe u hav a rel liv Spinarak!!!!!" << endl;
                if (1 + (rand () % 649) == 168) cout << "Nowe u hav a rel liv Ariados!!!!!" << endl;
                if (1 + (rand () % 649) == 169) cout << "Nowe u hav a rel liv Crobat!!!!!" << endl;
                if (1 + (rand () % 649) == 170) cout << "Nowe u hav a rel liv Chinchou!!!!!" << endl;
                if (1 + (rand () % 649) == 171) cout << "Nowe u hav a rel liv Lanturn!!!!!" << endl;
                if (1 + (rand () % 649) == 172) cout << "Nowe u hav a rel liv Pichu!!!!!" << endl;
                if (1 + (rand () % 649) == 173) cout << "Nowe u hav a rel liv Cleffa!!!!!" << endl;
                if (1 + (rand () % 649) == 174) cout << "Nowe u hav a rel liv Igglybuff!!!!!" << endl;
                if (1 + (rand () % 649) == 175) cout << "Nowe u hav a rel liv Togepi!!!!!" << endl;
                if (1 + (rand () % 649) == 176) cout << "Nowe u hav a rel liv Togetic!!!!!" << endl;
                if (1 + (rand () % 649) == 177) cout << "Nowe u hav a rel liv Natu!!!!!" << endl;
                if (1 + (rand () % 649) == 178) cout << "Nowe u hav a rel liv Xatu!!!!!" << endl;
                if (1 + (rand () % 649) == 179) cout << "Nowe u hav a rel liv Mareep!!!!!" << endl;
                if (1 + (rand () % 649) == 180) cout << "Nowe u hav a rel liv Flaaffy!!!!!" << endl;
                if (1 + (rand () % 649) == 181) cout << "Nowe u hav a rel liv Ampharos!!!!!" << endl;
                if (1 + (rand () % 649) == 182) cout << "Nowe u hav a rel liv Bellossom!!!!!" << endl;
                if (1 + (rand () % 649) == 183) cout << "Nowe u hav a rel liv Marill!!!!!" << endl;
                if (1 + (rand () % 649) == 184) cout << "Nowe u hav a rel liv Azumarill!!!!!" << endl;
                if (1 + (rand () % 649) == 185) cout << "Nowe u hav a rel liv Sudowoodo!!!!!" << endl;
                if (1 + (rand () % 649) == 186) cout << "Nowe u hav a rel liv Politoed!!!!!" << endl;
                if (1 + (rand () % 649) == 187) cout << "Nowe u hav a rel liv Hoppip!!!!!" << endl;
                if (1 + (rand () % 649) == 188) cout << "Nowe u hav a rel liv Skiploom!!!!!" << endl;
                if (1 + (rand () % 649) == 189) cout << "Nowe u hav a rel liv Jumpluff!!!!!" << endl;
                if (1 + (rand () % 649) == 190) cout << "Nowe u hav a rel liv Aipom!!!!!" << endl;
                if (1 + (rand () % 649) == 191) cout << "Nowe u hav a rel liv Sunkern!!!!!" << endl;
                if (1 + (rand () % 649) == 192) cout << "Nowe u hav a rel liv Sunflora!!!!!" << endl;
                if (1 + (rand () % 649) == 193) cout << "Nowe u hav a rel liv Yanma!!!!!" << endl;
                if (1 + (rand () % 649) == 194) cout << "Nowe u hav a rel liv Wooper!!!!!" << endl;
                if (1 + (rand () % 649) == 195) cout << "Nowe u hav a rel liv Quagsire!!!!!" << endl;
                if (1 + (rand () % 649) == 196) cout << "Nowe u hav a rel liv Espeon!!!!!" << endl;
                if (1 + (rand () % 649) == 197) cout << "Nowe u hav a rel liv Umbreon!!!!!" << endl;
                if (1 + (rand () % 649) == 198) cout << "Nowe u hav a rel liv Murkrow!!!!!" << endl;
                if (1 + (rand () % 649) == 199) cout << "Nowe u hav a rel liv Slowking!!!!!" << endl;
                if (1 + (rand () % 649) == 200) cout << "Nowe u hav a rel liv Misdreavus!!!!!" << endl;
                if (1 + (rand () % 649) == 201) cout << "Nowe u hav a rel liv Unown!!!!!" << endl;
                if (1 + (rand () % 649) == 202) cout << "Nowe u hav a rel liv Wobbuffet!!!!!" << endl;
                if (1 + (rand () % 649) == 203) cout << "Nowe u hav a rel liv Girafarig!!!!!" << endl;
                if (1 + (rand () % 649) == 204) cout << "Nowe u hav a rel liv Pineco!!!!!" << endl;
                if (1 + (rand () % 649) == 205) cout << "Nowe u hav a rel liv Forretress!!!!!" << endl;
                if (1 + (rand () % 649) == 206) cout << "Nowe u hav a rel liv Dunsparce!!!!!" << endl;
                if (1 + (rand () % 649) == 207) cout << "Nowe u hav a rel liv Gligar!!!!!" << endl;
                if (1 + (rand () % 649) == 208) cout << "Nowe u hav a rel liv Steelix!!!!!" << endl;
                if (1 + (rand () % 649) == 209) cout << "Nowe u hav a rel liv Snubbull!!!!!" << endl;
                if (1 + (rand () % 649) == 210) cout << "Nowe u hav a rel liv Granbull!!!!!" << endl;
                if (1 + (rand () % 649) == 211) cout << "Nowe u hav a rel liv Qwilfish!!!!!" << endl;
                if (1 + (rand () % 649) == 212) cout << "Nowe u hav a rel liv Scizor!!!!!" << endl;
                if (1 + (rand () % 649) == 213) cout << "Nowe u hav a rel liv Shuckle!!!!!" << endl;
                if (1 + (rand () % 649) == 214) cout << "Nowe u hav a rel liv Heracross!!!!!" << endl;
                if (1 + (rand () % 649) == 215) cout << "Nowe u hav a rel liv Sneasel!!!!!" << endl;
                if (1 + (rand () % 649) == 216) cout << "Nowe u hav a rel liv Teddiursa!!!!!" << endl;
                if (1 + (rand () % 649) == 217) cout << "Nowe u hav a rel liv Ursaring!!!!!" << endl;
                if (1 + (rand () % 649) == 218) cout << "Nowe u hav a rel liv Slugma!!!!!" << endl;
                if (1 + (rand () % 649) == 219) cout << "Nowe u hav a rel liv Magcargo!!!!!" << endl;
                if (1 + (rand () % 649) == 220) cout << "Nowe u hav a rel liv Swinub!!!!!" << endl;
                if (1 + (rand () % 649) == 221) cout << "Nowe u hav a rel liv Piloswine!!!!!" << endl;
                if (1 + (rand () % 649) == 222) cout << "Nowe u hav a rel liv Corsola!!!!!" << endl;
                if (1 + (rand () % 649) == 223) cout << "Nowe u hav a rel liv Remoraid!!!!!" << endl;
                if (1 + (rand () % 649) == 224) cout << "Nowe u hav a rel liv Octillery!!!!!" << endl;
                if (1 + (rand () % 649) == 225) cout << "Nowe u hav a rel liv Delibird!!!!!" << endl;
                if (1 + (rand () % 649) == 226) cout << "Nowe u hav a rel liv Mantine!!!!!" << endl;
                if (1 + (rand () % 649) == 227) cout << "Nowe u hav a rel liv Skarmory!!!!!" << endl;
                if (1 + (rand () % 649) == 228) cout << "Nowe u hav a rel liv Houndour!!!!!" << endl;
                if (1 + (rand () % 649) == 229) cout << "Nowe u hav a rel liv Houndoom!!!!!" << endl;
                if (1 + (rand () % 649) == 230) cout << "Nowe u hav a rel liv Kingdra!!!!!" << endl;
                if (1 + (rand () % 649) == 231) cout << "Nowe u hav a rel liv Phanpy!!!!!" << endl;
                if (1 + (rand () % 649) == 232) cout << "Nowe u hav a rel liv Donphan!!!!!" << endl;
                if (1 + (rand () % 649) == 233) cout << "Nowe u hav a rel liv Porygon2!!!!!" << endl;
                if (1 + (rand () % 649) == 234) cout << "Nowe u hav a rel liv Stantler!!!!!" << endl;
                if (1 + (rand () % 649) == 235) cout << "Nowe u hav a rel liv Smeargle!!!!!" << endl;
                if (1 + (rand () % 649) == 236) cout << "Nowe u hav a rel liv Tyrogue!!!!!" << endl;
                if (1 + (rand () % 649) == 237) cout << "Nowe u hav a rel liv Hitmontop!!!!!" << endl;
                if (1 + (rand () % 649) == 238) cout << "Nowe u hav a rel liv Smoochum!!!!!" << endl;
                if (1 + (rand () % 649) == 239) cout << "Nowe u hav a rel liv Elekid!!!!!" << endl;
                if (1 + (rand () % 649) == 240) cout << "Nowe u hav a rel liv Magby!!!!!" << endl;
                if (1 + (rand () % 649) == 241) cout << "Nowe u hav a rel liv Miltank!!!!!" << endl;
                if (1 + (rand () % 649) == 242) cout << "Nowe u hav a rel liv Blissey!!!!!" << endl;
                if (1 + (rand () % 649) == 243) cout << "Nowe u hav a rel liv Raikou!!!!!" << endl;
                if (1 + (rand () % 649) == 244) cout << "Nowe u hav a rel liv Entei!!!!!" << endl;
                if (1 + (rand () % 649) == 245) cout << "Nowe u hav a rel liv Suicune!!!!!" << endl;
                if (1 + (rand () % 649) == 246) cout << "Nowe u hav a rel liv Larvitar!!!!!" << endl;
                if (1 + (rand () % 649) == 247) cout << "Nowe u hav a rel liv Pupitar!!!!!" << endl;
                if (1 + (rand () % 649) == 248) cout << "Nowe u hav a rel liv Tyranitar!!!!!" << endl;
                if (1 + (rand () % 649) == 249) cout << "Nowe u hav a rel liv Lugia!!!!!" << endl;
                if (1 + (rand () % 649) == 250) cout << "Nowe u hav a rel liv Ho-Oh!!!!!" << endl;
                if (1 + (rand () % 649) == 251) cout << "Nowe u hav a rel liv Celebi!!!!!" << endl;
                if (1 + (rand () % 649) == 252) cout << "Nowe u hav a rel liv Treecko!!!!!" << endl;
                if (1 + (rand () % 649) == 253) cout << "Nowe u hav a rel liv Grovyle!!!!!" << endl;
                if (1 + (rand () % 649) == 254) cout << "Nowe u hav a rel liv Sceptile!!!!!" << endl;
                if (1 + (rand () % 649) == 255) cout << "Nowe u hav a rel liv Torchic!!!!!" << endl;
                if (1 + (rand () % 649) == 256) cout << "Nowe u hav a rel liv Combusken!!!!!" << endl;
                if (1 + (rand () % 649) == 257) cout << "Nowe u hav a rel liv Blaziken!!!!!" << endl;
                if (1 + (rand () % 649) == 258) cout << "Nowe u hav a rel liv Mudkip!!!!!" << endl;
                if (1 + (rand () % 649) == 259) cout << "Nowe u hav a rel liv Marshtomp!!!!!" << endl;
                if (1 + (rand () % 649) == 260) cout << "Nowe u hav a rel liv Swampert!!!!!" << endl;
                if (1 + (rand () % 649) == 261) cout << "Nowe u hav a rel liv Poochyena!!!!!" << endl;
                if (1 + (rand () % 649) == 262) cout << "Nowe u hav a rel liv Mightyena!!!!!" << endl;
                if (1 + (rand () % 649) == 263) cout << "Nowe u hav a rel liv Zigzagoon!!!!!" << endl;
                if (1 + (rand () % 649) == 264) cout << "Nowe u hav a rel liv Linoone!!!!!" << endl;
                if (1 + (rand () % 649) == 265) cout << "Nowe u hav a rel liv Wurmple!!!!!" << endl;
                if (1 + (rand () % 649) == 266) cout << "Nowe u hav a rel liv Silcoon!!!!!" << endl;
                if (1 + (rand () % 649) == 267) cout << "Nowe u hav a rel liv Beautifly!!!!!" << endl;
                if (1 + (rand () % 649) == 268) cout << "Nowe u hav a rel liv Cascoon!!!!!" << endl;
                if (1 + (rand () % 649) == 269) cout << "Nowe u hav a rel liv Dustox!!!!!" << endl;
                if (1 + (rand () % 649) == 270) cout << "Nowe u hav a rel liv Lotad!!!!!" << endl;
                if (1 + (rand () % 649) == 271) cout << "Nowe u hav a rel liv Lombre!!!!!" << endl;
                if (1 + (rand () % 649) == 272) cout << "Nowe u hav a rel liv Ludicolo!!!!!" << endl;
                if (1 + (rand () % 649) == 273) cout << "Nowe u hav a rel liv Seedot!!!!!" << endl;
                if (1 + (rand () % 649) == 274) cout << "Nowe u hav a rel liv Nuzleaf!!!!!" << endl;
                if (1 + (rand () % 649) == 275) cout << "Nowe u hav a rel liv Shiftry!!!!!" << endl;
                if (1 + (rand () % 649) == 276) cout << "Nowe u hav a rel liv Taillow!!!!!" << endl;
                if (1 + (rand () % 649) == 277) cout << "Nowe u hav a rel liv Swellow!!!!!" << endl;
                if (1 + (rand () % 649) == 278) cout << "Nowe u hav a rel liv Wingull!!!!!" << endl;
                if (1 + (rand () % 649) == 279) cout << "Nowe u hav a rel liv Pelipper!!!!!" << endl;
                if (1 + (rand () % 649) == 280) cout << "Nowe u hav a rel liv Ralts!!!!!" << endl;
                if (1 + (rand () % 649) == 281) cout << "Nowe u hav a rel liv Kirlia!!!!!" << endl;
                if (1 + (rand () % 649) == 282) cout << "Nowe u hav a rel liv Gardevoir!!!!!" << endl;
                if (1 + (rand () % 649) == 283) cout << "Nowe u hav a rel liv Surskit!!!!!" << endl;
                if (1 + (rand () % 649) == 284) cout << "Nowe u hav a rel liv Masquerain!!!!!" << endl;
                if (1 + (rand () % 649) == 285) cout << "Nowe u hav a rel liv Shroomish!!!!!" << endl;
                if (1 + (rand () % 649) == 286) cout << "Nowe u hav a rel liv Breloom!!!!!" << endl;
                if (1 + (rand () % 649) == 287) cout << "Nowe u hav a rel liv Slakoth!!!!!" << endl;
                if (1 + (rand () % 649) == 288) cout << "Nowe u hav a rel liv Vigoroth!!!!!" << endl;
                if (1 + (rand () % 649) == 289) cout << "Nowe u hav a rel liv Slaking!!!!!" << endl;
                if (1 + (rand () % 649) == 290) cout << "Nowe u hav a rel liv Nincada!!!!!" << endl;
                if (1 + (rand () % 649) == 291) cout << "Nowe u hav a rel liv Ninjask!!!!!" << endl;
                if (1 + (rand () % 649) == 292) cout << "Nowe u hav a rel liv Shedinja!!!!!" << endl;
                if (1 + (rand () % 649) == 293) cout << "Nowe u hav a rel liv Whismur!!!!!" << endl;
                if (1 + (rand () % 649) == 294) cout << "Nowe u hav a rel liv Loudred!!!!!" << endl;
                if (1 + (rand () % 649) == 295) cout << "Nowe u hav a rel liv Exploud!!!!!" << endl;
                if (1 + (rand () % 649) == 296) cout << "Nowe u hav a rel liv Makuhita!!!!!" << endl;
                if (1 + (rand () % 649) == 297) cout << "Nowe u hav a rel liv Hariyama!!!!!" << endl;
                if (1 + (rand () % 649) == 298) cout << "Nowe u hav a rel liv Azurill!!!!!" << endl;
                if (1 + (rand () % 649) == 299) cout << "Nowe u hav a rel liv Nosepass!!!!!" << endl;
                if (1 + (rand () % 649) == 300) cout << "Nowe u hav a rel liv Skitty!!!!!" << endl;
                if (1 + (rand () % 649) == 301) cout << "Nowe u hav a rel liv Delcatty!!!!!" << endl;
                if (1 + (rand () % 649) == 302) cout << "Nowe u hav a rel liv Sableye!!!!!" << endl;
                if (1 + (rand () % 649) == 303) cout << "Nowe u hav a rel liv Mawile!!!!!" << endl;
                if (1 + (rand () % 649) == 304) cout << "Nowe u hav a rel liv Aron!!!!!" << endl;
                if (1 + (rand () % 649) == 305) cout << "Nowe u hav a rel liv Lairon!!!!!" << endl;
                if (1 + (rand () % 649) == 306) cout << "Nowe u hav a rel liv Aggron!!!!!" << endl;
                if (1 + (rand () % 649) == 307) cout << "Nowe u hav a rel liv Meditite!!!!!" << endl;
                if (1 + (rand () % 649) == 308) cout << "Nowe u hav a rel liv Medicham!!!!!" << endl;
                if (1 + (rand () % 649) == 309) cout << "Nowe u hav a rel liv Electrike!!!!!" << endl;
                if (1 + (rand () % 649) == 310) cout << "Nowe u hav a rel liv Manectric!!!!!" << endl;
                if (1 + (rand () % 649) == 311) cout << "Nowe u hav a rel liv Plusle!!!!!" << endl;
                if (1 + (rand () % 649) == 312) cout << "Nowe u hav a rel liv Minun!!!!!" << endl;
                if (1 + (rand () % 649) == 313) cout << "Nowe u hav a rel liv Volbeat!!!!!" << endl;
                if (1 + (rand () % 649) == 314) cout << "Nowe u hav a rel liv Illumise!!!!!" << endl;
                if (1 + (rand () % 649) == 315) cout << "Nowe u hav a rel liv Roselia!!!!!" << endl;
                if (1 + (rand () % 649) == 316) cout << "Nowe u hav a rel liv Gulpin!!!!!" << endl;
                if (1 + (rand () % 649) == 317) cout << "Nowe u hav a rel liv Swalot!!!!!" << endl;
                if (1 + (rand () % 649) == 318) cout << "Nowe u hav a rel liv Carvanha!!!!!" << endl;
                if (1 + (rand () % 649) == 319) cout << "Nowe u hav a rel liv Sharpedo!!!!!" << endl;
                if (1 + (rand () % 649) == 320) cout << "Nowe u hav a rel liv Wailmer!!!!!" << endl;
                if (1 + (rand () % 649) == 321) cout << "Nowe u hav a rel liv Wailord!!!!!" << endl;
                if (1 + (rand () % 649) == 322) cout << "Nowe u hav a rel liv Numel!!!!!" << endl;
                if (1 + (rand () % 649) == 323) cout << "Nowe u hav a rel liv Camerupt!!!!!" << endl;
                if (1 + (rand () % 649) == 324) cout << "Nowe u hav a rel liv Torkoal!!!!!" << endl;
                if (1 + (rand () % 649) == 325) cout << "Nowe u hav a rel liv Spoink!!!!!" << endl;
                if (1 + (rand () % 649) == 326) cout << "Nowe u hav a rel liv Grumpig!!!!!" << endl;
                if (1 + (rand () % 649) == 327) cout << "Nowe u hav a rel liv Spinda!!!!!" << endl;
                if (1 + (rand () % 649) == 328) cout << "Nowe u hav a rel liv Trapinch!!!!!" << endl;
                if (1 + (rand () % 649) == 329) cout << "Nowe u hav a rel liv Vibrava!!!!!" << endl;
                if (1 + (rand () % 649) == 330) cout << "Nowe u hav a rel liv Flygon!!!!!" << endl;
                if (1 + (rand () % 649) == 331) cout << "Nowe u hav a rel liv Cacnea!!!!!" << endl;
                if (1 + (rand () % 649) == 332) cout << "Nowe u hav a rel liv Cacturne!!!!!" << endl;
                if (1 + (rand () % 649) == 333) cout << "Nowe u hav a rel liv Swablu!!!!!" << endl;
                if (1 + (rand () % 649) == 334) cout << "Nowe u hav a rel liv Altaria!!!!!" << endl;
                if (1 + (rand () % 649) == 335) cout << "Nowe u hav a rel liv Zangoose!!!!!" << endl;
                if (1 + (rand () % 649) == 336) cout << "Nowe u hav a rel liv Seviper!!!!!" << endl;
                if (1 + (rand () % 649) == 337) cout << "Nowe u hav a rel liv Lunatone!!!!!" << endl;
                if (1 + (rand () % 649) == 338) cout << "Nowe u hav a rel liv Solrock!!!!!" << endl;
                if (1 + (rand () % 649) == 339) cout << "Nowe u hav a rel liv Barboach!!!!!" << endl;
                if (1 + (rand () % 649) == 340) cout << "Nowe u hav a rel liv Whiscash!!!!!" << endl;
                if (1 + (rand () % 649) == 341) cout << "Nowe u hav a rel liv Corphish!!!!!" << endl;
                if (1 + (rand () % 649) == 342) cout << "Nowe u hav a rel liv Crawdaunt!!!!!" << endl;
                if (1 + (rand () % 649) == 343) cout << "Nowe u hav a rel liv Baltoy!!!!!" << endl;
                if (1 + (rand () % 649) == 344) cout << "Nowe u hav a rel liv Claydol!!!!!" << endl;
                if (1 + (rand () % 649) == 345) cout << "Nowe u hav a rel liv Lileep!!!!!" << endl;
                if (1 + (rand () % 649) == 346) cout << "Nowe u hav a rel liv Cradily!!!!!" << endl;
                if (1 + (rand () % 649) == 347) cout << "Nowe u hav a rel liv Anorith!!!!!" << endl;
                if (1 + (rand () % 649) == 348) cout << "Nowe u hav a rel liv Armaldo!!!!!" << endl;
                if (1 + (rand () % 649) == 349) cout << "Nowe u hav a rel liv Feebas!!!!!" << endl;
                if (1 + (rand () % 649) == 350) cout << "Nowe u hav a rel liv Milotic!!!!!" << endl;
                if (1 + (rand () % 649) == 351) cout << "Nowe u hav a rel liv Castform!!!!!" << endl;
                if (1 + (rand () % 649) == 352) cout << "Nowe u hav a rel liv Kecleon!!!!!" << endl;
                if (1 + (rand () % 649) == 353) cout << "Nowe u hav a rel liv Shuppet!!!!!" << endl;
                if (1 + (rand () % 649) == 354) cout << "Nowe u hav a rel liv Banette!!!!!" << endl;
                if (1 + (rand () % 649) == 355) cout << "Nowe u hav a rel liv Duskull!!!!!" << endl;
                if (1 + (rand () % 649) == 356) cout << "Nowe u hav a rel liv Dusclops!!!!!" << endl;
                if (1 + (rand () % 649) == 357) cout << "Nowe u hav a rel liv Tropius!!!!!" << endl;
                if (1 + (rand () % 649) == 358) cout << "Nowe u hav a rel liv Chimecho!!!!!" << endl;
                if (1 + (rand () % 649) == 359) cout << "Nowe u hav a rel liv Absol!!!!!" << endl;
                if (1 + (rand () % 649) == 360) cout << "Nowe u hav a rel liv Wynaut!!!!!" << endl;
                if (1 + (rand () % 649) == 361) cout << "Nowe u hav a rel liv Snorunt!!!!!" << endl;
                if (1 + (rand () % 649) == 362) cout << "Nowe u hav a rel liv Glalie!!!!!" << endl;
                if (1 + (rand () % 649) == 363) cout << "Nowe u hav a rel liv Spheal!!!!!" << endl;
                if (1 + (rand () % 649) == 364) cout << "Nowe u hav a rel liv Sealeo!!!!!" << endl;
                if (1 + (rand () % 649) == 365) cout << "Nowe u hav a rel liv Walrein!!!!!" << endl;
                if (1 + (rand () % 649) == 366) cout << "Nowe u hav a rel liv Clamperl!!!!!" << endl;
                if (1 + (rand () % 649) == 367) cout << "Nowe u hav a rel liv Huntail!!!!!" << endl;
                if (1 + (rand () % 649) == 368) cout << "Nowe u hav a rel liv Gorebyss!!!!!" << endl;
                if (1 + (rand () % 649) == 369) cout << "Nowe u hav a rel liv Relicanth!!!!!" << endl;
                if (1 + (rand () % 649) == 370) cout << "Nowe u hav a rel liv Luvdisc!!!!!" << endl;
                if (1 + (rand () % 649) == 371) cout << "Nowe u hav a rel liv Bagon!!!!!" << endl;
                if (1 + (rand () % 649) == 372) cout << "Nowe u hav a rel liv Shelgon!!!!!" << endl;
                if (1 + (rand () % 649) == 373) cout << "Nowe u hav a rel liv Salamence!!!!!" << endl;
                if (1 + (rand () % 649) == 374) cout << "Nowe u hav a rel liv Beldum!!!!!" << endl;
                if (1 + (rand () % 649) == 375) cout << "Nowe u hav a rel liv Metang!!!!!" << endl;
                if (1 + (rand () % 649) == 376) cout << "Nowe u hav a rel liv Metagross!!!!!" << endl;
                if (1 + (rand () % 649) == 377) cout << "Nowe u hav a rel liv Regirock!!!!!" << endl;
                if (1 + (rand () % 649) == 378) cout << "Nowe u hav a rel liv Regice!!!!!" << endl;
                if (1 + (rand () % 649) == 379) cout << "Nowe u hav a rel liv Registeel!!!!!" << endl;
                if (1 + (rand () % 649) == 380) cout << "Nowe u hav a rel liv Latias!!!!!" << endl;
                if (1 + (rand () % 649) == 381) cout << "Nowe u hav a rel liv Latios!!!!!" << endl;
                if (1 + (rand () % 649) == 382) cout << "Nowe u hav a rel liv Kyogre!!!!!" << endl;
                if (1 + (rand () % 649) == 383) cout << "Nowe u hav a rel liv Groudon!!!!!" << endl;
                if (1 + (rand () % 649) == 384) cout << "Nowe u hav a rel liv Rayquaza!!!!!" << endl;
                if (1 + (rand () % 649) == 385) cout << "Nowe u hav a rel liv Jirachi!!!!!" << endl;
                if (1 + (rand () % 649) == 386) cout << "Nowe u hav a rel liv Deoxys!!!!!" << endl;
                if (1 + (rand () % 649) == 387) cout << "Nowe u hav a rel liv Turtwig!!!!!" << endl;
                if (1 + (rand () % 649) == 388) cout << "Nowe u hav a rel liv Grotle!!!!!" << endl;
                if (1 + (rand () % 649) == 389) cout << "Nowe u hav a rel liv Torterra!!!!!" << endl;
                if (1 + (rand () % 649) == 390) cout << "Nowe u hav a rel liv Chimchar!!!!!" << endl;
                if (1 + (rand () % 649) == 391) cout << "Nowe u hav a rel liv Monferno!!!!!" << endl;
                if (1 + (rand () % 649) == 392) cout << "Nowe u hav a rel liv Infernape!!!!!" << endl;
                if (1 + (rand () % 649) == 393) cout << "Nowe u hav a rel liv Piplup!!!!!" << endl;
                if (1 + (rand () % 649) == 394) cout << "Nowe u hav a rel liv Prinplup!!!!!" << endl;
                if (1 + (rand () % 649) == 395) cout << "Nowe u hav a rel liv Empoleon!!!!!" << endl;
                if (1 + (rand () % 649) == 396) cout << "Nowe u hav a rel liv Starly!!!!!" << endl;
                if (1 + (rand () % 649) == 397) cout << "Nowe u hav a rel liv Staravia!!!!!" << endl;
                if (1 + (rand () % 649) == 398) cout << "Nowe u hav a rel liv Staraptor!!!!!" << endl;
                if (1 + (rand () % 649) == 399) cout << "Nowe u hav a rel liv Bidoof!!!!!" << endl;
                if (1 + (rand () % 649) == 400) cout << "Nowe u hav a rel liv Bibarel!!!!!" << endl;
                if (1 + (rand () % 649) == 401) cout << "Nowe u hav a rel liv Kricketot!!!!!" << endl;
                if (1 + (rand () % 649) == 402) cout << "Nowe u hav a rel liv Kricketune!!!!!" << endl;
                if (1 + (rand () % 649) == 403) cout << "Nowe u hav a rel liv Shinx!!!!!" << endl;
                if (1 + (rand () % 649) == 404) cout << "Nowe u hav a rel liv Luxio!!!!!" << endl;
                if (1 + (rand () % 649) == 405) cout << "Nowe u hav a rel liv Luxray!!!!!" << endl;
                if (1 + (rand () % 649) == 406) cout << "Nowe u hav a rel liv Budew!!!!!" << endl;
                if (1 + (rand () % 649) == 407) cout << "Nowe u hav a rel liv Roserade!!!!!" << endl;
                if (1 + (rand () % 649) == 408) cout << "Nowe u hav a rel liv Cranidos!!!!!" << endl;
                if (1 + (rand () % 649) == 409) cout << "Nowe u hav a rel liv Rampardos!!!!!" << endl;
                if (1 + (rand () % 649) == 410) cout << "Nowe u hav a rel liv Shieldon!!!!!" << endl;
                if (1 + (rand () % 649) == 411) cout << "Nowe u hav a rel liv Bastiodon!!!!!" << endl;
                if (1 + (rand () % 649) == 412) cout << "Nowe u hav a rel liv Burmy!!!!!" << endl;
                if (1 + (rand () % 649) == 413) cout << "Nowe u hav a rel liv Wormadam!!!!!" << endl;
                if (1 + (rand () % 649) == 414) cout << "Nowe u hav a rel liv Mothim!!!!!" << endl;
                if (1 + (rand () % 649) == 415) cout << "Nowe u hav a rel liv Combee!!!!!" << endl;
                if (1 + (rand () % 649) == 416) cout << "Nowe u hav a rel liv Vespiquen!!!!!" << endl;
                if (1 + (rand () % 649) == 417) cout << "Nowe u hav a rel liv Pachirisu!!!!!" << endl;
                if (1 + (rand () % 649) == 418) cout << "Nowe u hav a rel liv Buizel!!!!!" << endl;
                if (1 + (rand () % 649) == 419) cout << "Nowe u hav a rel liv Floatzel!!!!!" << endl;
                if (1 + (rand () % 649) == 420) cout << "Nowe u hav a rel liv Cherubi!!!!!" << endl;
                if (1 + (rand () % 649) == 421) cout << "Nowe u hav a rel liv Cherrim!!!!!" << endl;
                if (1 + (rand () % 649) == 422) cout << "Nowe u hav a rel liv Shellos!!!!!" << endl;
                if (1 + (rand () % 649) == 423) cout << "Nowe u hav a rel liv Gastrodon!!!!!" << endl;
                if (1 + (rand () % 649) == 424) cout << "Nowe u hav a rel liv Ambipom!!!!!" << endl;
                if (1 + (rand () % 649) == 425) cout << "Nowe u hav a rel liv Drifloon!!!!!" << endl;
                if (1 + (rand () % 649) == 426) cout << "Nowe u hav a rel liv Drifblim!!!!!" << endl;
                if (1 + (rand () % 649) == 427) cout << "Nowe u hav a rel liv Buneary!!!!!" << endl;
                if (1 + (rand () % 649) == 428) cout << "Nowe u hav a rel liv Lopunny!!!!!" << endl;
                if (1 + (rand () % 649) == 429) cout << "Nowe u hav a rel liv Mismagius!!!!!" << endl;
                if (1 + (rand () % 649) == 430) cout << "Nowe u hav a rel liv Honchkrow!!!!!" << endl;
                if (1 + (rand () % 649) == 431) cout << "Nowe u hav a rel liv Glameow!!!!!" << endl;
                if (1 + (rand () % 649) == 432) cout << "Nowe u hav a rel liv Purugly!!!!!" << endl;
                if (1 + (rand () % 649) == 433) cout << "Nowe u hav a rel liv Chingling!!!!!" << endl;
                if (1 + (rand () % 649) == 434) cout << "Nowe u hav a rel liv Stunky!!!!!" << endl;
                if (1 + (rand () % 649) == 435) cout << "Nowe u hav a rel liv Skuntank!!!!!" << endl;
                if (1 + (rand () % 649) == 436) cout << "Nowe u hav a rel liv Bronzor!!!!!" << endl;
                if (1 + (rand () % 649) == 437) cout << "Nowe u hav a rel liv Bronzong!!!!!" << endl;
                if (1 + (rand () % 649) == 438) cout << "Nowe u hav a rel liv Bonsly!!!!!" << endl;
                if (1 + (rand () % 649) == 439) cout << "Nowe u hav a rel liv Mime Jr.!!!!!" << endl;
                if (1 + (rand () % 649) == 440) cout << "Nowe u hav a rel liv Happiny!!!!!" << endl;
                if (1 + (rand () % 649) == 441) cout << "Nowe u hav a rel liv Chatot!!!!!" << endl;
                if (1 + (rand () % 649) == 442) cout << "Nowe u hav a rel liv Spiritomb!!!!!" << endl;
                if (1 + (rand () % 649) == 443) cout << "Nowe u hav a rel liv Gible!!!!!" << endl;
                if (1 + (rand () % 649) == 444) cout << "Nowe u hav a rel liv Gabite!!!!!" << endl;
                if (1 + (rand () % 649) == 445) cout << "Nowe u hav a rel liv Garchomp!!!!!" << endl;
                if (1 + (rand () % 649) == 446) cout << "Nowe u hav a rel liv Munchlax!!!!!" << endl;
                if (1 + (rand () % 649) == 447) cout << "Nowe u hav a rel liv Riolu!!!!!" << endl;
                if (1 + (rand () % 649) == 448) cout << "Nowe u hav a rel liv Lucario!!!!!" << endl;
                if (1 + (rand () % 649) == 449) cout << "Nowe u hav a rel liv Hippopotas!!!!!" << endl;
                if (1 + (rand () % 649) == 450) cout << "Nowe u hav a rel liv Hippowdon!!!!!" << endl;
                if (1 + (rand () % 649) == 451) cout << "Nowe u hav a rel liv Skorupi!!!!!" << endl;
                if (1 + (rand () % 649) == 452) cout << "Nowe u hav a rel liv Drapion!!!!!" << endl;
                if (1 + (rand () % 649) == 453) cout << "Nowe u hav a rel liv Croagunk!!!!!" << endl;
                if (1 + (rand () % 649) == 454) cout << "Nowe u hav a rel liv Toxicroak!!!!!" << endl;
                if (1 + (rand () % 649) == 455) cout << "Nowe u hav a rel liv Carnivine!!!!!" << endl;
                if (1 + (rand () % 649) == 456) cout << "Nowe u hav a rel liv Finneon!!!!!" << endl;
                if (1 + (rand () % 649) == 457) cout << "Nowe u hav a rel liv Lumineon!!!!!" << endl;
                if (1 + (rand () % 649) == 458) cout << "Nowe u hav a rel liv Mantyke!!!!!" << endl;
                if (1 + (rand () % 649) == 459) cout << "Nowe u hav a rel liv Snover!!!!!" << endl;
                if (1 + (rand () % 649) == 460) cout << "Nowe u hav a rel liv Abomasnow!!!!!" << endl;
                if (1 + (rand () % 649) == 461) cout << "Nowe u hav a rel liv Weavile!!!!!" << endl;
                if (1 + (rand () % 649) == 462) cout << "Nowe u hav a rel liv Magnezone!!!!!" << endl;
                if (1 + (rand () % 649) == 463) cout << "Nowe u hav a rel liv Lickilicky!!!!!" << endl;
                if (1 + (rand () % 649) == 464) cout << "Nowe u hav a rel liv Rhyperior!!!!!" << endl;
                if (1 + (rand () % 649) == 465) cout << "Nowe u hav a rel liv Tangrowth!!!!!" << endl;
                if (1 + (rand () % 649) == 466) cout << "Nowe u hav a rel liv Electivire!!!!!" << endl;
                if (1 + (rand () % 649) == 467) cout << "Nowe u hav a rel liv Magmortar!!!!!" << endl;
                if (1 + (rand () % 649) == 468) cout << "Nowe u hav a rel liv Togekiss!!!!!" << endl;
                if (1 + (rand () % 649) == 469) cout << "Nowe u hav a rel liv Yanmega!!!!!" << endl;
                if (1 + (rand () % 649) == 470) cout << "Nowe u hav a rel liv Leafeon!!!!!" << endl;
                if (1 + (rand () % 649) == 471) cout << "Nowe u hav a rel liv Glaceon!!!!!" << endl;
                if (1 + (rand () % 649) == 472) cout << "Nowe u hav a rel liv Gliscor!!!!!" << endl;
                if (1 + (rand () % 649) == 473) cout << "Nowe u hav a rel liv Mamoswine!!!!!" << endl;
                if (1 + (rand () % 649) == 474) cout << "Nowe u hav a rel liv Porygon-Z!!!!!" << endl;
                if (1 + (rand () % 649) == 475) cout << "Nowe u hav a rel liv Gallade!!!!!" << endl;
                if (1 + (rand () % 649) == 476) cout << "Nowe u hav a rel liv Probopass!!!!!" << endl;
                if (1 + (rand () % 649) == 477) cout << "Nowe u hav a rel liv Dusknoir!!!!!" << endl;
                if (1 + (rand () % 649) == 478) cout << "Nowe u hav a rel liv Froslass!!!!!" << endl;
                if (1 + (rand () % 649) == 479) cout << "Nowe u hav a rel liv Rotom!!!!!" << endl;
                if (1 + (rand () % 649) == 480) cout << "Nowe u hav a rel liv Uxie!!!!!" << endl;
                if (1 + (rand () % 649) == 481) cout << "Nowe u hav a rel liv Mesprit!!!!!" << endl;
                if (1 + (rand () % 649) == 482) cout << "Nowe u hav a rel liv Azelf!!!!!" << endl;
                if (1 + (rand () % 649) == 483) cout << "Nowe u hav a rel liv Dialga!!!!!" << endl;
                if (1 + (rand () % 649) == 484) cout << "Nowe u hav a rel liv Palkia!!!!!" << endl;
                if (1 + (rand () % 649) == 485) cout << "Nowe u hav a rel liv Heatran!!!!!" << endl;
                if (1 + (rand () % 649) == 486) cout << "Nowe u hav a rel liv Regigigas!!!!!" << endl;
                if (1 + (rand () % 649) == 487) cout << "Nowe u hav a rel liv Giratina!!!!!" << endl;
                if (1 + (rand () % 649) == 488) cout << "Nowe u hav a rel liv Cresselia!!!!!" << endl;
                if (1 + (rand () % 649) == 489) cout << "Nowe u hav a rel liv Phione!!!!!" << endl;
                if (1 + (rand () % 649) == 490) cout << "Nowe u hav a rel liv Manaphy!!!!!" << endl;
                if (1 + (rand () % 649) == 491) cout << "Nowe u hav a rel liv Darkrai!!!!!" << endl;
                if (1 + (rand () % 649) == 492) cout << "Nowe u hav a rel liv Shaymin!!!!!" << endl;
                if (1 + (rand () % 649) == 493) cout << "Nowe u hav a rel liv Arceus!!!!!" << endl;
                if (1 + (rand () % 649) == 494) cout << "Nowe u hav a rel liv Victini!!!!!" << endl;
                if (1 + (rand () % 649) == 495) cout << "Nowe u hav a rel liv Snivy!!!!!" << endl;
                if (1 + (rand () % 649) == 496) cout << "Nowe u hav a rel liv Servine!!!!!" << endl;
                if (1 + (rand () % 649) == 497) cout << "Nowe u hav a rel liv Serperior!!!!!" << endl;
                if (1 + (rand () % 649) == 498) cout << "Nowe u hav a rel liv Tepig!!!!!" << endl;
                if (1 + (rand () % 649) == 499) cout << "Nowe u hav a rel liv Pignite!!!!!" << endl;
                if (1 + (rand () % 649) == 500) cout << "Nowe u hav a rel liv Emboar!!!!!" << endl;
                if (1 + (rand () % 649) == 501) cout << "Nowe u hav a rel liv Oshawott!!!!!" << endl;
                if (1 + (rand () % 649) == 502) cout << "Nowe u hav a rel liv Dewott!!!!!" << endl;
                if (1 + (rand () % 649) == 503) cout << "Nowe u hav a rel liv Samurott!!!!!" << endl;
                if (1 + (rand () % 649) == 504) cout << "Nowe u hav a rel liv Patrat!!!!!" << endl;
                if (1 + (rand () % 649) == 505) cout << "Nowe u hav a rel liv Watchog!!!!!" << endl;
                if (1 + (rand () % 649) == 506) cout << "Nowe u hav a rel liv Lillipup!!!!!" << endl;
                if (1 + (rand () % 649) == 507) cout << "Nowe u hav a rel liv Herdier!!!!!" << endl;
                if (1 + (rand () % 649) == 508) cout << "Nowe u hav a rel liv Stoutland!!!!!" << endl;
                if (1 + (rand () % 649) == 509) cout << "Nowe u hav a rel liv Purrloin!!!!!" << endl;
                if (1 + (rand () % 649) == 510) cout << "Nowe u hav a rel liv Liepard!!!!!" << endl;
                if (1 + (rand () % 649) == 511) cout << "Nowe u hav a rel liv Pansage!!!!!" << endl;
                if (1 + (rand () % 649) == 512) cout << "Nowe u hav a rel liv Simisage!!!!!" << endl;
                if (1 + (rand () % 649) == 513) cout << "Nowe u hav a rel liv Pansear!!!!!" << endl;
                if (1 + (rand () % 649) == 514) cout << "Nowe u hav a rel liv Simisear!!!!!" << endl;
                if (1 + (rand () % 649) == 515) cout << "Nowe u hav a rel liv Panpour!!!!!" << endl;
                if (1 + (rand () % 649) == 516) cout << "Nowe u hav a rel liv Simipour!!!!!" << endl;
                if (1 + (rand () % 649) == 517) cout << "Nowe u hav a rel liv Munna!!!!!" << endl;
                if (1 + (rand () % 649) == 518) cout << "Nowe u hav a rel liv Musharna!!!!!" << endl;
                if (1 + (rand () % 649) == 519) cout << "Nowe u hav a rel liv Pidove!!!!!" << endl;
                if (1 + (rand () % 649) == 520) cout << "Nowe u hav a rel liv Tranquill!!!!!" << endl;
                if (1 + (rand () % 649) == 521) cout << "Nowe u hav a rel liv Unfezant!!!!!" << endl;
                if (1 + (rand () % 649) == 522) cout << "Nowe u hav a rel liv Blitzle!!!!!" << endl;
                if (1 + (rand () % 649) == 523) cout << "Nowe u hav a rel liv Zebstrika!!!!!" << endl;
                if (1 + (rand () % 649) == 524) cout << "Nowe u hav a rel liv Roggenrola!!!!!" << endl;
                if (1 + (rand () % 649) == 525) cout << "Nowe u hav a rel liv Boldore!!!!!" << endl;
                if (1 + (rand () % 649) == 526) cout << "Nowe u hav a rel liv Gigalith!!!!!" << endl;
                if (1 + (rand () % 649) == 527) cout << "Nowe u hav a rel liv Woobat!!!!!" << endl;
                if (1 + (rand () % 649) == 528) cout << "Nowe u hav a rel liv Swoobat!!!!!" << endl;
                if (1 + (rand () % 649) == 529) cout << "Nowe u hav a rel liv Drilbur!!!!!" << endl;
                if (1 + (rand () % 649) == 530) cout << "Nowe u hav a rel liv Excadrill!!!!!" << endl;
                if (1 + (rand () % 649) == 531) cout << "Nowe u hav a rel liv Audino!!!!!" << endl;
                if (1 + (rand () % 649) == 532) cout << "Nowe u hav a rel liv Timburr!!!!!" << endl;
                if (1 + (rand () % 649) == 533) cout << "Nowe u hav a rel liv Gurdurr!!!!!" << endl;
                if (1 + (rand () % 649) == 534) cout << "Nowe u hav a rel liv Conkeldurr!!!!!" << endl;
                if (1 + (rand () % 649) == 535) cout << "Nowe u hav a rel liv Tympole!!!!!" << endl;
                if (1 + (rand () % 649) == 536) cout << "Nowe u hav a rel liv Palpitoad!!!!!" << endl;
                if (1 + (rand () % 649) == 537) cout << "Nowe u hav a rel liv Seismitoad!!!!!" << endl;
                if (1 + (rand () % 649) == 538) cout << "Nowe u hav a rel liv Throh!!!!!" << endl;
                if (1 + (rand () % 649) == 539) cout << "Nowe u hav a rel liv Sawk!!!!!" << endl;
                if (1 + (rand () % 649) == 540) cout << "Nowe u hav a rel liv Sewaddle!!!!!" << endl;
                if (1 + (rand () % 649) == 541) cout << "Nowe u hav a rel liv Swadloon!!!!!" << endl;
                if (1 + (rand () % 649) == 542) cout << "Nowe u hav a rel liv Leavanny!!!!!" << endl;
                if (1 + (rand () % 649) == 543) cout << "Nowe u hav a rel liv Venipede!!!!!" << endl;
                if (1 + (rand () % 649) == 544) cout << "Nowe u hav a rel liv Whirlipede!!!!!" << endl;
                if (1 + (rand () % 649) == 545) cout << "Nowe u hav a rel liv Scolipede!!!!!" << endl;
                if (1 + (rand () % 649) == 546) cout << "Nowe u hav a rel liv Cottonee!!!!!" << endl;
                if (1 + (rand () % 649) == 547) cout << "Nowe u hav a rel liv Whimsicott!!!!!" << endl;
                if (1 + (rand () % 649) == 548) cout << "Nowe u hav a rel liv Petilil!!!!!" << endl;
                if (1 + (rand () % 649) == 549) cout << "Nowe u hav a rel liv Lilligant!!!!!" << endl;
                if (1 + (rand () % 649) == 550) cout << "Nowe u hav a rel liv Basculin!!!!!" << endl;
                if (1 + (rand () % 649) == 551) cout << "Nowe u hav a rel liv Sandile!!!!!" << endl;
                if (1 + (rand () % 649) == 552) cout << "Nowe u hav a rel liv Krokorok!!!!!" << endl;
                if (1 + (rand () % 649) == 553) cout << "Nowe u hav a rel liv Krookodile!!!!!" << endl;
                if (1 + (rand () % 649) == 554) cout << "Nowe u hav a rel liv Darumaka!!!!!" << endl;
                if (1 + (rand () % 649) == 555) cout << "Nowe u hav a rel liv Darmanitan!!!!!" << endl;
                if (1 + (rand () % 649) == 556) cout << "Nowe u hav a rel liv Maractus!!!!!" << endl;
                if (1 + (rand () % 649) == 557) cout << "Nowe u hav a rel liv Dwebble!!!!!" << endl;
                if (1 + (rand () % 649) == 558) cout << "Nowe u hav a rel liv Crustle!!!!!" << endl;
                if (1 + (rand () % 649) == 559) cout << "Nowe u hav a rel liv Scraggy!!!!!" << endl;
                if (1 + (rand () % 649) == 560) cout << "Nowe u hav a rel liv Scrafty!!!!!" << endl;
                if (1 + (rand () % 649) == 561) cout << "Nowe u hav a rel liv Sigilyph!!!!!" << endl;
                if (1 + (rand () % 649) == 562) cout << "Nowe u hav a rel liv Yamask!!!!!" << endl;
                if (1 + (rand () % 649) == 563) cout << "Nowe u hav a rel liv Cofagrigus!!!!!" << endl;
                if (1 + (rand () % 649) == 564) cout << "Nowe u hav a rel liv Tirtouga!!!!!" << endl;
                if (1 + (rand () % 649) == 565) cout << "Nowe u hav a rel liv Carracosta!!!!!" << endl;
                if (1 + (rand () % 649) == 566) cout << "Nowe u hav a rel liv Archen!!!!!" << endl;
                if (1 + (rand () % 649) == 567) cout << "Nowe u hav a rel liv Archeops!!!!!" << endl;
                if (1 + (rand () % 649) == 568) cout << "Nowe u hav a rel liv Trubbish!!!!!" << endl;
                if (1 + (rand () % 649) == 569) cout << "Nowe u hav a rel liv Garbodor!!!!!" << endl;
                if (1 + (rand () % 649) == 570) cout << "Nowe u hav a rel liv Zorua!!!!!" << endl;
                if (1 + (rand () % 649) == 571) cout << "Nowe u hav a rel liv Zoroark!!!!!" << endl;
                if (1 + (rand () % 649) == 572) cout << "Nowe u hav a rel liv Minccino!!!!!" << endl;
                if (1 + (rand () % 649) == 573) cout << "Nowe u hav a rel liv Cinccino!!!!!" << endl;
                if (1 + (rand () % 649) == 574) cout << "Nowe u hav a rel liv Gothita!!!!!" << endl;
                if (1 + (rand () % 649) == 575) cout << "Nowe u hav a rel liv Gothorita!!!!!" << endl;
                if (1 + (rand () % 649) == 576) cout << "Nowe u hav a rel liv Gothitelle!!!!!" << endl;
                if (1 + (rand () % 649) == 577) cout << "Nowe u hav a rel liv Solosis!!!!!" << endl;
                if (1 + (rand () % 649) == 578) cout << "Nowe u hav a rel liv Duosion!!!!!" << endl;
                if (1 + (rand () % 649) == 579) cout << "Nowe u hav a rel liv Reuniclus!!!!!" << endl;
                if (1 + (rand () % 649) == 580) cout << "Nowe u hav a rel liv Ducklett!!!!!" << endl;
                if (1 + (rand () % 649) == 581) cout << "Nowe u hav a rel liv Swanna!!!!!" << endl;
                if (1 + (rand () % 649) == 582) cout << "Nowe u hav a rel liv Vanillite!!!!!" << endl;
                if (1 + (rand () % 649) == 583) cout << "Nowe u hav a rel liv Vanillish!!!!!" << endl;
                if (1 + (rand () % 649) == 584) cout << "Nowe u hav a rel liv Vanilluxe!!!!!" << endl;
                if (1 + (rand () % 649) == 585) cout << "Nowe u hav a rel liv Deerling!!!!!" << endl;
                if (1 + (rand () % 649) == 586) cout << "Nowe u hav a rel liv Sawsbuck!!!!!" << endl;
                if (1 + (rand () % 649) == 587) cout << "Nowe u hav a rel liv Emolga!!!!!" << endl;
                if (1 + (rand () % 649) == 588) cout << "Nowe u hav a rel liv Karrablast!!!!!" << endl;
                if (1 + (rand () % 649) == 589) cout << "Nowe u hav a rel liv Escavalier!!!!!" << endl;
                if (1 + (rand () % 649) == 590) cout << "Nowe u hav a rel liv Foongus!!!!!" << endl;
                if (1 + (rand () % 649) == 591) cout << "Nowe u hav a rel liv Amoonguss!!!!!" << endl;
                if (1 + (rand () % 649) == 592) cout << "Nowe u hav a rel liv Frillish!!!!!" << endl;
                if (1 + (rand () % 649) == 593) cout << "Nowe u hav a rel liv Jellicent!!!!!" << endl;
                if (1 + (rand () % 649) == 594) cout << "Nowe u hav a rel liv Alomomola!!!!!" << endl;
                if (1 + (rand () % 649) == 595) cout << "Nowe u hav a rel liv Joltik!!!!!" << endl;
                if (1 + (rand () % 649) == 596) cout << "Nowe u hav a rel liv Galvantula!!!!!" << endl;
                if (1 + (rand () % 649) == 597) cout << "Nowe u hav a rel liv Ferroseed!!!!!" << endl;
                if (1 + (rand () % 649) == 598) cout << "Nowe u hav a rel liv Ferrothorn!!!!!" << endl;
                if (1 + (rand () % 649) == 599) cout << "Nowe u hav a rel liv Klink!!!!!" << endl;
                if (1 + (rand () % 649) == 600) cout << "Nowe u hav a rel liv Klang!!!!!" << endl;
                if (1 + (rand () % 649) == 601) cout << "Nowe u hav a rel liv Klinklang!!!!!" << endl;
                if (1 + (rand () % 649) == 602) cout << "Nowe u hav a rel liv Tynamo!!!!!" << endl;
                if (1 + (rand () % 649) == 603) cout << "Nowe u hav a rel liv Eelektrik!!!!!" << endl;
                if (1 + (rand () % 649) == 604) cout << "Nowe u hav a rel liv Eelektross!!!!!" << endl;
                if (1 + (rand () % 649) == 605) cout << "Nowe u hav a rel liv Elgyem!!!!!" << endl;
                if (1 + (rand () % 649) == 606) cout << "Nowe u hav a rel liv Beheeyem!!!!!" << endl;
                if (1 + (rand () % 649) == 607) cout << "Nowe u hav a rel liv Litwick!!!!!" << endl;
                if (1 + (rand () % 649) == 608) cout << "Nowe u hav a rel liv Lampent!!!!!" << endl;
                if (1 + (rand () % 649) == 609) cout << "Nowe u hav a rel liv Chandelure!!!!!" << endl;
                if (1 + (rand () % 649) == 610) cout << "Nowe u hav a rel liv Axew!!!!!" << endl;
                if (1 + (rand () % 649) == 611) cout << "Nowe u hav a rel liv Fraxure!!!!!" << endl;
                if (1 + (rand () % 649) == 612) cout << "Nowe u hav a rel liv Haxorus!!!!!" << endl;
                if (1 + (rand () % 649) == 613) cout << "Nowe u hav a rel liv Cubchoo!!!!!" << endl;
                if (1 + (rand () % 649) == 614) cout << "Nowe u hav a rel liv Beartic!!!!!" << endl;
                if (1 + (rand () % 649) == 615) cout << "Nowe u hav a rel liv Cryogonal!!!!!" << endl;
                if (1 + (rand () % 649) == 616) cout << "Nowe u hav a rel liv Shelmet!!!!!" << endl;
                if (1 + (rand () % 649) == 617) cout << "Nowe u hav a rel liv Accelgor!!!!!" << endl;
                if (1 + (rand () % 649) == 618) cout << "Nowe u hav a rel liv Stunfisk!!!!!" << endl;
                if (1 + (rand () % 649) == 619) cout << "Nowe u hav a rel liv Mienfoo!!!!!" << endl;
                if (1 + (rand () % 649) == 620) cout << "Nowe u hav a rel liv Mienshao!!!!!" << endl;
                if (1 + (rand () % 649) == 621) cout << "Nowe u hav a rel liv Druddigon!!!!!" << endl;
                if (1 + (rand () % 649) == 622) cout << "Nowe u hav a rel liv Golett!!!!!" << endl;
                if (1 + (rand () % 649) == 623) cout << "Nowe u hav a rel liv Golurk!!!!!" << endl;
                if (1 + (rand () % 649) == 624) cout << "Nowe u hav a rel liv Pawniard!!!!!" << endl;
                if (1 + (rand () % 649) == 625) cout << "Nowe u hav a rel liv Bisharp!!!!!" << endl;
                if (1 + (rand () % 649) == 626) cout << "Nowe u hav a rel liv Bouffalant!!!!!" << endl;
                if (1 + (rand () % 649) == 627) cout << "Nowe u hav a rel liv Rufflet!!!!!" << endl;
                if (1 + (rand () % 649) == 628) cout << "Nowe u hav a rel liv Braviary!!!!!" << endl;
                if (1 + (rand () % 649) == 629) cout << "Nowe u hav a rel liv Vullaby!!!!!" << endl;
                if (1 + (rand () % 649) == 630) cout << "Nowe u hav a rel liv Mandibuzz!!!!!" << endl;
                if (1 + (rand () % 649) == 631) cout << "Nowe u hav a rel liv Heatmor!!!!!" << endl;
                if (1 + (rand () % 649) == 632) cout << "Nowe u hav a rel liv Durant!!!!!" << endl;
                if (1 + (rand () % 649) == 633) cout << "Nowe u hav a rel liv Deino!!!!!" << endl;
                if (1 + (rand () % 649) == 634) cout << "Nowe u hav a rel liv Zweilous!!!!!" << endl;
                if (1 + (rand () % 649) == 635) cout << "Nowe u hav a rel liv Hydreigon!!!!!" << endl;
                if (1 + (rand () % 649) == 636) cout << "Nowe u hav a rel liv Larvesta!!!!!" << endl;
                if (1 + (rand () % 649) == 637) cout << "Nowe u hav a rel liv Volcarona!!!!!" << endl;
                if (1 + (rand () % 649) == 638) cout << "Nowe u hav a rel liv Cobalion!!!!!" << endl;
                if (1 + (rand () % 649) == 639) cout << "Nowe u hav a rel liv Terrakion!!!!!" << endl;
                if (1 + (rand () % 649) == 640) cout << "Nowe u hav a rel liv Virizion!!!!!" << endl;
                if (1 + (rand () % 649) == 641) cout << "Nowe u hav a rel liv Tornadus!!!!!" << endl;
                if (1 + (rand () % 649) == 642) cout << "Nowe u hav a rel liv Thundurus!!!!!" << endl;
                if (1 + (rand () % 649) == 643) cout << "Nowe u hav a rel liv Reshiram!!!!!" << endl;
                if (1 + (rand () % 649) == 644) cout << "Nowe u hav a rel liv Zekrom!!!!!" << endl;
                if (1 + (rand () % 649) == 645) cout << "Nowe u hav a rel liv Landorus!!!!!" << endl;
                if (1 + (rand () % 649) == 646) cout << "Nowe u hav a rel liv Kyurem!!!!!" << endl;
                if (1 + (rand () % 649) == 647) cout << "Nowe u hav a rel liv Keldeo!!!!!" << endl;
                if (1 + (rand () % 649) == 648) cout << "Nowe u hav a rel liv Meloetta!!!!!" << endl;
                if (1 + (rand () % 649) == 649) cout << "Nowe u hav a rel liv Genesect!!!!!" << endl;
}


		gfxFlushBuffers();
		gfxSwapBuffers();
		gspWaitForVBlank();
		if (kDown & KEY_B) break;
		if (A == 31500){
		memset(param, 0, sizeof(param));
		memset(hmac, 0, sizeof(hmac));
		APT_PrepareToDoApplicationJump(0, shopID, 0);
		APT_DoApplicationJump(param, sizeof(param), hmac); } }

	gfxExit();
	return 0;
}
